pkg/cli/debug.go
pkg/cli/download.go
pkg/cli/repo.go
pkg/cli/server.go
pkg/database/local.go
pkg/files/files.go
pkg/files/files_test.go
pkg/server/build.go
pkg/server/server.go
pkg/server/web_hook.go
pkg/serving/local.go
pkg/settings/project.go
pkg/storage/local.go

Every time a model is successfully built, each post-build web hook
gets a POST request with the model JSON (base64-encoded) and
additional metadata.

Post-build web hooks

---

go.mod
pkg/cli/build.go
pkg/cli/root.go
pkg/client/upload.go
pkg/files/files.go
pkg/server/build.go
pkg/server/server.go
pkg/zip/fs.go
pkg/zip/hash.go
pkg/zip/read.go
pkg/zip/write.go
pkg/zip/zip.go
pkg/zip/zip_test.go

Caches all files by SHA256 on the server and only uploads files that
have changed. Currently missing garbage collection so every changed
file is saved forever.

Caching zip reader/writer for faster builds

---

pkg/server/build.go
pkg/zip/hash.go
pkg/zip/read.go
pkg/zip/zip_test.go

Plus fix bug where IDs were generated before resolving cached content

Make content-addressable IDs ignore timestamps

---

pkg/docker/cog.py
pkg/serving/local.go

Show error message on bad request

---

pkg/server/build.go

Handle @files in example output

---

go.mod
go.sum
pkg/cli/server.go
pkg/docker/cog.py
pkg/docker/generate.go
pkg/docker/generate_test.go
pkg/server/build.go
pkg/server/web_hook.go

Redis queue worker model runner

---

pkg/cli/benchmark.go
pkg/cli/infer.go
pkg/cli/root.go
pkg/cli/test.go
pkg/docker/builder.go
pkg/docker/local_builder.go
pkg/model/compatibility.go
pkg/server/build.go
pkg/serving/local.go
pkg/serving/platform.go
pkg/serving/test.go

Local test command

---

pkg/cli/debug.go
pkg/cli/test.go
pkg/docker/generate.go
pkg/docker/generate_test.go
pkg/model/compatibility.go
pkg/model/config.go
pkg/model/config_test.go
pkg/server/build.go
pkg/serving/test.go

Move workdir to top level of config

---

pkg/docker/cog.py
pkg/docker/generate.go
pkg/docker/generate_test.go

Pass consumer ID to queue worker

---

end-to-end-test/end_to_end_test/test_server.py
pkg/cli/list.go
pkg/cli/login.go
pkg/cli/repo.go
pkg/cli/root.go
pkg/cli/server.go
pkg/cli/show.go
pkg/client/auth.go
pkg/client/client.go
pkg/client/delete.go
pkg/client/download.go
pkg/client/get.go
pkg/client/list.go
pkg/client/ping.go
pkg/client/upload.go
pkg/global/global.go
pkg/model/model.go
pkg/server/auth.go
pkg/server/download.go
pkg/server/server.go
pkg/server/web_hook.go
pkg/serving/local.go
pkg/serving/platform.go
pkg/serving/test.go
pkg/settings/user.go

Authentication via auth delegate

---

pkg/docker/cog.py

Write setup and run time to stderr and to a fixed-length Redis stream

Record timing information in worker

---

pkg/server/build.go

Reduce build memory usage

---

cmd/cog/cog.go
pkg/cli/root.go
pkg/global/global.go
pkg/server/profiling.go
pkg/server/server.go

HTTP profiling

---

pkg/server/build.go

Test before computing ID and uploading package to storage

---

end-to-end-test/end_to_end_test/test_server.py
pkg/server/download.go
pkg/server/server.go
pkg/storage/local.go
pkg/storage/storage.go

Download individual files from model

---

pkg/client/upload.go

Show auth errors on cog build

---

pkg/client/upload.go

Catch error when server dies to avoid spewing logs

---

pkg/docker/local_builder.go
pkg/global/global.go
pkg/model/compatibility.go

Build with Buildx on M1 Macs

---

pkg/server/build.go
pkg/server/web_hook.go

* Run "post-build" hook before "post-build-primary" hook
* Include image URI and arch

Update web hooks

---

end-to-end-test/end_to_end_test/test_server.py
pkg/cli/build.go
pkg/cli/push.go
pkg/client/build.go
pkg/server/build.go

Tail image build logs on push with -l param

---

.vscode/settings.json
Makefile
pkg/cli/debug.go
pkg/cli/download.go
pkg/cli/login.go
pkg/cli/model.go
pkg/cli/root.go
pkg/cli/test.go
pkg/docker/exists.go
pkg/docker/generate.go
pkg/docker/local_builder.go
pkg/model/config.go
pkg/server/auth.go
pkg/server/queue.go
pkg/server/queue_test.go
pkg/server/server.go
pkg/server/version_delete.go
pkg/serving/platform.go
pkg/serving/test.go
pkg/util/files/files_test.go
pkg/util/zip/zip_test.go
tools/generate_compatibility_matrices/main.go

Somewhat hesitant to put it in `make test` because that slows down the development cycle. Mayeb we can set up pre-commit or something.

Lint everything

---

pkg/util/zip/write.go
pkg/util/zip/zip_test.go

Print warning if there are symlinks in the model directory and ignore them. I added a TODO to maybe support symlinks that point to files within the tree, but that's not supported in this PR.

Handle symlinks in uploaded models

---

.github/workflows/ci.yaml
Makefile
end-to-end-test/end_to_end_test/conftest.py
end-to-end-test/end_to_end_test/test_queue_worker.py
end-to-end-test/end_to_end_test/test_server.py
end-to-end-test/end_to_end_test/util.py
end-to-end-test/requirements.txt
pkg/cli/infer.go
pkg/docker/cog.py
pkg/docker/cog_test.py
pkg/docker/cog_test_requirements.txt
pkg/serving/test.go
pkg/serving/test_test.go
pkg/util/mime/mime.go
pkg/util/mime/mime_test.go

Handle various TODOs, broken up into individual commits.

Handle todos

---

end-to-end-test/end_to_end_test/test_server.py
pkg/client/version_upload.go
pkg/server/build.go

Throw error if user tries to upload the same version twice

---

end-to-end-test/end_to_end_test/conftest.py
end-to-end-test/end_to_end_test/test_queue_worker.py
end-to-end-test/end_to_end_test/test_server.py
pkg/docker/builder.go
pkg/docker/local_builder.go
pkg/docker/mock.go
pkg/server/queue.go

Images are built, tagged with registry and content-addressable tag,
pushed, re-tagged as :latest, and the original tag is removed.
This prevents Cog from using a ton of disk space, but builds are still
fast since the cached layers from the last build are still kept around
thanks to the :latest tag.
ref #80 #18

Only keep :latest tag for local images

---

pkg/cli/root.go
pkg/docker/generate.go

Installing Cog busts the Docker cache, so do the pre-install before it.

Cache preinstall

---

end-to-end-test/end_to_end_test/test_docker_cleanup.py
end-to-end-test/end_to_end_test/test_server.py
pkg/docker/local_builder.go

Following up from https://github.com/replicate/cog/pull/88, this will
keep Cog from leaving dangling Docker images that take lots of disk
space.
Fixes #18

Attempt to delete :latest tag before tagging with :latest

---

.gitignore
end-to-end-test/end_to_end_test/test_config.py
end-to-end-test/end_to_end_test/test_queue_worker.py
end-to-end-test/end_to_end_test/util.py
pkg/cli/debug.go
pkg/cli/model.go
pkg/cli/predict.go
pkg/cli/push.go
pkg/cli/root.go
pkg/cli/run.go
pkg/cli/test.go
pkg/config/load.go
pkg/config/load_test.go
pkg/errors/errors.go
pkg/server/build.go
pkg/util/config/config.go

#102 
* Standardises config-related functionality in `utils/config.go`
* Eliminates some repetitious config loading code
* Adds a func to walk the parent directories in search of a `cog.yaml`
* Adds some basic error creation code in `pkg/errors/errors.go`
* Is this a reasonable approach?
* ~~How do we want `cog run` to work - relative to `cwd` or relative to the root (see #102)?~~
* ~~What else needs to change to allow `cog` usage in subdirectories?~~
* What's the best way to test this? Unit tests (where?), some addition to the e2e tests?
(If you like the config-loading (`utils/config.go`) refactor, we could merge that as a separate PR first to keep PRs small and lean)

refactor: re-usable config loading, and basic error definitions

---

pkg/util/terminal/glint_step_group.go

Makes build output easier to read.

Make inline terminal taller

---

end-to-end-test/end_to_end_test/conftest.py
end-to-end-test/end_to_end_test/test_queue_worker.py
pkg/docker/cog.py
pkg/docker/generate.go
pkg/docker/generate_test.go

Queue worker "tees" stdout/stderr to a Redis queue, such that each log
line becomes a message on the queue. The ID is the model URL during
setup, and the prediction ID during the run stage.

Send logs to queue

---

Makefile
python/cog/server/redis_queue.py
test-integration/test_integration/conftest.py

Since we're overwriting sys.std{out,err} with our custom logger, it
needs to implement the file methods present on the overwritten objects.

Implement expected file methods on Cog's queue logger

---

pkg/image/build.go
pkg/image/type_signature.go

GPU models might expect GPUs to exist to even be able to import.
The downside of this approach is that it is now impossible to build
GPU models on a CPU. Perhaps something we need to explain.
See also #199

Enable GPUs when fetching type signature

---

pkg/docker/build.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

This dramatically speeds up `pip install` when adding/changing pip packages, because tensorflow/torch are so goddamn huge.

Use buildkit caching for pip and apt

---

pkg/cli/login.go

This is needed when developing against a local registry

Add hidden --registry flag to cog login

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go
pkg/image/build.go

A quote in a `pre_install` step was being escaped incorrectly.
Unsurprisingly -- we were putting a shell script inside an argument
inside a string, inside a JSON document, inside a string, inside a
Dockerfile instruction.
By doing this in the post-build labelling step this works properly
(shrug). We should be really be using proper APIs as much as we can
or we're going to be endlessly battling typing/escaping problems
like this.

Set all labels after build

---

pkg/docker/build.go
test-integration/test_integration/test_predict.py

So predict output is clean and can be piped.

Redirect build stdout to stderr

---

pkg/config/compatibility.go
pkg/config/config.go

If it's not in the compatibility matrix, we don't need to stop users from installing it. It's not like GPU where we need to know the correct CUDA version.
Historically, we needed this because Cog has to support CPU and GPU _simultaneously_. But we don't do that any longer, so just let users install whatever the heck packages they like.
See also #220

Allow installing any PyTorch CPU version

---

docs/yaml.md
pkg/config/config.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

The existing `pre_install` was intentionally left undocumented
because the name was not ideal. (What is it "pre"? What's
"install"?)
"run" seems apt, because it maps directly to the Dockerfile
instruction and it's "running" these things, not "installing" them.
Known issues:
- This does not work with multiple lines.
- There should be some method of getting files in that works
efficiently even when building base images. Maybe a run command
could say what files it needs copied?
I will create separate issues for these when this is merged.
Closes #159

Add `run` build option to `cog.yaml`

---

pkg/cli/debug.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go
pkg/image/build.go

Use a single, randomly generated tempdir when building. This
means more than one build can run concurrently without colliding,
and neatens up the cleanup process.
This was a WIP implementation of #222 that I abandoned, but this
is useful separately.

Better build temp directory

---

Makefile
test-integration/Makefile

1) -vv displays full diff output so you can see what failure is
2) Enabled output capturing again, so output isn't a big mess
and failure is associated with output.
Not sure why it was this way to start with.

More sensible pytest output

---

pkg/config/compatibility.go
pkg/config/config.go
pkg/config/config_test.go

This is the GPU partner of https://github.com/replicate/cog/pull/221.
Lets you do stuff like this:
```
build:
gpu: true
cuda: "9.2"
python_version: "3.6.3"
python_packages:
- "torch==0.4.1"
```
Even though Torch 0.4.1 is not known by Cog. If you do this, it will display a warning saying things might not work correctly if you don't know what you're doing. If you don't supply `cuda`, it will fail hard.
Part of the way towards #181 and #220.

Allow PyTorch GPU versions not known by Cog

---

docs/getting-started.md

This PR updates the installation instructions in the Getting Started guide to use `sudo` to download and chmod the cog binary. This presumably wasn't working because the latest version of homebrew doesn't make `/usr/local/bin` writeable by my user.
🍐 @bfirsh

use sudo to install

---

python/cog/server/redis_queue.py
test-integration/test_integration/fixtures/timeout-project/cog.yaml
test-integration/test_integration/fixtures/timeout-project/predict.py
test-integration/test_integration/fixtures/yielding-timeout-project/cog.yaml
test-integration/test_integration/fixtures/yielding-timeout-project/predict.py
test-integration/test_integration/test_redis_queue.py

Timeouts are passed as seconds to the somewhat unwieldy list of
arguments. It is optional, so it remains backwards compatible with
models.
I have made a little helper to use Python's argument handling to parse
the argument string and set types. This should really be kwargs, or
JSON, or something.
One thought about this: timeouts using signals might happen anywhere and
might leave Predictors in unpredictable (lol) states. We might have to
see whether this is a problem in reality. If so, then we might want to
just reboot the whole worker on timeout.
@andreasjansson Can you think of any reasons off the top of your head why GPUs/Tensorflow/Torch might get left in weird states?
An additional caveat of this: if a model has a bare `except:` in it, the timeout won't work, because the signal is …

Add prediction timeouts to redis worker

---

docs/getting-started.md

`wget` is not installed by default on macOS. It's easy to `brew install wget`, but then we're assuming the user has homebrew, and would have to add some macOS-specific clause in the docs.
This PR updates the getting started to use `curl` instead of `wget`, as most users will have this command in their environment.
```
-O, --remote-name   Write output to a file named as the remote file
```

use curl instead of wget to download weights

---

docs/getting-started.md

This PR adds a note to the Getting Started guide to clarify that the first invocation of `cog predict` triggers a build.

note that build runs before first prediction

---

pkg/config/compatibility.go

Let the user manually specify things like `torchvision==0.10.0+cu111`.
Or, shoot themselves in the foot. But we told them, right?
Related to #181

Relax torchvision version check

---

docs/yaml.md

This PR updates the cog.yaml reference page to mention the `r8.im` registry.

document r8.im registry in YAML reference

---

README.md

This PR adds a section to the README describing how to upgrade Cog. I wouldn't expect this to be necessary, but for some reason on my machine if I already have cog installed and run the documented install commands, I end up with a broken binary:
```sh
$ sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
$ sudo chmod +x /usr/local/bin/cog
$ which cog
/usr/local/bin/cog                                                                        
$ cog
zsh: killed     cog
$ cog --version
zsh: killed     cog --version
```
Starting a new shell doesn't seem to help. 🤔 
Resolves https://github.com/replicate/cog/issues/315

document how to Upgrade cog versions

---

python/cog/server/redis_log_capture.py
python/cog/server/redis_queue.py
test-integration/test_integration/conftest.py
test-integration/test_integration/test_redis_queue.py

We previously missed output printed from C modules, notably TensorFlow's GPU logs that are really helpful for debugging CUDA issues.
This PR uses os.dup2() to tee stdout/stderr to a subprocess that sends log messages to the log queue. It's fiddly low-level stuff so I've added lots of comments inline.

Capture _all_ stdout/stderr in Redis worker

---

python/cog_test.py

This is hard to do without in integration tests, but we shouldn't have to do this in unit tests. 1 second aggregated over number of times we run unit tests, etc...

Mock time instead of sleeping in tests

---

docs/getting-started-own-model.md

I was finding it hard to find an example of `cog.yaml` and `predict.py`
the other day when showing someone Replicate. This is the documentation
that is linked to from replicate.ai/docs.
This also makes it a bit clearer what is going on, I think.

Add full example of cog.yaml to getting started

---

CONTRIBUTING.md

This PR updates the CONTRIBUTING docs with info about how (and why) to use a git hook for sign-off.
Resolves https://github.com/replicate/cog/issues/238

document how to automatically sign off commits

---

docs/getting-started.md

Small fix - markdown link for "install Docker" had swapped order. (I do that on accident too!)

1-line markdown change - fix typo in getting-started.md

---

python/cog/server/http.py

Predictions will be run serially and get queued up if one is already running. This is a quick fix to get GPU models serving correctly.
The real fix is being incorporated into #259 and #343.

Don't use threads or processes for HTTP server

---

.all-contributorsrc
CONTRIBUTING.md
README.md

This PR sets up [All Contributors](https://allcontributors.org/) on the project so we can recognize contributions in all their various forms, not just commits.
- Added the @allcontributors bot which we can use to add contributors directly from Issue and PR comments.
- Added docs on how and we acknowledge contributions.
- Added the folks from GitHub's [Contributors](https://github.com/replicate/cog/graphs/contributors) page. There are more folks not on that list that we can add manually after this lands.
- There's a CLI for adding contributors but we probably need it since we have the GitHub bot. We can add it later if needed.
---
Here's what it look like in the rendered README:

recognize all contributors

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

Not having wheel installed makes installing some packages very slow. We
noticed dlib particularly.
Docker's Python base image already installs the wheel package, but it is
not installed when we install Python ourselves with pyenv.

Install wheel with pyenv Python

---

.github/workflows/ci.yaml

This would have caught a bug we found in new Cog on Python 3.7.
Ref #196. This is implicitly defining some of the Python versions we
support, but they are not enforced in Cog yet.
/cc @preeth1

Run Python tests on multiple Python versions

---

python/cog/server/redis_queue.py
python/setup.py
requirements-dev.txt

Fixes a deprecation warning. Looks like there was one undocumented
internal API change that affects us.

Upgrade to redis-py 4

---

.vscode/settings.json

Does what it says on the tin. 🥫

update VS Code settings to format Python files on save

---

requirements-dev.txt

Installing 1.21.1 failed locally because the binary is only available for older versions of Python.
Although the latest version of numpy is 1.22.2, the latest version that includes support for Python 3.7 is 1.21.5.
Signed-off-by: Dominic Baggott <dominic.baggott@gmail.com>

Upgrade numpy to 1.21.5

---

python/cog/predictor.py
python/tests/server/test_http_input.py
test-integration/test_integration/fixtures/failing-project/predict.py

If an output type isn't specified, Pydantic expects the model to return nothing. When the model returns an output and it's compared to `None`, an error is logged and a 500 error is returned.
This change explicitly raises an error when the output type is undefined and raises an error message, rather than defaulting to `None`. The error message provides explanation of how to fix the issue more clearly than the original behaviour.

Display better error when output type is undefined

---

README.md

This is a follow-up to https://github.com/replicate/cog/pull/415#discussion_r802998007 that nestles the story about Cog in subheadings of the "What is Cog?" heading, and removes them from the TOC to tighten things up a bit.
Before | After
--- | ---

nestle the story and shorten the TOC

---

.goreleaser.yaml
CONTRIBUTING.md

This updates the goreleaser config to support prereleases, and updates the CONTRIBUTING guide with instructions on how to create a prerelease.
https://goreleaser.com/customization/release/#github

support and document prereleases

---

python/cog/predictor.py
python/tests/server/test_http.py
python/tests/server/test_http_input.py

Allow only a short list of types for model inputs. We can extend this list in the future much more easily than restricting it.
Add a test to assert an error is raised when starting the server. Remove the test for extraneous keys, because the server won't start any more with that predictor definition.
There's a minor weirdness for the Cog types: within Cog, `Path` and `File` are available in the module `cog.types`, but when Cog is imported into another project they're in the module `cog`. We've written some special case code to handle that, but don't know enough about Python packaging to understand why there's a difference, and whether there's a better way to handle this.

Strictly limit the allowed model input types

---

docs/getting-started-own-model.md
docs/python.md
python/cog/types.py
python/tests/server/test_http_input.py

Due to [this pydantic bug](https://github.com/tiangolo/fastapi/issues/240), the `gt` and `lt` options for `cog.Input` do not work and cause the schema parsing to fail. This PR removes them and fixes the tests / documentation to not use them.

Remove `lt` and `gt` as `cog.Input` options

---

python/cog/predictor.py
python/cog/server/http.py
python/cog/server/redis_queue.py
python/cog/types.py
python/tests/server/test_http_input.py

This is a todo item in #407. This was much easier than expected. In short, we're adding a `cleanup()` method to the dynamically generated `Input` method that can be called to remove all of its files. It gets called after a prediction is run -- inside a try/finally so it is _always_ run.
Output files in the Redis queue were already cleaned up, it was just input files that were not. Output files are not cleaned up for the HTTP server, but it is not designed to be production-ready yet so this can be a piece of follow-up work.
@evilstreak I did a bit of exploratory work to see how complex this would be, and in the end the exploratory work just turned into the implementation. Sorry. 😂

Clean up temporary input files

---

python/cog/predictor.py
python/tests/server/test_http.py

If you call your custom output object `Output`, then FastAPI cleverly tries to dedupe and called it `modulename_Output`. This isn't particularly helpful because the whole point is we're trying to make it consistently called `Output`.
This feels a bit fragile, and could break `Input` too. I've expressed the problem here for future fixing: https://github.com/replicate/cog/issues/453

Only set custom Output object if it's not already called Output

---

docs/python.md

Does what it says on the tin.
Part of https://github.com/replicate/cog/pull/407

Document `cog.File()` and `cog.Path()`

---

pkg/cli/push.go
pkg/global/global.go

Show a message after a successful push. If the push was to the Replicate registry then also show a link to the model page on replicate.com.
(It's using `localhost:8100` as the replicate registry in development – in the wild that'd be matching against and replacing `r8.im`)
I talked to @bfirsh about displaying a message from replicate.com rather than hardcoding this into Cog. Unfortunately, there's no existing call made to replicate.com after the `docker push` command has completed, and there's no way I know of to make `docker push` display more info by feeding it a suitable response from the server.
So, although it's much harder to update this when it's in Cog (because rolling out new code changes requires people to update their version), this seems like the right place to have it for …

Show a replicate.com link after pushing to r8.im

---

python/cog/predictor.py
python/cog/server/http.py
python/cog/server/redis_queue.py
python/tests/server/test_http.py
test-integration/test_integration/fixtures/yielding-project/predict.py
test-integration/test_integration/fixtures/yielding-timeout-project/predict.py
test-integration/test_integration/test_redis_queue.py

An implementation of #462. This is a precursor to supporting progressive output for Pydantic Cog models on Replicate.
It's not documented, but it wasn't documented before, so I think we can defer that. #435
There is another bug fix in here with a little semantic change to the progressive output response. Details in the commit.
Closes #462

Make progressive output a list

---

python/cog/__init__.py

We're doing a backwards incompatible change anyway, and this is actually
a neat bit of forced compatibility. If you try to use a old Cog model
with new Cog it will just fail because it can't import `Predictor`,
instead of failing somewhere deeper in the stack.

Remove cog.Predictor

---

python/cog/server/redis_queue.py
test-integration/test_integration/fixtures/yielding-file-project/cog.yaml
test-integration/test_integration/fixtures/yielding-file-project/predict.py
test-integration/test_integration/test_redis_queue.py

Inputs were being cleaned up prematurely for progressive predictors. This caused all progressive output models that take files as input to throw errors.
This fix moves input cleanup to the cleanup_functions that are run after the prediction has finished.

Fix yielding predictor cleanup bug

---

python/cog/predictor.py
python/cog/response.py
python/tests/server/test_http.py

This is stopping `choices` work on `Input`.
This is what the pydantic docs tell us to do: https://pydantic-docs.helpmanual.io/usage/types/#enums-and-choices
We need to do multiple inheritance to make the types work. It's always
a string, but may as well use InputType in case we support other things
in the future.
Also included a related fix to add a type to Response.status.
h/t @dashstander for the report!

Add types to enums in the schema

---

docs/getting-started.md

This PR updates the getting started guide with a note about how to view the dockerfile generated by Cog. A better long-term home for this information would be Cog's CLI docs, but those don't exist yet. See https://github.com/replicate/cog/issues/433
Resolves https://github.com/replicate/cog/issues/265

document `cog debug dockerfile`

---

pkg/cli/init-templates/predict.py

The `lt` and `gt` options to the cog `Input` object are no longer supported: https://github.com/replicate/cog/pull/448
This PR updates the `predict.py` template generated by `cog init` to use the `ge` and `le` options instead.

use `ge` and `le` options in predictor template

---

python/cog/predictor.py
python/tests/server/test_http.py
test-integration/test_integration/fixtures/many-inputs-project/cog.yaml
test-integration/test_integration/fixtures/many-inputs-project/predict.py
test-integration/test_integration/test_predict.py

Subclassing InputTypeEnum from `(int, enum.Enum)` caused validation
error in both the HTTP and Redis workers. Interestingly, this wasn't
caught by the existing `test_choices_int` test in test_http_input.py.

Fix int enums

---

python/cog/predictor.py
python/cog/response.py
python/cog/server/http.py
python/tests/server/test_http.py

The multi-line `"""heredocs"""` we define in the Request and Response objects become the `description` values in the OpenAPI schema. This updates those descriptions for consistency.
Toward #413 and #475 
---

make the description consistent in Request and Response schemas

---

pkg/cli/init-templates/cog.yaml
test-integration/test_integration/test_build.py

The `cog init` command generates a boilerplate `cog.yaml` file with commented-out stanzas. This default output includes empty lists, which are not actually valid YAML.
```yaml
foo:
```
This PR resolves that issue by commenting out the entire stanza, leaving it up to the user to selectively uncomment or remove the default config as needed.
Resolves https://github.com/replicate/cog/issues/468

fix invalid empty lists from `cog init`

---

docs/python.md

`Output` is a thing the user defines, not a built-in Cog thing. I'm not sure the best hierarchy for this in the document, but this is clearer than it was before.
I have removed the API documentation because this is confusing for people trying to implement models for Replicate. Perhaps this should live in some separate API documentation?

Fix output documentation

---

README.md
docs/http.md

This is a work-in-progress implementation of #413. I was considering creating an issue to discuss the design of the HTTP API, but I figure a pull request and some documentation might be the most productive medium for doing this.
The text of the documentation is incomplete and might be partial sentences. Mainly looking here for feedback on the API, then we can complete all the sentences.
I think it is mostly there, but a few design questions:
1. Do we like our request and response objects?
2. Do we like our status names? (Maybe `failure` instead of `failed`? Is there some prior art here we can build upon instead of inventing something new?)
3. #428
4. Is this compatible with #437 and #443?
5. File handling is a work in progress and I will create a separate piece of documentation about …

Design & document HTTP API

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

This seemed to be timing out in CI for some reason. All
https://pyenv.run does is call this script.

Install pyenv from github

---

README.md
notebooks.md

This PR adds a new file `docs/notebooks.md` which describes how to run a notebook server with Cog, and how to import a notebook into a Cog predictor.

document how to use notebooks with cog

---

README.md
docs/redis.md

Something that is kind-of missing here is that the Redis API is not just
undocumented, it's also not stable. I wonder whether we need to mention
that?

Make it clear what is incomplete

---

pkg/global/global.go
pkg/image/build.go
pkg/image/config.go
pkg/image/openapi_schema.go
test-integration/test_integration/test_build.py

Once we've added support for run.cog labels to Replicate, it should be
pretty safe to remove generating the old ones. Users will have to update
their Cog client to run new models.
We should leave in support for the old labels for running models --
there are lots on Replicate.

Switch to cog.run labels

---

pkg/image/build.go
test-integration/test_integration/test_build.py

Looking at them in `docker inspect` output the former just looks really
clumsy. Now that "cog" and "version" are next to each other, it's pretty
obvious that it refers to Cog.

Rename run.cog.cog_version label to run.cog.version

---

pkg/config/config.go
pkg/config/config_test.go
pkg/dockerfile/generator_test.go

A little bit of preparatory work for #157 I did last week. We want to use the same codepath for backwards compatibility for `python_packages`, and this'll be much simpler if only one of them is set.

Only allow one of python_packages or python_requirements to be set

---

python/cog/json.py
python/tests/test_json.py

Fixes the getting started guide, which returns numpy floats in tuples.
Based on FastAPI's json_encodable:
https://github.com/tiangolo/fastapi/blob/26f725d259c5dbe3654f221e608b14412c6b40da/fastapi/encoders.py#L111
Ref #541
Closes #499

Recursively encode tuple outputs

---

python/cog/predictor.py
python/tests/server/test_http_input.py

Fix enums being passed to predict() when using `choices`

---

docs/redis.md

A first version of docs for the queue API. We'll probably want to revisit these after folks start using them for real.

Document the Redis queue API

---

README.md
docs/notebooks.md

The README currently gives the impression that users can run `$ cog run ... jupyter notebook ...` on a Cog model. This is true, but only works if that model has the `jupyterlab` python package installed. That package is not mentioned in the README, nor is it included in the default `cog.yaml` generated by `$ cog init`.
This PR removes the misleading `$ cog run` command from the README, and updates the notebook docs to mention that `jupyterlab` must first be installed.
A few other things we could do to make this a smoother experience for users:
- Include `jupyterlab` in the default list of deps created by `$cog init`
- Bake notebook support into every model by updating Cog to automatically install `jupyterlab` as part of the base image.
---
Resolves #560
Hat tip to @iperdomo for opening an …

update notebook docs to mention installing jupyterlab

---

python/cog/server/log_capture.py
python/cog/server/redis_queue.py
python/cog/server/runner.py
test-integration/test_integration/test_redis_queue.py

If you try to fork a new process after CUDA has been initialized, it raises an error. From [the PyTorch docs](https://pytorch.org/docs/stable/notes/multiprocessing.html#cuda-in-multiprocessing):
> The CUDA runtime does not support the fork start method; either the spawn or forkserver start method are required to use CUDA in subprocesses.
We're already doing setup within the subprocess, but it seems that some imports will start initialization of CUDA, and we're loading the predictor outside of the subprocess.
This PR moves the loading into the subprocess and switches to using spawn to start the subprocess. Doing the former without the latter is possibly enough, but we'd need to spend more time testing that.
We should release this promptly as 0.3.1 as (some?) CUDA models won't with the …

Use multiprocessing spawn method to support CUDA

---

Makefile

When doing a local install from a dev environment using `make install` you get a binary with a version of `dev`.
In order to support breaking changes in Cog's APIs, we're building systems that switch based on the version of Cog that was used to build and push a model. For that to work for locally modified and installed versions, we need a more useful version number.
As we're using something similar to semantic versioning (and will actually use semantic versioning from 1.0.0 onwards), this uses the `+suffix` syntax for denoting build metadata:
> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST …

Base version for make install on latest release tag

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

NVIDIA's apt repositories are broken: https://github.com/NVIDIA/nvidia-docker/issues/1631
We don't install anything from the NVIDIA because it's all already installed in the base image, so just remove them for now.

Remove NVIDIA apt sources/key

---

go.mod
go.sum

Dependabot was struggling to do this by itself and throwing a minor
security warning (which was annoying).

Upgrade github.com/opencontainers/image-spec

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

This fixes an issue I had when I was installing both pytorch and tensorflow in the `run` block. cog expected some files to be there that weren't, this allows it to continue.
Signed-off-by: Dashiell Stander <dash.stander@gmail.com>

Does not fail if there are not any nvidia packages to remove

---

test-integration/test_integration/test_predict.py

The old model was from before Cog 0.2.0.
Signed-off-by: Dominic Baggott <dominic.baggott@gmail.com>

Update remote image test to recent Cog model

---

docs/getting-started.md

update pillow and tensorflow versions in getting started guide

---

python/setup.py

See https://github.com/replicate/cog/pull/593#issuecomment-1122004077
This will be properly fixed by
https://github.com/replicate/cog/issues/409

Require typing-extensions>=4.1.0

---

docs/deploy.md
python/cog/command/openapi_schema.py
python/cog/predictor.py
python/cog/server/http.py
python/cog/server/redis_queue.py
python/cog/server/runner.py

FastAPI uses threads for concurrency when the view function is synchronous, which is the case for `POST /predictions`. By default, the thread pool is 40. This won't work for GPU models which usually need to be run serially, and is too high for CPU models which are usually CPU bound. This may also be causing it to run out of memory (see #521).
This pull request sets the number of threads to be the number of CPUs, or just 1 if it's a GPU model. It is also configurable with the `--threads` option.
This is hard to test with an automated test, but open to ideas.
I tested locally with a simple model that sleeps:
```python
from cog import BasePredictor, Input
import time
def setup(self):
self.prefix = "hello"
def predict(self, text: str = Input(description="Text …
```

Make number of threads configurable

---

pkg/cli/root.go
pkg/update/state.go
pkg/update/update.go
test-integration/test_integration/conftest.py

Super simple thing to get this working. It works a bit like this:
- In the background, it hits `https://update.cog.run/v1/check?version=1.2.3` (easily cacheable on a CDN!)
- That endpoint responds with `{"message": "..."}` which gets stored in `~/.config/cog/update-check.json` along with a timestamp. 
- On subsequent runs, that message gets displayed before any Cog command. "A new version of Cog is available! Go to https://cog.run/docs/upgrade to upgrade."
- After an hour, it hits that endpoint again.
Any errors are swallowed and sent to debug logging so anything broken in here shouldn't break anything for the user.
I considered encoding versions in the API somehow, but this seemed like the simplest, most flexible solution. You could imagine a future where `cog update` existed and this …

Check for new versions

---

python/cog/server/runner.py
test-integration/test_integration/fixtures/long-setup-project/cog.yaml
test-integration/test_integration/fixtures/long-setup-project/predict.py
test-integration/test_integration/test_redis_queue.py

When we moved the predictor into a subprocess, the call to `setup()` stopped blocking because the work isn't happening in the main thread.
Reuse the "prediction finished" communication channel to indicate that the setup is finished. Rename `PREDICTION_DONE` to `PROCESSING_DONE` to make it a little more generic.
I'm reluctant to add a test that has a minimum run time of 15s, but the timing on setup has a slightly non-deterministic amount of delay because of getting the docker container booted.

Make queue worker wait for setup before taking jobs

---

python/cog/server/redis_queue.py

Hopefully this will make it a little easier to debug the state of individual predictions in large clusters.

Log message_id in messages from Redis queue worker

---

python/cog/server/runner.py

An output type of `List[Output]` would break because of the problems that `make_pickleable` works around. This change makes that work, by making pickleable each item in the list.
This is still a bandaid.
Fixes #652

Support lists of complex outputs in queue worker

---

python/cog/predictor.py
python/tests/server/test_http.py

Iterators represent progressive output, lists just represent several
outputs. On Replicate, we want to be able to differentiate between these
two so iterators have a slider and lists are displayed as a grid.

Annotate iterators so we can differentiate from lists

---

docs/python.md

People often try to set output values to `None`, only to discover that type checking fails. This PR updates the documentation for `Output` to clarify that unwanted values can be omitted.
cc @vccheng2001 @chenxwh

document how to optionally set output properties

---

docs/redis.md
mypy.ini
python/cog/server/redis_queue.py
python/cog/server/runner.py
python/setup.py

This adds some basic spans to setup and to predictions when running the predictor via the Redis queue worker.
Telemetry is enabled when the `OTEL_SERVICE_NAME` environment variable is set. The OTLP exporter also needs to be [configured via environment variables][1].
[1]: https://opentelemetry-python.readthedocs.io/en/latest/sdk/environment_variables.html
If a `traceparent` parameter is provided with the prediction request, Cog will use that value as the parent for the prediction spans. This allows spans from Cog to show up in distributed traces.
This PR includes a lot of whitespace churn due to the new `with …:` blocks, so is probably best reviewed with [?w=1](646/files?w=1)

Add OpenTelemetry instrumentation to queue worker

---

python/cog/server/redis_queue.py
test-integration/test_integration/test_redis_queue.py

Currently the only way to know whether Cog has picked up a request is to watch for jobs to be claimed from the request queue. Sending an empty processing message is a much cleaner way to handle that, and will be picked up by whatever system folks are using to listen to non terminal responses.
PR also includes a commit to swap `brpop` to `blpop`, to fix a timing issue which was exposed by this change.

Send response when queue worker starts predict

---

python/setup.py

Seeing this:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/site-packages/cog/server/redis_queue.py", line 20, in <module>
from .runner import PredictionRunner
File "/usr/local/lib/python3.8/site-packages/cog/server/runner.py", line 14, in <module>
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter  # type: ignore
File "/usr/local/lib/python3.8/site-packages/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py", line 22, in <module>
from opentelemetry.exporter.otlp.proto.grpc.exporter import (
File …
```

Pin protobuf to make opentelemetry work

---

docs/redis.md
python/cog/server/redis_queue.py
test-integration/test_integration/test_redis_queue.py

Timestamps are useful for calculating how long a prediction has taken to run. There are other ways we could get this data (using HTTP streams instead of queueing, and doing accurate timing from the outside), but this is probably the simplest to get started with and arguably the simplest for all sorts of users in the future.
Signed-off-by: Dominic Baggott <dominic.baggott@gmail.com>
Resolves #589

Include timestamps in Redis responses

---

python/cog/server/redis_queue.py

[A breaking change](https://github.com/redis/redis-py/pull/2252) in `redis==4.3.4` breaks Cog.
This PR handles the new XAUTOCLAIM response format in a backwards-compatible way.
Closes https://github.com/replicate/cog/issues/671

Handle new XAUTOCLAIM response introduced in redis>=4.3.4

---

pkg/update/state.go
pkg/update/update.go

I made the update check display a message for #672 but the message
doesn't reset when people upgrade.

Reset upgrade state when upgraded

---

python/cog/server/redis_queue.py
python/cog/server/runner.py
test-integration/test_integration/fixtures/timeout-project/predict.py
test-integration/test_integration/test_redis_queue.py

When the Redis queue worker is responsible for handling timeouts, the predictor process continues running after the queue worker sends the timeout message. If another job gets picked up before the queue worker is finished, it'll send back outputs from the previous job.
Moving it into the runner means the predictor itself is timed out and stops running. Expand the test case to demonstrate the issue and prevent regression.
Contains a couple of the preliminary fixes from #678, and a semi-related fix to timeout logic. Best viewed commit-by-commit with whitespace diffs turned off.

Fix timeout behaviour

---

.github/workflows/ci.yaml

The 10.15 test runner is being deprecated: https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/

Update macos test version from 10.15 to 12

---

docs/redis.md
python/cog/server/redis_queue.py
test-integration/test_integration/fixtures/failing-after-output-project/predict.py
test-integration/test_integration/fixtures/logging-project/predict.py
test-integration/test_integration/fixtures/yielding-file-project/predict.py
test-integration/test_integration/fixtures/yielding-list-of-complex-output-project/predict.py
test-integration/test_integration/fixtures/yielding-project/predict.py
test-integration/test_integration/test_redis_queue.py

We're sending complete snapshots, so we don't need to keep intermediate states. The downside of putting the complete states onto a regular list is that we're adding monotonically increasing snapshots to it. In extreme cases, the size and number of those items can overwhelm the Redis server.
Using a string key should also be slightly more resilient than popping off a list, as we don't lose the latest state if something goes wrong.

Use a string key for responses instead of a list

---

pkg/config/compatibility.go
pkg/config/config.go
pkg/config/config_test.go

Tensorflow counterpart of #229.
Closes #181
This code is quite spaghetti-like now, so there are a few random bodges in there to make the errors work right. I just bashed away at this until the tests passed and the project reported in #694 worked. Could do with refactor at some point, as mentioned in #181.

Allow unsupported tensorflow versions

---

docs/python.md
pkg/cli/predict.go
test-integration/test_integration/fixtures/file-list-output-project/cog.yaml
test-integration/test_integration/fixtures/file-list-output-project/predict.py
test-integration/test_integration/test_predict.py

Lots of models output multiple files -- either progressive output or batches of files.
This pull request makes `cog predict` output them as `output.0.png`, `output.1.png`, etc. The test is pretty illustrative.

Output multiple files

---

.github/workflows/ci.yaml

Push the exact thing we install inside the container to PyPi.
This is not well documented – it's not clear how to use the PyPi package standalone. In short, you can run `python -m cog.server.http`, so long as there's a `cog.yaml` with a `predictor` key in it. Not ideal, but we can fix this up later.
I have tested this little script locally, but not tested the actual push to PyPi obviously. We can fix it live if it doesn't work. I have set the `PYPI_TOKEN` secret.
Closes #146

Push package to PyPi

---

docs/redis.md
python/cog/server/redis_queue.py
test-integration/test_integration/test_redis_queue.py

Two changes:
- Add `started_at` and `completed_at` and `metrics` to the queue worker response, to match [the API provided by Replicate](https://replicate.com/docs/reference/http).
- Echo back, as part of the webhook response, any and all fields send as part of the request.

Update response schema

---

CONTRIBUTING.md

Contributing current specifies that you should use a different version of golang than the CI system uses
Signed-off-by: Jesse Andrews <anotherjesse@gmail.com>

update docs to 1.18 version of Go (used in CI)

---

docs/redis.md
python/cog/files.py
python/cog/server/redis_queue.py
test-integration/test_integration/test_redis_queue.py
test-integration/upload_server/app.py

Using a simple PUT request with the file contents as the body, rather than as multipart/form-data, means we can upload directly to GCS with a little redirecting.
Closes #734 
See also #496. We could take this opportunity to adjust the API, which I've not done here yet.

Send file uploads as a basic PUT

---

.gitignore
python/cog/response.py
python/cog/server/redis_queue.py
python/cog/server/response_throttler.py
python/tests/server/test_response_throttler.py

Introduces a new environment variable `COG_THROTTLE_RESPONSE_INTERVAL` that lets the user control the rate at which non-terminal webhooks are sent.

Throttle webhook responses

---

docs/redis.md
python/cog/response.py
python/cog/server/redis_queue.py
python/cog/server/runner.py
python/tests/server/test_http.py
test-integration/test_integration/test_redis_queue.py

Allow a Redis key to be provided for each prediction. If that key is created at any point during the prediction, the worker will interrupt the predictor and return a terminal `canceled` response.
Closes #723

Handle cancelations in Redis queue worker

---

pkg/cli/predict.go
pkg/predict/predictor.go

When running `cog predict` if the user hits "ctrl-c" the docker container is left running
This catches the ctrl-c and terminates docker container

stop container on ctrl-c during cog predict

---

python/cog/server/redis_queue.py
test-integration/test_integration/test_redis_queue.py

`pipe.send()` is non-blocking when you send less than 64K of data. When you send more than that, the call blocks until something calls `recv()`. That causes a deadlock, where the predictor process is blocked on `send()`, and the parent process is waiting for it to send the `PROCESSING_DONE` signal.
This rejigs the non-generator output path to ignore the `PROCESSING_DONE` signal, because there's only going to be a single output.
I don't think there's a deadlock in the generator path, but I haven't tested it to be sure.
This whole lot of code is due a rewrite pretty soon anyway!

Fix deadlock for large outputs

---

python/cog/server/redis_queue.py
python/cog/server/runner.py
test-integration/test_integration/fixtures/unhandled-error-project/cog.yaml
test-integration/test_integration/fixtures/unhandled-error-project/predict.py
test-integration/test_integration/test_redis_queue.py

Continuously check if the runner has a subprocess that's alive, and return an error if not.

Handle dead predictor process

---

python/cog/server/redis_queue.py

This should prevent us from creating zombie pods.

Shut down if the runner died

---

pkg/dockerfile/generator.go

the function is only used on GPU dockerfile generation. This lets code readers understand the scope of the install
Signed-off-by: Jesse Andrews <anotherjesse@gmail.com>

rename installpython function to include scope - cuda

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

- container is built with pyenv
- pyenv doesn't need python-openssl installed to function
- appears that cog models do not rely on a side-effect of python-openssl install (libssl-dev is installed explicitly)
- if cog models need python-openssl, it can be installed by updating the model's cog.yaml
```
python_packages:
- "pyOpenSSL==22.1.0"
```
This change is because python-openssl was renamed to python3-openssl in more recent versions of ubuntu
Signed-off-by: Jesse Andrews <anotherjesse@gmail.com>

python-openssl system package not used

---

python/setup.py

Currently installed version of protobuf@3.20.0 has a vulnerability
https://security.snyk.io/vuln/SNYK-PYTHON-PROTOBUF-3031740
[A potential Denial of Service issue in protobuf-cpp and protobuf-python ](https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf)
```
Issues to fix by upgrading dependencies:
Pin protobuf@3.20.0 to protobuf@3.20.2 to fix
✗ Denial of Service (DoS) [Medium Severity][https://snyk.io/vuln/SNYK-PYTHON-PROTOBUF-3031740] in protobuf@3.20.0
introduced by cog@0.4.4 > protobuf@3.20.0 and 4 other path(s)
```
Allowing protobuf to use the newest patch version fixes the problem.

Require protobuf<=3.20.3 (fix a potential Denial of Service issue)

---

pkg/config/config.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

Undocumented, and GitHub code search implies unused. If you want to do this, you can use `run`, and when we have #714 you can put it in `requirements.txt`.
Yanked out of #714

Remove python_extra_index_urls and python_find_links

---

python/cog/server/worker.py

This should hopefully fix the problem we're seeing in production of very mixed up Kubernetes logs.

Flush tee-d output after each line

---

docs/redis.md
python/cog/server/probes.py
python/cog/server/redis_queue.py
python/tests/server/test_probes.py

This can be checked by an exec readiness probe and used to control deployment rollout for model pods.

Write a file when setup is complete

---

python/cog/server/redis_queue.py
python/cog/server/webhook.py
test-integration/test_integration/fixtures/failed-setup-project/cog.yaml
test-integration/test_integration/fixtures/failed-setup-project/predict.py
test-integration/test_integration/test_redis_queue.py

Expose setup logs in a similar way to prediction outputs.

Send timings and logs for setup to a URL

---

pkg/config/compatibility.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/load.go
pkg/config/load_test.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

This is a partial implementation of #157 that is mostly backwards compatible.
Previously, we read `python_packages`, did our clever processing on it to resolve PyTorch/Tensorflow versions, then inserted it into the `Dockerfile` as a long `pip install` line. There was also an undocumented `python_requirements` option that naively did `pip install -r requirements.txt` without any dependency resolution.
In #157, we want to migrate to using `python_requirements` instead, and do our clever processing on `requirements.txt`. This pull request is a step towards that.
It does a few things:
- `python_requirements` is read into the system that does our clever dependency resolution. Lines that are not able to be processed by Cog (anything that's not `package==version`) are ignored.
- …

Resolve dependencies in `python_requirements`

---

pkg/docker/build.go

Signed-off-by: Youka <59315275+youkaclub@users.noreply.github.com>
Usually docker build load automatically the build results to local registry, in buildx --load is required
Close #797

load flag is required in buildx

---

docs/redis.md
python/cog/response.py
python/cog/server/redis_queue.py
test-integration/test_integration/test_redis_queue.py

The main reason for this is to allow us to not send a webhook every time there's a new log line (which can happen a lot!) when all the consumer cares about is new outputs.
Closes #786.
---
I'm interested in feedback on the API this provides as much as the implementation. `webhook_events` feels like a natural accompaniment to `webhook`, and is something we would want to provide through other interfaces like the HTTP API.
It can also naturally encompass the `webhook_completed` property currently exposed through the Replicate API, by passing `{"webhook": "...", "webhook_events": ["done"]}`.

Accept list of events to send webhooks for

---

.github/workflows/ci.yaml
.gitignore
Makefile

This PR implements some changes I needed to get a Homebrew formula working (see https://github.com/replicate/cog/issues/822), specifically:
- Defining constants for executables like `PYTHON`. When Homebrew installs Python 3, my understanding is that it links to `python3`, keeping the default `python` (2.7) executable accessible in the default `PATH`. Because Python 3 is a prerequisite for building from source, we need a way to override this when running `make`.
- Adding an `install` target. In this PR, it's configured to be overridden by conventional `PREFIX` / `BINDIR` constants. It also supports [staged installs](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) using a `DESTDIR` constant.
This PR includes some other changes to keep the rest of the `Makefile` more consistent:
- …

Refactor `Makefile`

---

pkg/cli/init_test.go
pkg/config/config_test.go
pkg/config/load_test.go
pkg/dockerfile/generator_test.go
pkg/util/files/files_test.go

A testing cleanup. 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
assert.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```

test: use `T.TempDir` to create temporary test directory

---

python/cog/server/redis_queue.py

If SIGTERM arrives before we have started RedisQueueWorker (where we explicitly register a handler for that signal) and we are running as PID 1, the kernel will decline to kill the process.
This means that there is a period during startup where a SIGTERM will be ignored.
To avoid/minimise the possibility of this, this commit sets an explicit SIGTERM handler to quit the process which is used until overridden by the more graceful handler inside RedisQueueWorker.

Add an explicit handler to die on SIGTERM

---

README.md

Fixes #818 
The current instructions use [backquoted command substitution](https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_06_03) (<code>``</code>) to select the appropriate release artifact for the current machine. This PR updates this command to use dollar sign syntax (`$()`) instead, which is more widely supported.
Following up on the changes in #823, this PR also updates the "Install" section of the README to provide instructions for building from source. This PR also consolidates the "Upgrade" section, since you can re-run the same install command to get the latest version. Finally, I went through and annotated terminal commands with the <code>```console</code>, which adds some syntax highlighting on GitHub.
Feel free to cherry-pick only the `$()` …
```

Update install instructions in `README`

---

README.md

`brew install cog` is a thing now, thanks to @mattt! 🎉 
See https://github.com/Homebrew/homebrew-core/pull/117929
This PR updates the README's install docs to include Homebrew as an option.

document `brew install cog`

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go
pkg/image/build.go

Configure krallin/tini as the Docker image entrypoint. Ensures that signals are handled appropriately and any child processes are correctly reaped inside Cog containers.
Fixes #840.
Signed-off-by: Nick Stenning <nick@whiteink.com>

Install tini as image entrypoint

---

python/cog/director/queue_worker.py
python/cog/director/redis.py

Very simple change.
It would be slightly more work to also re-write Cog to include this when it logs to stdout; but it's certainly something I could do in a follow-up.
@nickstenning @evilstreak

cog/async-api: log prediction id

---

python/cog/director/__main__.py
python/cog/director/queue_worker.py

This matches the behaviour of the existing RedisQueueWorker. It also causes the director to shutdown if setup fails.

Report setup runs from director

---

python/cog/director/queue_worker.py
python/cog/server/runner.py
python/tests/server/test_http.py

The general principles here:
- if we're at all able to, trigger a final "failed" webhook with the error and all the logs and output so far
- if the error is irrecoverable, crash the server -- the director has to be able to handle a crashed sibling container anyway, so don't try any heroics to stay alive
---
This is untested – consider this a sketch for feedback rather than a polished-and-ready-to-go piece of code!

Tighten up error handling in PredictionRunner

---

python/cog/director/__main__.py
python/cog/director/director.py
python/cog/director/eventtypes.py
python/cog/director/healthchecker.py
python/cog/director/http.py
python/cog/director/prediction_tracker.py
python/cog/director/queue_worker.py
python/tests/director/test_healthchecker.py
python/tests/director/test_http.py
python/tests/director/test_prediction_tracker.py

First of all, I apologise for opening a pull request on the weekend. I forgot that I'm out on Monday, and I had a moment of inspiration (or at least it felt like it to me!) today and figured I would try and get ahead of things.
If I haven't completely messed this up, this PR should:
1. Address most of the remaining error handling we need to do on the director side. It handles:
- sending failure webhooks for input validation errors
- sending failure webhooks when the model container ignores cancelations
- ensuring that handled failure modes result in the redis message being ACKed
2. Make it much clearer how to integrate detection of failure of the model container while a prediction is running. This isn't done yet, but the model container healthchecking moves into its own logical thread, …

Fix a bunch of error handling edge cases in director

---

python/cog/director/director.py
python/cog/director/healthchecker.py

Increase the number of retries so that the healthcheck endpoint has to fail for roughly ~6s before emitting a `HealthcheckStatus` event with a status of `Health.UNKNOWN`. That roughly mirrors the ~5s interval we poll at when the model container is healthy.
If we get a non-healthy status event during a prediction, abort the prediction and shut everything down.

Abort prediction on a failed healthcheck event

---

python/cog/director/director.py
python/cog/director/redis.py

To keep things simple, this uses structlog's execution context variable binding (which internally uses Python's built-in `contextvars` package).
In future we may wish to consider using explicit logger binding (e.g. `bound_log = log.bind(a=123)`) but this works well enough for the moment.

Bind context for director logs while handling prediction

---

python/cog/director/director.py
python/cog/director/redis.py

At the moment we're failing to ack messages in exceptional cases (e.g. when we call _abort while handling a prediction). This is leading to a build-up of pending messages in the Redis stream which in turn results in autoscaler requesting additional replicas which are unneeded and will not participate in handling the pending messages.
For now, remove all ability to handle pending stream messages, and instead ack every message handled, whether it completed successfully or not.

Remove Redis XAUTOCLAIM and ack messages whenever possible

---

python/cog/files.py
python/cog/server/runner.py

We're seeing a handful of 408 errors when uploading files. We're assuming the upload requests reuses a connection that the destination considers stale. There's probably some smarter things to do with connection pooling, but the approach here of retrying them a few times seems like it'll catch a wider variety of intermittent network errors.

Retry file upload requests

---

python/cog/server/http.py
python/cog/server/runner.py
python/cog/server/worker.py
python/tests/server/conftest.py
python/tests/server/test_runner.py

This commit attempts to improve how server shutdown occurs, in a few different ways:
1. Exceptions thrown while running a prediction are caught, logged, and used to trigger a clean shutdown of the server. Unfortunately we cannot currently recover from an exception thrown while a prediction is running, because we have no way to resume and drain the prediction event stream.
2. Server shutdown tries to proceed gracefully, but will escalate to sending SIGKILL to the process if needs be.
3. SIGINT at the terminal is now always respected if possible.
One minor note of caution here: we are running Worker.terminate() to kill the worker, which is not a graceful shutdown. In-flight predictions will be killed immediately, and no final status webhooks will be sent. It is beholden on the director to …

Improve server shutdown behaviour

---

python/cog/director/__main__.py
python/cog/director/director.py
python/cog/director/healthchecker.py
python/tests/director/test_healthchecker.py

We wait up to 10 seconds for an explicit confirmation of the model container's health before fetching the next prediction from Redis. This should hopefully prevent us from dequeueing predictions that are bound to fail (e.g. when the model container has crashed but we have not yet detected that with the regular background checks).

Explicitly healthcheck the model container before each prediction

---

Makefile

Fixes a regression introduced in [#823](https://github.com/replicate/cog/pull/823).
**Before**
```console
$ make clean cog
$ ./cog --version
cog version v0.6.1-19-g08f4c8f (built 2023-01-25T05:21:05-0800)
```
**After**
```console
$ make clean cog
$ ./cog --version
cog version v0.6.1+dev (built 2023-01-25T05:18:20-0800)
```

Revert how `COG_VERSION` is set in cog Makefile target

---

python/cog/server/http.py

FastAPI 0.89.0 has a bug which causes the model to fail to start if handlers annotate a response class of Response (or its subclasses).
See: https://github.com/tiangolo/fastapi/pull/5855

Loosen response type annotations

---

python/cog/server/webhook.py
python/tests/server/test_webhook.py

We're happy to ignore any status response failures with this webhook, so we should be happy to ignore any connection errors too.
Without this we're actually less tolerant of network failures than the retry logic for terminal webhooks would suggest, because a single connection error on a non-terminal webhook is enough to interrupt a prediction and crash the model.

Swallow connection errors for non-terminal webhooks

---

.github/workflows/ci.yaml
python/cog/director/Dockerfile
python/cog/director/cloudbuild.yaml
python/cog/director/script/build

We get the version of the published package by looking at the filename of the wheel during the python package build step. We could try loading that wheel and checking `cog.__version__`, but that requires installing a bunch of dependencies which is more of a faff than just looking at the file. This may end up being error prone, in which case we can revisit it!

Build director image after release

---

docs/http.md
python/cog/director/director.py
python/cog/server/http.py
python/cog/server/runner.py
python/tests/server/test_http.py
python/tests/server/test_runner.py

The motivation here is that we've been seeing a few problems in production where director's call to the POST endpoint times out but succeeds on the model container. Director then retries the "failed" request and gets a failure from the Cog HTTP API because the model container is now busy.
This PR adds an idempotent `PUT /predictions/<prediction_id>` endpoint, and switches director over to using that. Hopefully, this means that an initial request timeout will be much less likely to result in a prediction failure, because subsequent retries will succeed.
The core of the change makes `PredictionRunner.predict(...)` itself idempotent if (and only if) the prediction request includes an ID. If the prediction request includes an ID, then subsequent calls to `predict()` with the same ID will …

Add an idempotent PUT endpoint for prediction creation

---

python/cog/predictor.py
python/cog/server/runner.py
python/cog/types.py

This commit moves the downloading of URLs provided as Path input parameters off the main thread and into the worker thread handling the prediction.
This has been causing issues in production because large files are downloaded before the initial PUT /predictions/<id> request responds, which results in director timing out the request and the prediction failing.
This is not code to be proud of, and we will almost certainly need to rethink it in the near future. For now, though, it appears to do the right thing: async create prediction requests now respond immediately.

Defer downloading of URLs provided to Path inputs

---

python/cog/director/director.py
python/cog/director/eventtypes.py
python/cog/director/healthchecker.py
python/cog/server/http.py
python/tests/director/test_healthchecker.py

This commit tightens up the contract between director and the model container's `/health-check` endpoint.
Specifically, the `status` field of the healthcheck endpoint now reports one of four health statuses: STARTING, READY, BUSY, SETUP_FAILED.
The expected state transitions between these four states are as follows:
┌────────┐
▼        │
STARTING ────► READY     BUSY
│            │        ▲
│            └────────┘
▼
SETUP_FAILED
Once setup is complete, we expect the model pod to cycle between READY and BUSY. If any other status is seen, or if BUSY is seen when we expect the container to be READY, we abort the pod.

Incorporate READY/BUSY status into model healthcheck

---

python/cog/director/redis.py
python/cog/server/redis_queue.py

We provide the host as context instead.

Stop leaking Redis secrets on connection

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

This reverts commit 67c5b31a143d6601df58ddd705bd707680359d6b.
#579 removed the nvidia apt sources because they were broken upstream. When CI passes here, they have been fixed and we can merge this.
See also https://github.com/NVIDIA/nvidia-docker/issues/1631

Revert "Remove NVIDIA apt sources/key"

---

python/cog/director/__main__.py
python/cog/director/director.py
python/cog/director/monitor.py
python/cog/schema.py
python/tests/director/test_monitor.py

@nickstenning @evilstreak 
This adds a `cog.prediction` and `cog.director.idle` spans from Cog
**Should we set the parent span on `cog.prediction`?** We could probably pass down the parent span id in the `Prediction` message and then set the parent span. I didn't want to go through this effort of changing yet another repo if you guys didn't think it was worth it! Let me know.
**Why do you need both `cog.director.utilization` and `cog.prediction`?** I want to be able to get a utilization number between 0 and 1, and we can't use `CONCURRENCY(cog.prediction) / availableReplicas` or something to compute it. We can get away without it, but I would love to have this 0..1 utilization number.
**How many events will this generate per month?** This will generate [around 100M events …

observability: add utilization span + prediction span

---

python/cog/director/__main__.py

Given that e.g. Refinery disables GRPC by default, I anticipate Protobuf over HTTP is the more common protocol—so we're going to default to that. I can't find an easy way for the Python SDK to properly respect `OTEL_EXPORTER_OTLP_PROTOCOL` that wouldn't be super hacky, so we'll default to this for now until the use-case arises for someone to need GRPC.
@nickstenning

director: change default trace exporter to http

---

python/cog/director/director.py
python/cog/director/monitor.py
python/tests/director/test_monitor.py

This sets span attributes from the environment if they're set. I'm not using `None` because OpenTelemetry emits warnings for span attributes set to `None`.
I could now make `set_current_prediction` in `Monitor` be replaced with `working` and `idle` methods, but it could be useful in the future for other monitoring of e.g. emitting utilization by user (highly sampled). Doesn't really do any damage IMO.
@nickstenning @evilstreak

director: set span attributes from env

---

python/cog/director/director.py

The `Prediction` object has a nice error field from the model that we weren't populating span attributes with. Now we are! Examples of this error from various models might be:
```
NSFW content detected. Try running it again, or try a different prompt.
CUDA out of memory. Tried to allocate 5.92 GiB (GPU 0; 14.76 GiB total capacity; 6.65 GiB already allocated; 4.28 GiB free; 9.52 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
@evilstreak @nickstenning

director: add prediction.error

---

pkg/config/data/config_schema_v1.0.json

Related to https://github.com/replicate/cog/issues/907
This PR adds descriptions to each of the fields in the [Cog config file JSON Schema](https://github.com/replicate/cog/blob/be661dcf719118e5ec07d00a307ea96223e60c30/pkg/config/data/config_schema_v1.0.json). The descriptions use existing language from the [YAML file docs](https://github.com/replicate/cog/blob/be661dcf719118e5ec07d00a307ea96223e60c30/docs/yaml.md).
Currently, this JSON Schema file is used only for validation. The addition of descriptions provides useful context to consumers of the schema in IDEs and editors.

Add descriptions to JSON Schema fields

---

python/cog/server/http.py
python/cog/server/runner.py

8a72ba8 accidentally changed the behaviour of container readiness checks: model containers started marking themselves as "ready" before the model setup had successfully completed.
This is a problem, because it means a deployment rollout will potentially proceed before a new container is actually ready to service incoming predictions.
This change moves our use of ProbeHelper into Runner so that it's only called once a model has successfully completed setup.

Only mark container as ready after successful setup

---

python/cog/director/director.py
python/cog/director/redis.py

If director catastrophically fails (oom killed, preempted, etc) then the only signal we have that something has gone wrong is that the prediction never finishes and the message in the queue is never acked. To make use of that signal we have to wait longer than the prediction could possibly take.
This changes the behaviour of director so that it uses `XCLAIM` to continuously update the idle time of the message it's processing. If the idle time of any message is longer than the `claim_interval` used (with a resonable margin for error) then we can assume the director responsible for it has somehow died, and we can either retry it or fail it from whatever system monitors the queue.
This is done in a thread so that issues with, eg, webhook delivery don't stop the idle time from being updated …

Repeatedly claim Redis messages during processing

---

docs/python.md
docs/redis.md
python/cog/__init__.py
python/cog/types.py
python/tests/server/fixtures/yield_concatenate_iterator.py
python/tests/server/test_http.py

Implements https://github.com/replicate/cog/issues/969 
It's the same thing, just with a different name. `Stream` is a new noun, whereas `ConcatenateIterator` is a verbose description of what it does: it is an iterator that gets concatenated.
This is an experiment at passing hints about how outputs should be displayed to Replicate. You can imagine other hints about display that we might want to pass.

Add ConcatenateIterator type

---

Makefile
pkg/cli/root.go
pkg/cli/train.go
pkg/config/config.go
pkg/config/data/config_schema_v1.0.json
python/cog/command/openapi_schema.py
python/cog/predictor.py
python/cog/server/http.py
python/cog/server/worker.py
python/tests/server/conftest.py
python/tests/server/fixtures/function.py
python/tests/server/fixtures/missing_setup.py
python/tests/server/fixtures/setup_weights.py
python/tests/server/test_http.py
python/tests/server/test_worker.py
python/tests/test_predictor.py
test-integration/test_integration/fixtures/train-project/cog.yaml
test-integration/test_integration/fixtures/train-project/predict.py
test-integration/test_integration/fixtures/train-project/train.py

This adds a `train` option to `cog.yaml` and a `cog train` command to run it.
There are a few bits of refactoring to make this possible, contained in some significant commits. Notably, predictors can now just be functions if you have no `setup()`.
`cog.yaml`:
```yaml
build:
python_version: "3.10"
train: "train.py:train"
```
`train.py`:
```python
from cog import BasePredictor, File
import io
def train(param: str) -> File:
return io.StringIO("hello " + param)
```
Then you can run it like this:
```
$ cog train -i param=train
...
$ cat weights
hello train
```
The HTTP server can be booted up in two different modes, specified with the `--x-mode` argument: `predict` and `train`.
In `predict` mode, it behaves like it did before.
In `train` mode, if you call `POST /predictions` it actually runs …

Training 🚂

---

pkg/image/build.go
test-integration/test_integration/test_build.py

If a `.git` directory exists when doing `cog build` or `cog push`, this pull request sets the label `run.cog.git_commit` from `HEAD`. This lets us link an image back to the code it was built from.
An alternate name could be `run.cog.git_head` to make it clear precisely what it is.
In the future, you could imagine some indication of whether the commit is dirty or not. I wonder whether there is a standard format for indicating this stuff beyond just appending `-dirty`?

Record git commit on images

---

docs/yaml.md
pkg/config/config.go
pkg/config/data/config_schema_v1.0.json
pkg/dockerfile/generator.go
test-integration/test_integration/test_run.py

Add support for build secrets

---

.github/workflows/ci.yaml

From https://github.com/pypa/gh-action-pypi-publish:
> The `master` branch version has been sunset. Please, change the GitHub Action version you use from `master` to `release/v1` or use an exact tag, or a full Git commit SHA.

Pin `pypa/gh-action-pypi-publish` to `release/v1` in CI workflow

---

.github/workflows/ci.yaml

For consistency with Make target names.

Rename `test` job to `test-go` in CI workflow

---

docs/yaml.md

Related to #1006
Most Cog examples use `python_packages`, but the `python_requirements` option is convenient when you already have a `requirements.txt` file or need to configure options like `--extra-index-url` or `--trusted-host`. 
This PR documents the `python_requirements` field in `yaml.md`.

Document `python_requirements` field in `cog.yaml`

---

pkg/docker/run.go

We have [logic](https://github.com/replicate/cog/blob/642f550f8cdb1fa1ff52074c5aa3f7508a351778/pkg/docker/run.go#L114) to detect when a GPU isn't available locally. Recently a user reported the following error when building a GPU model locally on a Mac:
```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
```
This PR catches that case too.

Catch missing GPU when running cog build

---

docs/http.md

This could imply the filtered events always get sent, but in reality they're only sent *if* requested, and the "always sent" refers to the lack of throttling.

Update ambiguous webhook events filter docs

---

.github/workflows/ci.yaml
python/cog/predictor.py
python/pyproject.toml

This package currently specifies `python_requires=>=3.6` and tests Python 3.7 – 3.10. 
Python 3.7 reaches EOL in June 2023 [(source)](https://devguide.python.org/versions/). Many popular libraries including [Pytorch](https://github.com/pytorch/pytorch#prerequisites) and [numpy](https://github.com/numpy/numpy/blob/954aa5856c9812b71162415b6573b397368a1da7/setup.py#L526) now require Python>=3.8.
This PR raises the Python version requirements to >= 3.8. It also adds Python 3.11 to the test matrix in our CI workflow.

Update Python version requirements

---

.github/dependabot.yml

This PR updates `dependabot.yml` to enable automatic version updates for Python dependencies.
For more information, see ["About Dependabot version updates"](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) in GitHub's documentation.

Enable Dependabot version updates for pip dependencies

---

pyproject.toml
python/cog/logging.py
python/cog/predictor.py
python/cog/server/http.py
python/cog/server/runner.py
python/cog/types.py
python/tests/server/test_worker.py

Based on #1060 
This PR resolves the mypy type checking errors in `python/cog`. 
The only remaining issues have to do with the `weights` argument passed to setup and the dynamically defined `PredictionRequest` / `PredictionResponse` types:
```console
$ python -m mypy python/cog
python/cog/predictor.py:95: error: Argument "weights" to "setup" of "BasePredictor" has incompatible type "Union[IOBase, pathlib.Path, None]"; expected "Union[File, cog.types.Path, None]"  [arg-type]
python/cog/server/http.py:141: error: Variable "PredictionRequest" is not valid as a type  [valid-type]
python/cog/server/http.py:141: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
python/cog/server/http.py:147: error: PredictionRequest? has no attribute "id" …
```

Fix various mypy type checking errors

---

python/cog/server/http.py

Reimplementation of https://github.com/replicate/cog/pull/709
Things have moved around a bit in `http.py` since the original PR was opened. Notably, the predict function is now delegated to a helper that's shared by a `POST` and idempotent `PUT` endpoint. That `raise HTTPException` call now has exception chaining that includes details in the traceback.
This PR reapplies https://github.com/replicate/cog/pull/709/commits/893b28bf7b5c4a57f3a86727fd725421c351d22e to include the original error message in the raised exception as well as chaining to that error.

Provide details in Internal Server Error responses for predict endpoint

---

pkg/config/data/config_schema_v1.0.json
pkg/config/validator_test.go

Resolves https://github.com/replicate/cog/issues/368

Allow null/empty lists for `python_packages`, `system_packages`, `pre_install`, and `run` in `cog.yaml`

---

pkg/cli/predict.go
pkg/cli/run.go
pkg/docker/run.go
pkg/predict/predictor.go

Fixes #590
I was able to reproduce the described behavior with the following example project:
```yaml
build:
python_version: "3.8"
gpu: true
python_packages:
- torch
- numpy
predict: "predict.py:Predictor"
```
```python
from cog import BasePredictor
import torch
def predict(self, size: int) -> int:
n = torch.randn([size])
if torch.cuda.is_available():
n = n.cuda()
return n.sum().item()
```
With the latest version of Cog, `cog predict` fails on my local machine with the following error:
```console
$ cog predict -i size=100
Starting Docker image cog-gpu-project-base and running setup()...
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ⅹ Failed to start container: exit status 125
```
This PR updates the `cog …

Automatically re-run command when GPU isn't available

---

pkg/docker/build.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

Follow up to #1041 
This PR updates the `COPY --from=weights` command to use the [`--link` flag](https://github.com/moby/buildkit/blob/dockerfile/1.4.0/frontend/dockerfile/docs/syntax.md#linked-copies-copy---link-add---link) that was [added in Dockerfile 1.4](https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit/). This should improve performance when rebasing existing Cog images onto new base images.
This PR also updates our invocation of `docker buildx build` to replace `BUILDKIT_INLINE_CACHE=1` with `--cache-to type=inline` and remove the redundant `DOCKER_BUILDKIT=1` environment variable.
/cc @hongchaodeng

Copy weights using `--link` option

---

pkg/cli/init-templates/cog.yaml

This PR updates the `cog.yaml` file template created when running `cog init` to use [Python 3.11](https://www.python.org/downloads/release/python-3110/). It's currently set to use Python 3.8.

Update `cog init` template to use Python 3.11

---

pkg/config/compatibility.go
pkg/docker/build.go
pkg/docker/run.go
pkg/util/platform.go

Resolves https://github.com/replicate/cog/issues/1086
Resolves https://github.com/replicate/cog/issues/1085
This PR automatically sets the `DOCKER_DEFAULT_PLATFORM=linux/amd64` environment variable for the `docker run` invocation when running `cog predict`. Without setting this, Cog logs the following warning:
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Automatically set `DOCKER_DEFAULT_PLATFORM=linux/amd64` when running `cog predict` on M1/M2 Macs

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

Weights are more likely to change than Python requirements and setup commands, so they should be copied after those layers.

Copy weights after installing Python dependencies and running setup commands

---

test-integration/test_integration/test_build.py

Follow up to #1008
I've noticed that the `test_build_gpu_model_on_cpu` integration test is flakey, sometimes failing with the following error:
```
Author identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'runner@runner.(none)')
--------------------------- Captured stderr teardown ---------------------------
Error: No such image: cog-test-iwmtrwwpjd
=========================== short test summary info ============================
FAILED test_integration/test_build.py::test_build_gpu_model_on_cpu - subprocess.CalledProcessError: Command '['git', 'commit', …
```

Configure Git user in GPU build integration test

---

docs/getting-started.md

This relies on https://github.com/replicate/cog/pull/1041. We need to merge that first.
I separate the doc change out because every git push takes a long cycle on CI testing. I would like to decouple them since this change doesn't need any CI.

doc: add best practices to building images

---

README.md
docs/getting-started-own-model.md
docs/getting-started.md
docs/yaml.md

This PR updates our documentation to use Python 3.11 and the latest versions of PyTorch, TensorFlow, and Pillow.

Update Python and dependency versions in documentation

---

.github/dependabot.yml

Currently, it's set up to run daily, which I find to be too noisy. This PR updates the `dependabot.yaml` configuration to run weekly instead.

Configure Dependabot to run weekly

---

docs/getting-started.md
pkg/cli/build.go
pkg/cli/debug.go
pkg/cli/push.go
pkg/image/build.go

#1041 adds a feature that allows large weight files to be copied in a separate layer from code, which reduces the amount of time needed to rebuild an image. This feature works well, but some users have reported problems that we should resolve before making it the default behavior.
#1095 Added a `--no-weights-image` flag to opt out of this behavior. This PR replaces that flag with a new `--separate-weights` flag that opts in to this behavior.
When separated weights becomes the default behavior, we can make this Boolean flag default to `true` and allow opting out with `--separate-weights=false`.

Make separate weights feature opt-in

---

pkg/cli/debug.go

fix https://github.com/replicate/cog/issues/1168
Actually the flag has been implemented. The code doesn't look right to extra command.
cc @mattt

fix: debug cmd should have --separate-weights

---

pkg/config/compatibility.go
pkg/config/config_test.go
pkg/config/data/config_schema_v1.0.json
pkg/dockerfile/generator_test.go
pkg/util/version/version.go

Follow-up to #1170 
Given a `cog.yaml` file that specifies `cuda: 11.6` and a dependency on `torch==1.13.0`, running `cog build` with Cog [v0.8.0-beta9](https://github.com/replicate/cog/releases/tag/v0.8.0-beta9) fails with the following error:
> ⅹ CUDA 11.6 is not supported by Cog
It should instead have matched these entries:
```jsonc
// CUDA
{
"Tag": "11.6.2-cudnn8-devel-ubuntu20.04",
"CUDA": "11.6.2",
"CuDNN": "8",
"IsDevel": true,
"Ubuntu": "20.04"
}
// Torch
{
"Torch": "1.13.0+cu116",
"Torchvision": "0.14.0+cu116",
"Torchaudio": "0.13.0",
"FindLinks": "",
"ExtraIndexURL": "https://download.pytorch.org/whl/cu116",
"CUDA": "11.6",
"Pythons": [
"3.6",
"3.7",
"3.8",
"3.9",
"3.10",
"3.11"
]
}
```
However, Cog was looking for a strict match on CUDA 11.6.0.
This PR changes the check to …

Allow `MAJOR.MINOR` to match `MAJOR.MINOR.PATCH` with non-zero patch

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

Alternative to #1156
This PR downloads `tini` using `curl` in a separate build stage, and then copies it over. This avoids running `apt update` or relying on the existence of `curl`.

Download `tini` in separate stage

---

python/cog/types.py
python/tests/test_types.py

We have a bunch of issues with input filename handling. The most important is that we set no limits on filename length, which results in errors when the filename exceeds Linux's 255 byte limit.
This commit does the following:
- enforces a shorter 200-byte filename limit through truncation
- correctly decodes URL-encoded filenames
- protects against illegal characters in filenames (nul byte, slash)
In addition, it replaces a couple of ad-hoc data URI parsers with use of `urllib.request.urlopen`, which has supported data URIs since Python 3.4.

Fix input filename handling issues

---

CONTRIBUTING.md
go.mod
pkg/config/config.go

This PR resolves a TODO comment to make `ValidateAndComplete` return all errors generated when validating a config file instead of just the first. It relies on a [new language feature for wrapping multiple errors](https://go.dev/doc/go1.20#errors), so this PR depends on #1177

Accumulate errors in `ValidateAndComplete`

---

.gitattributes

Cog is about 50/50 split between Python and Go, both in fact and in principal. This PR adds an attribute to hide Makefile from the GitHub repo statistics to draw this out more clearly.

Exclude Makefile from GitHub repository statistics

---

python/cog/files.py

I deploy models with cog use: `docker run -d -p 5000:5000 my-model python -m cog.server.http --upload-url http://host:port/file`.
I found that when I used an asynchronous method to generate images and then uploaded to 'upload-url', the result was empt.
when I modified it using `fh.seek(0)`, I succeeded.

fix(python): put file to endpoint `file.seek(0)`

---

python/cog/json.py

It takes a little while to import numpy and it's not necessary for the server process to do up front. 
Signed-off-by: technillogue <technillogue@gmail.com>

don't import numpy at the top of json.py

---

.golangci.yaml

Follow up to ffd9edb2d8e1c699b406c8a480dac4fbc104c23d

Remove exception for 'compatability' in misspell configuration

---

.golangci.yaml
.vscode/settings.json
pkg/cli/build.go
pkg/cli/run.go
pkg/cli/train.go
pkg/docker/image_inspect.go
pkg/docker/login.go
pkg/docker/run.go
pkg/image/openapi_schema.go
pkg/predict/input.go
pkg/predict/predictor.go
tools/compatgen/internal/cuda.go
tools/compatgen/internal/torch.go
tools/compatgen/main.go

This PR updates the VSCode settings to automatically run `goimports` with local configured to sort `github.com/replicate/cog` imports separately from 3rd party imports.

Configure goimports local prefix

---

pkg/dockerfile/generator.go

In #1214 we accidentally left it so pyenv is installed when gpu: true even if  --use-cuda-base-image=false. This PR fixes that.

Small fix: don't install python when using python base image

---

pkg/image/build.go
pkg/image/openapi_schema.go
test-integration/test_integration/fixtures/invalid-int-project/cog.yaml
test-integration/test_integration/fixtures/invalid-int-project/predict.py
test-integration/test_integration/test_build.py

It's important that the OpenAPI schema generated by cog validates. This adds a validation step into the `cog build` process.
This should at least help us reduce the number of invalid schemas pushed to r8.im.

Validate model schema on build

---

.github/dependabot.yml

This PR updates `dependabot.yml` to add `gitHub-actions` to the list of package ecosystems for this project.
For more information, see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

Add GitHub Actions to Dependabot Version Updates configuration

---

pkg/image/build.go

The weights are changed if there is no cache (no previous value) or the value differs.
Introduced in #1223
On a tangential note -- if cog crashes around the `Equal` function, the `.dockerignore` is in an inconsistent state, which leads to weights being ignored (because it thinks the `.dockerignore` cog created is the real one, next time you run it) ... ideally there should be a finally block in the right place to restore the original `.dockerignore` if any, even if the code crashes.

Fix weight manifest change check

---

pkg/cli/predict.go
pkg/cli/run.go

This PR adds support for setting an environment variable when running a model (not during building)
This is meant to augment the development process of "cog train" - where fine-tuned models are different from the original model only by the presence of a `COG_WEIGHTS` variable.
Currently there is no easy way of using `cog predict` or `cog run` to test models during development with the results of fine-tuning.
After this PR lands, if you are doing development of a cog model such as llama or sdxl, you can test that the fine-tuned code-path works before pushing to replicate by doing:
cog predict -e COG_WEIGHTS=https://replicate.delivery/pbxt/xyz/weights.tar -i prompt="a photo of TOK"
or if you want to test that it works for multiple predictions (and doesn't leak memory), you can:
cog run -e …

support env vars for predict & run

---

CONTRIBUTING.md

`requirements-dev.txt` was removed in https://github.com/replicate/cog/pull/1201
This PR updates the contributing docs with a [new command](https://chat.openai.com/share/ce6d4db5-0da8-44c1-a344-5e11835a4667).
cc @nickstenning 
---

update pip install command in contributing guide

---

docs/deploy.md
docs/http.md
docs/training.md

We have some HTTP API reference docs about the OpenAPI schema, but it's not clear how to actually "run a Cog server". This PR addresses that with some docs about how to build the Cog image and run it with Docker.
cc @anotherjesse @mattt

document running a server to view OpenAPI schema

---

pkg/dockerfile/generator.go

this is like #1233. however, there's no way to configure anything to be installed in the pip install build stage. llama requires sentencepiece, which requires cmake to build from source. we don't want to put cmake in system_packages (and it wouldn't help anyway). so there's this envvar as a stopgap until we decide to have a build_system_packages setting or something

COG_EXPERIMENTAL_BUILD_STAGE_DEPS for dependencies required in the pip install stage

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

The pip install stage by default brings pip's dependencies: distutils, setuptools, wheel. Pyenv also brings these packages, so trying to symlink the ones from pip causes an error
```
=> CACHED [stage-1 5/7] COPY --from=deps --link /dep /dep                                                                                                                                                                   0.0s
=> ERROR [stage-1 6/7] RUN ln -s /dep/* $(pyenv prefix)/lib/python*/site-packages                                                                                                                                           0.5s
------
> [stage-1 6/7] RUN ln -s /dep/* $(pyenv prefix)/lib/python*/site-packages:
#0 0.388 ln: failed to create symbolic link …
```

add --force flag to ln

---

python/cog/predictor.py
python/tests/fixtures/argv_override.py
python/tests/test_predictor.py

In production, any sys.argv should not be exposed to user code. Partly because this might leak information about the production environment, but primarily because user code often has its own argument parsing code which gets confused when it sees our arguments to cog/server/http.py.
This uses mock.patch to ensure that sys.argv contains just sys.argv[0] when user code is executing.
Even though we (Cog) have already done all argument parsing long before this executes, we also put the original value back once we're done running user code.

Override `sys.argv` while importing predictor module

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

There's this error that can happen
```
=> ERROR [stage-1 6/7] RUN ln --force -s /dep/* $(pyenv prefix)/lib/python*/site-packages                                                                                 0.5s
------
> [stage-1 6/7] RUN ln --force -s /dep/* $(pyenv prefix)/lib/python*/site-packages:
0.390 ln: /root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/_distutils_hack: cannot overwrite directory
0.391 ln: /root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pkg_resources: cannot overwrite directory
0.392 ln: /root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/setuptools: cannot overwrite directory
0.392 ln: /root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/wheel: cannot overwrite directory
0.392 ln: …
```

fix an error with multistage symlinks

---

pkg/util/mime/mime.go

Currently, models do not support [Markdown files](https://en.wikipedia.org/wiki/Markdown). Instead, they must be converted to and from plain text (`text/plain` / `.txt`) files.
This PR adds a new entry to Cog's MIME / content type mapping for Markdown files (content type `text/markdown` with file extension `.md`) so they can be supported directly.

Add support for Markdown file inputs and outputs

---

python/cog/predictor.py
python/tests/server/fixtures/input_union_integer_or_list_of_integers.py
python/tests/server/fixtures/input_union_string_or_list_of_strings.py
python/tests/server/test_http_input.py

Alternative to ~#968~ https://github.com/replicate/cog/pull/1292
This PR extends Cog to support `List` and `Union` type inputs. 
For example, given the following predictor:
```python
from cog import BasePredictor, Path
from typing import List, Union
def predict(self, args: Union[int, List[int]]) -> int:
if isinstance(args, int):
return args
else:
return sum(args)
```
The following assertions are satisfied:
```python
resp = client.post("/predictions", json={"input": {"args": 123}})
assert resp.status_code == 200
assert resp.json()["output"] == 123
resp = client.post("/predictions", json={"input": {"args": [1, 2, 3]}})
assert resp.status_code == 200
assert resp.json()["output"] == 6
resp = client.post("/predictions", json={"input": {"args": "abc"}})
assert …
```

Allow `Union` and `List` input types

---

pkg/cli/build.go

Follow-up to #1229 
This PR corrects the usage description for `--dockerfile` option to reflect the actual behavior. I introduced this mistake with https://github.com/replicate/cog/pull/1229/commits/ffe657f652444215bd30ea9b666ea1818de2dba6.

Fix usage description for `--dockerfile` option

---

go.mod
pkg/cli/build.go

Follow-up to #1229
The `--dockerfile` flag is intended primarily for debugging, and shouldn't be advertised in command usage output. This PR marks the flag as hidden.
```console
$ cog build --help
Build an image from cog.yaml
Usage:
cog build [flags]
Flags:
-h, --help                         help for build
--no-cache                     Do not use cache when building the image
--openapi-schema string        Load OpenAPI schema from a file
--progress string              Set type of build progress output, 'auto' (default), 'tty' or 'plain' (default "auto")
--secret stringArray           Secrets to pass to the build environment in the form 'id=foo,src=/path/to/file'
--separate-weights             Separate model weights from code in image layers
-t, --tag string                   A name for …
```

Hide `--dockerfile` flag

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

this replaces symlinks with hard copies using a buildkit feature, RUN --mount=type=bind,from=stage. the readme tells people they need buildx, but we should maybe still verify that buildkit is actually available (#1322), or find a different solution (e.g. somehow force pyenv to use a knowable site-packages location, or copy packages directly into /src)
I noted other options for resolving minor versions here: https://github.com/replicate/cog/pull/1233/commits/94ce8f046328249a6073b68eca67e2f5bd58e343
https://docs.docker.com/engine/reference/builder/#run---mounttypebind
---
this is the relevant part of the previous dockerfile
```Dockerfile
FROM python:3.11 as deps
COPY .cog/tmp/build2042880849/cog-0.0.1.dev-py3-none-any.whl /tmp/cog-0.0.1.dev-py3-none-any.whl
RUN …
```

fix updating pip in multistage cuda images

---

pkg/util/mime/mime.go
pkg/util/mime/mime_test.go

This PR adds MIME type definitions some 3D assets.
| Content type | File extension |
|-|-|
| `model/gltf-binary` | `.glb` |
| `model/mtl` |         `.mtl` |
| `model/obj` |          `.obj`|

Add support for `.glb`, `.mtl` and `.obj` files

---

python/cog/command/ast_openapi_schema.py
python/cog/predictor.py
python/cog/server/worker.py
python/tests/server/fixtures/async_hello.py
python/tests/server/fixtures/async_yield.py
python/tests/server/test_http.py
python/tests/server/test_worker.py

this is the first step towards supporting continuous batching and concurrent predictions. eventually, you will be configure it so your predict function will be called concurrently. this will work with engines that implement batching internally like vLLM and TRT, and allow users to implement things like microbatching on their own. it may also be possible to have truly concurrent predictions without batching at all by using cuda streams.

support async predict functions 

---

python/cog/server/http.py

this doesn't change any logic, but as far as I understand sync routes use threads instead of the starlette event loop: https://fastapi.tiangolo.com/async/#path-operation-functions

make HTTP routes async

---

python/cog/server/runner.py
python/cog/server/webhook.py

This is a bit of a hack, but it should help us get output sooner from models that are latency-sensitive and return their first output very shortly after prediction start.
If COG_THROTTLE_RESPONSE_INTERVAL is set to a value below 0.1 (i.e. <100ms), don't sent the initial "start" webhook. This should mean that the first output webhook will be sent as soon as it is received. Without this, there is a risk that it will be throttled by the ResponseThrottler.

Get faster initial output from latency-sensitive models

---

docs/environment.md
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

https://github.com/NVIDIA/nvidia-container-runtime/issues/112
I'm interested in capabilities beyond the default Nvidia base images of just compute and utility. I'm particularly interested in using the video encoding and decoding functionality and OpenGL in an X11 application.

Add ENV NVIDIA_DRIVER_CAPABILITIES=all to permit Video SDK transcoding, 3D rendering, and X11 OpenGL Display

---

Makefile

My `bash` doesn't live in `/bin`, so the Makefile doesn't work for me. However, `bash` is in the `PATH`, so look it up from there.

Makefile: don't hardcode bash path and use the one from PATH instead

---

pkg/cli/predict.go

We observed papercuts during cog usage, and forgetting `-i` was quite an annoying one. Test for this and show a specific warning.

cog predict: specific hint if image name contains '='

---

pyproject.toml
python/cog/server/http.py
python/cog/server/runner.py
python/cog/server/worker.py
python/tests/server/test_http.py
python/tests/server/test_runner.py

stacked PR on top of #1350 as well as #1355, this similarly only takes steps to eventually allow concurrent predictions. this PR starts with changing multiprocessing.pool.AsyncResult to asyncio.Task, and propagates the necessary async changes
- have runner return asyncio.Task instead of AsyncFuture
- making tests async

async runner

---

.github/workflows/ci.yaml
Makefile
pyproject.toml
python/cog/command/ast_openapi_schema.py
python/cog/files.py
python/cog/json.py
python/cog/predictor.py
python/cog/schema.py
python/cog/server/http.py
python/cog/server/response_throttler.py
python/cog/server/runner.py
python/cog/server/webhook.py
python/cog/server/worker.py
python/cog/types.py
python/tests/server/test_runner.py

I fell into a typing hole while setting up pyright-lsp. Nevertheless, I think these are good changes, mostly preventing some annoying crashes (ast_openapi_scha + bytes defaults, cpus being uncountable).
Fixes  #1360

Fix types, run typechecker in CI

---

pkg/cli/push.go

It's nice that Cog can push to any Docker registry, so it makes sense that this could be "any URL", but most users will be pushing to Replicate's model registry. This change updates the usage to give more of a hint of what kind of URL they should be constructing.

use a more realistic registry URL in cog push usage

---

python/cog/command/ast_openapi_schema.py
python/cog/predictor.py
python/cog/server/http.py
python/cog/server/runner.py
python/cog/server/webhook.py
python/cog/server/worker.py
python/cog/types.py
python/tests/server/fixtures/async_hello.py
python/tests/server/fixtures/async_setup_uses_same_loop_as_predict.py
python/tests/server/fixtures/async_yield.py
python/tests/server/fixtures/setup_uses_async.py
python/tests/server/test_http.py
python/tests/server/test_runner.py
python/tests/server/test_worker.py

The current implementation (prior to #1350)  throws an error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/cog/server/worker.py", line 226, in _predict
for r in result:
...
File "/src/src/download.py", line 118, in sync_download_file
return self.loop.run_until_complete(self.download_file(url))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 629, in run_until_complete
self._check_running()
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 590, in _check_running
raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
```
The problem is that llama's [setup()](https://github.com/replicate/cog-llama-template/blob/main/predict.py#L35) creates …

create event loop before predictor setup

---

pyproject.toml
python/cog/server/http.py

Yeah, overriding `State` like that wasn't legal to do, so it's right to complain. However, it's really nice so I'll keep doing it. Long term there should maybe be a type variable to `FastAPI`?
https://github.com/microsoft/pyright/issues/5933

Fix FastAPI state hack, freeze pyright version

---

test-integration/test_integration/conftest.py
test-integration/test_integration/test_build.py
test-integration/test_integration/test_predict.py

Ensures that images that we expect to clean up are cleaned up correctly. With check=True in the call to `docker rmi ...` we will raise if the call fails, and the exception will include the command output.

Stricter image cleanup

---

test-integration/test_integration/conftest.py
test-integration/test_integration/test_predict.py
test-integration/test_integration/util.py

- fixes the case when "make test-integration" fails intermittently in test cleanup that removes image
- added def remove_docker_image(image_name, max_attempts=5, wait_seconds=1):

fix(test): 'docker' 'rmi' failed in python integration tests

---

python/cog/server/http.py

`os.sched_getaffinity` is not available on all platforms. Fall back to the original `os.cpu_count` if needed.

Set a reasonable default parallelism on non-Linux platforms

---

python/cog/server/http.py
python/tests/server/test_http_input.py

- handle early exceptions during model container setup
- catch exceptions during creation of Pydantic validators
- propagate error message to health checks w/o creation of predictor
Ref: https://github.com/replicate/infra/issues/21

fix: handle early exceptions in model setup

---

docs/python.md

It seems there's some [confusion with custom return objects](https://github.com/replicate/cog/issues/1275). This PR intends to avoid this confusion by adding a not in the docs.

Add note for naming `Output` class

---

docs/yaml.md

This PR adds some documention for people who are using git-based Python dependencies. This used to work, but we switched to using a slimmer image that doesn't include git in https://github.com/replicate/cog/pull/1214
Resolves https://github.com/replicate/cog/issues/1381

document how to install git-hosted python packages

---

README.md

This PR adds a section to the README with instructions about how to upgrade from an older version of Cog to the newest version.

add upgrade instructions to README

---

.goreleaser.yaml

This is a partial fix for https://github.com/replicate/cog/issues/1465
This PR updates the Goreleaser config to capitalize OS names like `Darwin` and `Linux` so they match the output of `uname -s`, which we've long used for the [installation instructions in the README](https://github.com/replicate/cog?tab=readme-ov-file#install).
@caarlos0 does this look right? I did a dry run locally and I see this:
```
$ goreleaser release --snapshot --skip=publish --clean              
...
• archives
• skip archiving                                 binary=cog name=cog_Darwin_arm64
• skip archiving                                 binary=cog name=cog_Darwin_x86_64
• skip archiving                                 binary=cog name=cog_Linux_x86_64
• skip archiving                                 binary=cog …
```

Capitalize OS name in release artifacts

---

pyproject.toml
python/cog/command/ast_openapi_schema.py
python/cog/predictor.py
python/cog/server/http.py
python/cog/server/runner.py
python/cog/server/webhook.py
python/cog/server/worker.py
python/cog/types.py
python/tests/server/fixtures/async_hello.py
python/tests/server/fixtures/async_yield.py
python/tests/server/test_http.py
python/tests/server/test_http_input.py
python/tests/server/test_runner.py
python/tests/server/test_worker.py

Revert "add test cases for shared loop across setup and predict + asyncio.run in setup"
Revert "don't use async for predict loop if predict is not async"
Revert "conditionally create the event loop if predictor is async, and add a path for hypothetical async setup"
Revert "Revert "Revert "support async predict functions  (#1350)" (#1373)""
This reverts commit 8b8bbac9989a04bb7d3e1843d2a998b647cb7b02.
This reverts commit 0ca552108fd549e63b0a9ad6dfdb8b1a328a4259.
This reverts commit dcf5ac4656f4f93173b5c85b4cfbcdb544e8a8a7.
This reverts commit 47f3fa590145ef103ec46a95c054303df2d7c7a9.
Revert "review changes to tests and server"
Revert "delete remaining runner thread code :)"
Revert "make tests async and fix them"
Revert "have runner return asyncio.Task instead of AsyncFuture"
This reverts …

Revert batching changes

---

python/cog/command/openapi_schema.py
python/cog/server/http.py
test-integration/test_integration/conftest.py
test-integration/test_integration/test_build.py
test-integration/test_integration/util.py

- added handling of early setup exceptions on "train" path in cog predict/build
- skip calling setup() on early setup errors, and optionally initiate shutdown in interactive mode 
- added check for setup() errors in cog build (in openapi_schema.py)
Testing:
- use simple model with predict & train
- change input type in train to a bad type
- run cog predict or build
Expected:
- cog prints bad input type error
Ref:  https://github.com/replicate/infra/issues/25

fix: add handling of early setup exceptions on "train" path in cog predict/build

---

python/cog/command/openapi_schema.py
python/cog/server/http.py

- ignore "train" part of schema errors during predict runs for backward compatibility with existing "bad" models already in use
- expected: cog shall not trigger exception/error  when "train" is present in config but "train.py" is missing.

fix: ignore "train" part of schema errors during predict runs

---

.github/workflows/ci.yaml

16-cores costs $0.064/minute. 8-cores costs $0.032/minute. The default 2-cores costs $0.008/minute.

Use cheaper runner for CI

---

docs/python.md

Addresses #1426 
Recommends downloading weights in `setup` using `pget` or using the `--separate-weights` flag otherwise.

Document how to download/store weights

---

docs/yaml.md

Removed a redundant backtick that was causing the `python requirements` section to be displayed as a code excerpt.
@allcontributors please add @JacekDuszenko for doc

Fix a formatting typo in yaml.md

---

python/cog/server/eventtypes.py
python/cog/server/helpers.py
python/cog/server/worker.py
python/tests/server/test_worker.py

A critical part of concurrent predictions is multiplexing several prediction outputs over the same pipe. This takes a stab at that. Once this is done, we might be able to drop some parts of runner.
We tag each _PublicEventType with a prediction id, introduce a `Mux`, and have a `_read_events` task responsible for reading events from the pipe and writing them to the mux. The mux adds it to the right queue, and then the places that previously called `_wait` instead call `Mux.read`. 
We also add a semaphore and keep track of predictions in flight. READY is renamed to IDLE, but that may need to be reworked further. 
---
Some challenges
* contextvar to tag logs that were emitted from inside a predict() 
* however, logs emitted from cross-prediction stuff (like the actual batching code) have to …

Mux prediction events

---

Makefile
pkg/docker/build.go
pkg/image/build.go
pyproject.toml
python/cog/files.py
python/cog/schema.py
python/cog/server/http.py

- store openapi schema file json & py files in .cog subdir during cog build;
- conditionally create Input & Output schema types from openapi schema file;
- conditionally create TrainingInput & TrainingOutput schema types from openapi schema file;
Migration:
- optimization will work for new  models, old models are unaffected
Ref: https://github.com/replicate/infra/issues/23

feat: eliminate redundant loads of predict.py and train.py in early setup of cog predict

---

.vscode/extensions.json
.vscode/settings.json

Prompted by getting a `All settings starting with "python.linting." are deprecated and can be removed from settings.` warning at startup. This PR resolves the handful of other issues discovered along the way.

Update VSCode workspace settings

---

.github/workflows/ci.yaml
Makefile
docs/yaml.md
test-integration/test_integration/fixtures/python_37/cog.yaml
test-integration/test_integration/fixtures/python_37/predict.py
test-integration/test_integration/test_build.py

- do not allow python 3.7 in models
- added python 3.12 to CI verification
- added test:  test_integration/test_build.py::test_python_37_depricated
Ref: issue #1431

feat: deprecate python 3.7

---

pkg/image/build.go
test-integration/test_integration/test_build.py

We have been warning that these are deprecated for a long, long time
now, and we probably have the liberty to make breaking changes <1.0.
Signed-off-by: Ben Firshman <ben@firshman.com>

Remove deprecated labels

---

docs/python.md

The bulleted list doesn't render well at the moment:
Adding enters before the blocks to ƒix that!

Better formatting for `pget` instructions in `setup()` docs for Python

---

pkg/cli/init-templates/cog.yaml
pkg/cli/init-templates/predict.py

use shorter cog.run URLs in `cog init` templates

---

python/cog/predictor.py

the behavior of cog.Path and cog.File as setup weights argument is inconsistent with how it works in predict. allowing str is a way out until that's fixed properly

allow setup(self, weights: str)

---

pkg/config/torch_compatibility_matrix.json

I ran the compatgen tool with `go run tools/compatgen/main.go torch`, and used the output to update the compatibility matrix for torch.
- adds support for Torch 2.2.*
- removes Python 3.6 from compatibilities matrix
Judging from [this merged PR](https://github.com/replicate/cog/pull/1550), should we maybe also remove mentions of Python 3.7 and add Python 3.12?

update compatibility matrices: support torch 2.2

---

.github/workflows/ci.yaml
pkg/cli/build.go
pkg/config/config.go
pkg/config/config_test.go
python/tests/server/test_worker.py
test-integration/test_integration/test_build.py

- previous deprecation of Ptyhon 3.7 in models did not have actual check (https://github.com/replicate/cog/pull/1550)
- now the model python minimum version is checked in `cog build` only
- this new approach is compatible with existing already built and/or uploaded models
- fixed integration test
- keep running CI tests on python 3.7

feat: deprecate python 3.7 #2

---

.github/workflows/build-bases.yaml

In support of new cog-bases work this workflow will build the base images. The workflow is limited to work on the WIP branch `cog-base-images` and does not push to the registry.
Once the `cog-base-images` work is merged to main this workflow will be updated.
Additionally, this is intended to be exclusively a manual dispatch.

Implement base-building workflow

---

python/tests/server/test_worker.py

this PR attempts to debug why hypothesis tests are flaking

Increase timeout of flakey test to 1.5s

---

tools/compatgen/main.go

Make the help message of compatgen clearer by explicitly stating the valid options for <target>.

Include options for compatgen targets in Usage help

---

python/cog/__init__.py
python/cog/predictor.py
python/cog/types.py
python/tests/server/fixtures/input_secret.py
python/tests/server/test_http_input.py
python/tests/test_types.py
test-integration/test_integration/util.py

This PR defines a new `Secret` type in Cog's Python package, which model authors can use to signify that an input holds sensitive information (like a password or API token).
The `Secret` type inherits from [Pydantic's `SecretStr`](https://docs.pydantic.dev/1.10/usage/types/#secret-types):
> You can use the `SecretStr` and the `SecretBytes` data types for storing sensitive information that you do not want to be visible in logging or tracebacks. `SecretStr` and `SecretBytes` can be initialized idempotently or by using `str` or `bytes` literals respectively. The `SecretStr` and `SecretBytes` will be formatted as either `'**********'` or `''` on conversion to json. 
```python
from cog import BasePredictor, Secret
def predict(self, secret: Secret) -> None: …
```

Define `Secret` type

---

pkg/docker/build.go

Related to https://github.com/replicate/cog/issues/1620
Some customers have observed the [`replicate/setup-cog` action](https://github.com/replicate/setup-cog) failing to push new versions of images to Replicate.
In logs for such failing GitHub Actions runs, the following is printed:
> No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
We currently _do_ pass `--load`, but only when building on macOS:
https://github.com/replicate/cog/blob/03216b69e2f0aa2b93fe42e00f752fae5b576a78/pkg/docker/build.go#L25
I believe this code was leftover from when `cog build` didn't always imply `docker buildx build`, and BuildKit was used only when building `linux/amd64` on …

Always pass `--load` flag to `docker buildx build` command

---

pkg/cli/init.go

The correct link on cog.run is https://cog.run/getting-started/
Alternatively we could add a redirect to cog.run/docs/getting-started to redirect back.

Fix Getting Started Link returns 404

---

python/cog/server/connection.py
python/cog/server/helpers.py
python/cog/server/runner.py
python/cog/server/worker.py
python/tests/server/test_connection.py
python/tests/server/test_webhook.py

Yet Another Step towards merging #1530 into #1512. this drops that stupid `race()` function and the threaded mp.Connection setup, because those were found to be somewhat slow when profiling and it's generally simpler and less deadlock-prone to do it this way. we instead just implement most of the same stuff as mp.Connection, including a test that it matches the same binary format implemented by mp.Connection

implement mp.Connection with async streams

---

pkg/docker/build.go
pkg/image/build.go

Related to #1635 and #1631
PR #1621 attempts to address this issue, but passing the ```--load``` parameter in each build only partially solves the problem.

fix: 🐛 Failed to Load Docker Image Metadata in Github Action

---

pkg/config/cuda_base_images.json
pkg/config/tf_compatibility_matrix.json
pkg/config/torch_compatibility_matrix.json

Release Notes:
- https://docs.nvidia.com/cuda/archive/12.3.2/
- https://github.com/pytorch/pytorch/releases/tag/v2.3.0
- https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1

Update CUDA compatibility matrix for CUDA 12.3 / PyTorch 2.3.0

---

docs/yaml.md

This PR adds some docs about how to pin to a specific git commit when installing Python packages directly from a GitHub repo.
cc @fofr @lucataco

document pinning python package installations to commit SHAs

---

python/cog/schema.py
python/cog/server/runner.py

it might be helpful to account for the cost of individual predictions in a batch, including the changes in batch size over the course of the prediction. this would add a metric representing that. it can also be used to determine the average batch size (`batch_size = predict_time / time_share`).
if there are two predictions that take 1 second, they would both cost 0.5s. if there's one prediction that takes 3 seconds and another one that takes 1 second (overlapping with the first prediction), the first will cost 2.5 (1 + 1/2 + 1) seconds and the second will cost 0.5 (1/2) seconds.
```
AAA***
*BBBB*
**CC**
***DDD
```
job A is running for the first 3 seconds, job B is running from second 2 to 5, job C runs seconds 3–4, job D runs seconds 4–6. suppose each second costs $1. A costs $1 + $.5 + …

time_share metric

---

docs/metrics.md
python/cog/__init__.py
python/cog/server/eventtypes.py
python/cog/server/runner.py
python/cog/server/worker.py
python/tests/server/test_runner.py

we need the model code to emit accurate input token counts using the correct prompt formatting and tokenizer for the model in question. after some internal discussion `from cog import emit_metric` seems similar to the best approach for this. presently these metrics are ignored for non-official models and shouldn't really matter anywhere else, so it shouldn't be a concern with billing. this particular approach is janky but should unblock us for now. 
usage:
```python
async def predict(self, ...) -> ...:
...
formatted_prompt = prompt_template.format(prompt=prompt, system_prompt=system_prompt)
input_token_count = len(self.tokenizer(formatted_prompt )["input_ids"])
cog.emit_metric(name="input_token_count", value=input_token_count)
...
```

function to emit metrics

---

pkg/config/config.go
python/cog/server/http.py

we need users to be able to set target metric. after discussion in #1668, this seems like the simplest approach for now and could be reconsidered later.

allow setting both max and target concurrency in cog.yaml

---

python/cog/files.py
python/cog/server/runner.py
python/tests/cog/test_files.py

This PR introduces two small changes to the file upload interface.
1. We now allow downstream services to include the destination of the asset in a `Location` header, rather than assuming that it's the same as the final upload url (either the one passed via `--upload-url` or the result of a 307 redirect response.
2. We now include the `X-Prediction-Id` header in upload request, this allows the downstream client to potentially do configuration/routing based on the prediction ID. This ID should be considered unsafe and needs to be validated by the downstream service.

Include prediction id upload request

---

pkg/cli/init-templates/.github/workflows/push.yaml
pkg/cli/init.go

This PR adds a "Push to Replicate" GitHub Actions workflow file to the `cog init` template, so users will have a smoother path to continuous delivery.
The workflow is configured to start users off with a manual "repository dispatch" so pushes are explicit and intentional. It also has some commented-out settings to support a more continuous workflow once they've kicked the tires, plus some pointers for common issues like running out of disk space.
```
$ ~/go/bin/cog init     
Setting up the current directory for use with Cog...
✅ Created /Users/z/Desktop/cog-init-test/cog.yaml
✅ Created /Users/z/Desktop/cog-init-test/predict.py
✅ Created /Users/z/Desktop/cog-init-test/.dockerignore
✅ Created /Users/z/Desktop/cog-init-test/.github/workflows/push.yaml
Done! For next steps, check out the docs …
```

update `cog init` to include a GitHub Actions workflow file

---

docs/getting-started.md
docs/yaml.md

This PR clarifies that you can run `cog push r8.im/foo/bar` to override the `image` in cog.yaml.

document how cog.yaml `image` works with `cog push`

---

python/cog/server/runner.py
python/cog/server/worker.py

#1643 adding a predict_time_share metric but it was only set on the prediction after the completed webhook was sent

predict_time_share needs to be set before sending the completed webhook

---

Makefile
pyproject.toml
python/cog/command/ast_openapi_schema.py
python/tests/cog/test_files.py
python/tests/server/test_code_xforms.py

The latest version of Ruff enabled new errors, causing regressions in our codebase. This PR fixes those errors and updates the `pyproject.toml` file to use the new `tool.ruff.lint` namespace.

Fix linter errors

---

pkg/dockerfile/generator.go
pyproject.toml

As of cog v0.9.7, setting the `--use-cuda-base-image=false` flag fails b/c we changed the logic below around copying python packages to the staging images. This fixes that logic for the case when we have that flag set and aren't using cog base images.

fixing install logic to reenable no cuda base image

---

python/tests/server/test_worker.py

Recently we have been hitting the timings deadline in the python integration tests.
I didn't investigate if the regression is expected or not.

Increase Hypothesis test deadlines

---

pkg/cli/run.go
pkg/docker/run.go

This commit fixes the `run` command for Apple Silicon M1 support. The `run` command now uses the `docker run` command with the `--platform` flag set to `linux/amd64` to ensure that the container runs on the correct architecture. This behavior matches the `build` command, which also uses the `--platform` flag to ensure that the image is built for the correct architecture.

Quick fix for Apple Silicon M1 support in `run`

---

python/cog/server/clients.py

Fixes an error that occurs when uploading the results of a training run.
```
File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/cog/server/clients.py", line 190, in upload_file
[log.info](http://log.info/)("doing test upload to", url)
File "/root/.pyenv/versions/3.11.9/lib/python3.11/site-packages/structlog/_native.py", line 136, in meth
return self._proxy_to_logger(name, event % args, **kw)
~~~~~~^~~~~~
TypeError: not all arguments converted during string formatting
```

Fix upload logging

---

pkg/cli/predict.go

Follow-up to #1253 
This PR fixes a bug where environment variables wouldn't be set on the second attempt to run `cog predict` when no GPUs are available (such as on macOS).

Set missing `Env` argument in call to `NewPredictor` on retry

---

pkg/cli/train.go

Follow-up to #1253
While I was working on #1709, I noticed that we don't support passing environment variables to `cog train`. This PR makes that change.

Add `--env`/`-e` flags to cog train subcommand

---

python/cog/code_xforms.py
python/cog/predictor.py
python/cog/server/http.py
python/cog/server/runner.py
python/cog/server/telemetry.py
python/cog/server/useragent.py
python/cog/server/webhook.py
python/tests/server/test_http.py
test-integration/test_integration/test_predict.py

If the request to /predict contains headers `traceparent` and `tracestate` defined by w3c Trace Context[^1] then these headers are forwarded on to the webhook and upload calls.
This allows observability systems to link requests passing through cog.
[^1]: https://www.w3.org/TR/trace-context/

Propagate trace context to webhook and upload requests

---

python/cog/server/clients.py

tweak https://github.com/replicate/cog/commit/6996db to fix T4/A100-40

fix upload redirect handling

---

docs/yaml.md
pkg/config/compatibility.go
pkg/config/config.go
pkg/config/config_test.go

When the user specifies a CUDA or Python version in the cog.yaml, we now ensure that at least the minor version is set. This validation ensures that our compatibility version logic works properly.
Additionally, this commit adds logic to the CUDA version selection process, enabling it to pick the latest versions of both CUDA and Ubuntu that satisfy the major.minor constraints.
It also fixes a bug in the config parsing that caused a panic if the user defined only the major version of Python.

Validate minor version for CUDA and Python

---

docs/yaml.md
pkg/config/config.go
pkg/dockerfile/generator_test.go

Python 3.8 was released back in 2019 and recent versions of PyTorch and TensorFlow all support Python 3.12.
The change here update Cog to use Python 3.12 if a version is not specified. 
It doesn't modify cog internal version resolution for PyTorch and Tensorflow as Cog will select the latest
Python version based the compatibility matrix.

Update default python version to 3.12

---

pkg/cli/build.go
pkg/cli/run.go
pkg/config/config.go
pkg/config/config_test.go
pkg/dockerfile/base.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

In preparation for making `--use-cog-base-image` flag the default behavior, we are adding better
handling for invalid configuration.
* Check that the combination of cuda, python and pytorch is valid before attempting to run/build the image
* Check that we are not missing flags that don't work together

Improve cog base image handling

---

python/cog/server/worker.py

when an error happens, we log the traceback. this goes through the normal logging mechanism, which drops the log if there's more than one prediction. we can use `_log(traceback.format_exc())` instead. also fix some minor formatting things.

log traceback properly

---

pkg/cli/build.go

Unhide the flags that control if we should use base images by default.
That should allow more testing of the functionality before we make it the default behavior.
Moved out from https://github.com/replicate/cog/pull/1699

Unhide the use-cog-base-image-flag

---

.github/workflows/ci.yaml

Reverts replicate/cog#1731
Inadvertently merged this before migrating incompatible changes.

Revert "Bump goreleaser/goreleaser-action from 4 to 6"

---

python/cog/server/runner.py

seemingly director or some other part of the system introduces enough change to predict_time as recorded in web that predict_time/predict_time_share gives implausible values for batch size. recording batch_size *should* be redundant given predict_time_share, but everything will probably be simpler to just record it explicitly.

add batch size metric

---

docs/deploy.md

The example curl to `/predict` does not include the necessary headers shown in [https://github.com/replicate/cog/blob/main/docs/http.md#post-predictions-synchronous](https://github.com/replicate/cog/blob/main/docs/http.md#post-predictions-synchronous)

add necessary headers to curl

---

README.md

Example in README failed to build because torch `1.8.1+cu111` doesn't exist any more?
```
> [deps 5/5] RUN --mount=type=cache,target=/root/.cache/pip pip install -t /dep -r /tmp/requirements.txt:
0.494 Looking in links: https://download.pytorch.org/whl/torch_stable.html
4.031 ERROR: Could not find a version that satisfies the requirement torch==1.8.1+cu111 (from versions: 1.13.0, 1.13.0+cpu, 1.13.0+cu116, 1.13.0+cu117, 1.13.0+cu117.with.pypi.cudnn, 1.13.1, 1.13.1+cpu, 1.13.1+cu116, 1.13.1+cu117, 1.13.1+cu117.with.pypi.cudnn, 2.0.0, 2.0.0+cpu, 2.0.0+cpu.cxx11.abi, 2.0.0+cu117, 2.0.0+cu117.with.pypi.cudnn, 2.0.0+cu118, 2.0.1, 2.0.1+cpu, 2.0.1+cpu.cxx11.abi, 2.0.1+cu117, 2.0.1+cu117.with.pypi.cudnn, 2.0.1+cu118, 2.0.1+rocm5.3, 2.0.1+rocm5.4.2, 2.1.0, 2.1.0+cpu, 2.1.0+cpu.cxx11.abi, …
```

Bump to latest supported python & torch in README.md

---

README.md
tools/install.sh

Follow up to #1558 
Trying this out myself, I noticed that it wasn't being run interactively. To make that work, you need to redirect the source directly into a `sh` process. Piped execution doesn't support interactivity.
```console
$ curl -fsSL https://cog.run/install.sh | sh
On OS X, it is recommended to install cog using Homebrew instead:
`brew install cog`
Do you want to continue with this installation anyway?
```
This PR updates to use process substitution syntax. As discussed in https://github.com/fish-shell/fish-shell/issues/5181, fish (my preferred shell) uses a different syntax, so I added special instructions for that. I also removed instructions for `fetch`, because I think `wget` and `curl` cover the vast majority of use cases.

Update install script instructions

---

pkg/cli/push.go
pkg/docker/manifest_inspect.go

- Added the `ManifestInspect` function in `pkg/docker` to verify if a Docker image exists on a registry using the `docker manifest inspect` command.
- Updated the `push` function in `pkg/cli/push.go` to include a check for the existence of a model on the Replicate registry before initiating the build process.
- The validation step is conditionally executed only for images with the Replicate registry prefix, preventing unnecessary checks for other registries.
- This change ensures that if a model does not exist on Replicate, the process stops early with a clear error message, avoiding the waste of time and resources on building and attempting to push a non-existent model.
References:
- Issue #1678

Implement pre-build repository check for Replicate images

---

.github/workflows/ci.yaml

Cog's CI workflow consists of unit tests for Go, unit tests for Python, and integration tests. When Go unit tests fail, CI continues to run Python and integration tests, leading to wasted effort.
This PR sets up job dependencies to reduce wasted effort. First, it tests Go unit tests, since those run faster and only target 2 platforms. Once that finishes, it runs Python unit tests across our supported Python versions. And then, only when all of that finishes does it run integration tests.
This PR also removes Python 3.7 from the build matrix, as support for that was dropped in #1582.

Reduce unnecessary work in CI workflow

---

python/cog/server/http.py

Resolves #1735 
By default `http.server` binds to `0.0.0.0`. To support IPv6, you can specify `--host="::"`.
Defaulting to `::` breaks integration tests, as it requires Docker to enable IPv6 support. Making the host configurable seems like a better solution.

Update HTTP server to make host configurable

---

python/cog/predictor.py
python/cog/types.py

Resolves #1736
This PR updates the `cleanup` method in `BaseInput` to specify `missing_ok=True` when unlinking `URLPath` values. 
This PR also follows a suggestion in a code comment to use the native `missing_ok` parameter of `pathlib.Path.unlink`, which was added in Python 3.8 (and which, as of #1582 is the minimum supported Python version.

Allow `URLPath` files to be missing when cleaning up inputs

---

Makefile
pkg/docker/build.go
pkg/image/build.go

Related to #1635
PR #1638 solved this issue by ```load``` the image, but this solution took too long. 
```
2024-05-03T15:46:10.8805623Z #22 [stage-1 10/10] COPY . /src
2024-05-03T15:48:13.0347903Z #22 DONE 122.3s
2024-05-03T15:48:13.1585476Z 
2024-05-03T15:48:13.1587553Z #23 exporting to docker image format
2024-05-03T15:48:13.1588225Z #23 exporting layers
2024-05-03T15:56:24.3242181Z #23 exporting layers 491.2s done
2024-05-03T15:56:24.4767343Z #23 preparing layers for inline cache
2024-05-03T15:56:24.4943072Z #23 preparing layers for inline cache 0.2s done
2024-05-03T15:56:24.6204175Z #23 exporting manifest sha256:7b10fa087624266b84eb57facf450e2dc767b009b56436bd3c028779a4cc67f6 0.1s done
2024-05-03T15:56:24.6206394Z #23 exporting config …
```

fix: 🐛 a better fix for #1635

---

pkg/docker/run.go

Followup on https://github.com/replicate/cog/issues/1293#issuecomment-1952954820

Make cog local runner match /tmp/shm size on Replicate

---

.github/workflows/ci.yaml

Thanks to speedups in #1767, the slowdown from waiting for pending jobs to schedule a runner is now greater than the potential savings of not running integration tests.
This PR partially reverts #1760.

Restructure CI workflow (again)

---

pkg/config/config_test.go

Related to #710
#1023 created a failing test case where Cog dropped TensorFlow from requirements when specified in combination with PyTorch. This PR provides a passing test case to show a combination of package versions that does work.
The underlying issue of #710 is that this fails silently, and this PR doesn't address that. I just wanted to put this out there in case this unblocks anyone in this situation.

Add passing test that includes Torch and TensorFlow together

---

python/cog/server/worker.py
python/tests/server/fixtures/stream_redirector_race_condition.py
python/tests/server/test_worker.py

Alternative to #1758
Resolves https://github.com/replicate/cog/issues/982 Resolves https://github.com/replicate/cog/issues/1308 Resolves https://github.com/replicate/cog/issues/1446

Fix possible data corruption due to race condition in StreamRedirector

---

pkg/cli/baseimage.go
pkg/dockerfile/base.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

Follow-up to #1769 
This PR does the following:
* Adds (previously failing) test coverage for `cog.yaml` files with various minor and patch versions of Torch
* Updates logic for matching base images to pass aforementioned test case
* Strips patch from configured versions when generating `FROM` base image name
Now, when I run `cog build --use-cog-base-image` with either of the following configurations:
**With patch versions**
```yaml
build:
gpu: true
cuda: "12.1"
python_version: "3.11.7"
python_packages:
- "torch==2.3.0"
predict: "predict.py:Predictor"
```
**Without patch versions**
```yaml
build:
gpu: true
cuda: "12.1"
python_version: "3.11"
python_packages:
- "torch==2.3"
predict: "predict.py:Predictor"
```
...both attempt to pull `FROM r8.im/cog-base:cuda12.1-python3.11-torch2.3` [^1] …

Fix `cog build --use-cog-base-image` with minor and patch versions of Python and Torch

---

docs/deploy.md
docs/http.md

I started documenting the HTTP server host parameter added by #1748, but one thing led to another, and I ended up rewriting the [HTTP API docs](https://github.com/replicate/cog/blob/main/docs/http.md).
At a high level, this PR reorganizes the document by extracting discussion of topics like sync/async, idempotency, and webhooks out of individual endpoints and into top-level sections. I also added missing discussion of how file uploads work, and removed information about running the HTTP server which were duplicated in the [deployment](https://github.com/replicate/cog/blob/main/docs/deploy.md) doc.

Rewrite HTTP API documentation

---

python/cog/predictor.py
test-integration/test_integration/fixtures/future-annotations-project/cog.yaml
test-integration/test_integration/fixtures/future-annotations-project/predict.py
test-integration/test_integration/test_predict.py

Resolves #600 
This PR starts with a failing test case, and then applies the changes from #601.

Handle predictors with deferred annotations

---

pkg/cli/login.go

This pull request changes `cog login` process by hiding the API key input from view ( using `term.ReadPassword` ) when the user pastes it into the terminal. Similar methods are used in for ex. `sudo` to prevent screen-sharing vulnerabilities.
Current behavior
```
This command will authenticate Docker with Replicate's 'r8.im' Docker registry. You will need a Replicate account.
Hit enter to get started. A browser will open with an authentication token that you need to paste here.
If it didn't open automatically, open this URL in a web browser:
https://replicate.com/auth/token
Once you've signed in, copy the authentication token from that web page, paste it here, then hit enter:
[API_KEY]
ⅹ User does not exist
```
Proposed behavior
```
This command will authenticate Docker with Replicate's …
```

Secure Prompt for API key

---

python/cog/server/clients.py
python/cog/server/http.py
python/cog/server/telemetry.py
python/tests/server/test_http.py

Based on the implementation in #1698.
If the request to /predict contains headers `traceparent` and `tracestate` defined by w3c Trace Context[^1] then these headers are forwarded on to the webhook and upload calls.
This allows observability systems to link requests passing through cog.
[^1]: https://www.w3.org/TR/trace-context/

[async] Propagate trace context to webhook and upload requests

---

python/cog/server/worker.py

we're currently holding the lock the whole time an iterator is running; it needs to be held separately for each send. instead of doing a bunch of indents, just factor out the locked send into a separate class
although the lock isn't actually shared between processes and the more lightweight threading.Lock could be used, that means it has to be created in run() rather than __init__

don't block logs during iterators by fixing the lock

---

python/cog/json.py
python/cog/server/response_throttler.py
python/cog/server/runner.py
python/cog/server/webhook.py
python/tests/server/test_response_throttler.py
python/tests/server/test_runner.py
python/tests/server/test_webhook.py

this addresses some bottlenecks in models that output tokens fast
- encode webhooks only after knowing they will be sent
- bail out of upload type checks early for strs

optimize webhook serialization

---

python/cog/predictor.py

Cherry-picked from #1379
`human_readable_type_name` currently fails for types like `None`, which don't have a `__module__` attribute. This PR adds a `hasattr` check and falling back on `str(t)` to prevent unintended exceptions.

Make human readable type name function more resilient

---

pkg/cli/predict.go

`cog train` failed after 30 minutes with "weights: is a directory".
I refactored `predictIndividualInputs` so it checks output file writability if the path is known.

cog predict: check output path writability before predict/train

---

pkg/cli/train.go

- Currently, `cog train` always writes to `weights`
- Currently, there's no way to use it with already existing images
- Some models have a `weights` directory
Together, this makes for a terrible experience. This PR adds a way to specify the output directory and use an existing image.

cog train: bring functionality on par with cog predict

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

Resolves #1663
Alternative to #1807 
https://github.com/replicate/cog/pull/1605 introduced a regression in how Dockerfiles are generated when `--separate-weights` is enabled. As described in #1663, without a preceding `FROM` command that creates an alias for `weights`, the `COPY --from=weights` steps fail.
This PR updates the logic to inject this missing `FROM` command before the final stage.

Fix `Dockerfile` generation regression when `--separate-weights` is enabled

---

python/cog/server/clients.py
python/cog/server/runner.py
python/tests/server/test_clients.py

Based on #1667
This PR introduces two small changes to the file upload interface.
1. We now allow downstream services to include the destination of the asset in a `Location` header, rather than assuming that it's the same as the final upload url (either the one passed via `--upload-url` or the result of a 307 redirect response.
2. We now include the `X-Prediction-Id` header in upload request, this allows the downstream client to potentially do configuration/routing based on the prediction ID. This ID should be considered unsafe and needs to be validated by the downstream service.

[async] Include prediction id upload request

---

python/cog/server/runner.py
python/cog/server/worker.py

unconditionally mark predictions as cancelled without waiting for cancellation to succeed
while I struggle with #1786, we see queue spikes because not responding to cancellation promptly causes the pod to get restarted. this is a dirty hack to pretend like cancellation works immediately. as soon as we fix the race condition (and possibly any issues with task.cancel() behaving differently from signal handlers), we can drop this.
this is implemented by pretending as though the right event was read from the pipe

patch cancel bug: immediately mark predictions as cancelled

---

python/cog/predictor.py

https://github.com/replicate/cog/blob/f7759a08ef89a39d06c287b0a279a2a6bb7e0ce8/python/cog/predictor.py#L395
```
python/cog/predictor.py:395:8 - warning: Condition will always evaluate to False since the types "type[BaseModel]" and "None" have no overlap (reportUnnecessaryComparison)
```

Fix Pyright `reportUnnecessaryComparison ` warning

---

.gitignore
README.md
tools/install.sh

* Fixes: https://github.com/replicate/cog/issues/1783
* Adds venv to gitignore (not strictly part of this issue but noticed it on my system)
* Add support for specifying the `INSTALL_DIR` via environment variable outside of the script to prevent a `read`
* Allow the user to specify `SUDO_CMD` via environment variable outside of the script incase they are operating on a docker that doesn't contain it
* Downgrades the docker run check to a warning, in docker this can't be running. I also feel this should be a runtime check rather than an install check.
* Updates the docs to add a docker install instruction.

Make install docker friendly

---

pyproject.toml
python/cog/code_xforms.py
python/cog/command/ast_openapi_schema.py
python/cog/files.py
python/cog/json.py
python/cog/predictor.py
python/cog/server/http.py
python/cog/server/probes.py
python/cog/server/runner.py
python/cog/server/telemetry.py
python/cog/server/useragent.py
python/cog/server/webhook.py
python/cog/server/worker.py
python/cog/suppress_output.py
python/cog/types.py

Ignoring warnings related to `TODO` and `FIXME` comments:
```
python -m pylint python/ --disable W0511
```
This is a lot, but I think it would help us to ratchet up code quality ahead of merging async.

Resolve or ignore Ruff and Pylint warnings

---

pkg/image/build.go
test-integration/test_integration/test_build.py

* Fixes https://github.com/replicate/cog/issues/1822
* Adds a test case and develops against it, this test case creates a cog build, gets the labels from the docker image, and compares them against the layer hashes.
* Issue was the previous code was fetching the manifest, then the layers from the manifest, and the digest from those layers, but this was the hash for the layer manifest rather than the layer itself.
* Change to fetch layers rather than the manifest.
* Use the `DiffID` of the layers which is the uncompressed hash, this corresponds to what is in the docker inspect for the layers.

Fix cog base layer hash

---

pkg/config/validator.go
pkg/config/validator_test.go

* Currently we only know what the expected type was from validation error messages.
* Make sure we print the field as well to let the user know exactly which field is having issues.
* Add a test to confirm this error message.
* Fixes: https://github.com/replicate/cog/issues/1826

Print field in the validator error

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

The release job of the CI run for the latest release [failed](https://github.com/replicate/cog/actions/runs/10180772831/attempts/1) when building and pushing the Python package to PyPI. For some reason [^1], the package got built as `0.9.15.dev0+g592f768.d20240731` instead of `0.9.14`, and PyPI rejected that value.
[^1]: Any theories?
Our current CI/CD makes it impossible to re-run the failed release step without deleting or invalidating the GitHub release artifacts built by goreleaser. For sake of integrity, re-tagging or modifying artifacts after the fact is not an option.
This PR extracts the release step into its own workflow. It takes advantage of the [`workflow_run`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#wo …

Extract release process into separate workflow

---

python/cog/server/http.py
python/cog/server/runner.py
python/tests/server/test_runner.py

this addresses the problem described in https://www.notion.so/replicate/Short-Term-Async-Fixes-9d11cfc15bb84878aedd9d8ddf31840d?pvs=4#8a86d46ada954ff5b509231224c24f2f
prior to https://github.com/replicate/cog/commit/974675f9#diff-136cc6506e8aaea24081862f89e1cb778251b7726180fe237c8aaf560ae7ec69R315-R338, runner.shutdown() would call worker.terminate(). as far as I understand, neither in that branch nor in main is worker.shutdown() ever called. in that commit, I split runner.shutdown into runner.shutdown and runner.terminate, but never made anything call terminate. because I also removed the `should_exit = True` line, the uvicorn server would never exit, so the shutdown handler would eventually notice this and kill the whole process, so we never noticed that terminate was never called. …

call terminate after the last prediction or after a timeout if shutting down

---

pkg/cli/init-templates/.dockerignore

Some models has nested model git repos with LFS which keeps copies of large files in `.git/lfs/objects` and leads to bloated image.

Ignore git files everywhere in .dockerignore

---

pyproject.toml

We're working with `concurrent.futures.Future` on another branch and older pyright appears to have trouble with Future's type variables:
error: Argument of type "(f: Future[Done]) -> None" cannot be assigned to parameter "fn" of type "(Future[_T@Future]) -> object" in function "add_done_callback"
Type "(f: Future[Done]) -> None" cannot be assigned to type "(Future[_T@Future]) -> object"
Parameter 1: type "Future[_T@Future]" cannot be assigned to type "Future[Done]"
"Future[_T@Future]" is incompatible with "Future[Done]"
Type parameter "_T@Future" is invariant, but "_T@Future" is
not the same as "Done" (reportGeneralTypeIssues)Vkk

Bump pyright to 1.1.375

---

python/cog/json.py

It seems that some versions of numpy don't appreciate being imported multiple times from multiple threads, and throw an exception:
RuntimeError: CPU dispatcher tracer already initlized
This is easy enough to work around by only attempting the import once.

Fix a multithreading bug related to numpy import

---

python/cog/schema.py
python/cog/server/http.py
python/cog/server/runner.py
python/tests/server/test_http.py
python/tests/server/test_http_input.py
python/tests/server/test_runner.py

This simplifies `PredictionRunner`, removing its worker thread and making it a wrapper around the worker which also manages the lifecycle of `PredictTask` and `SetupTask` objects.
`PredictTask` is essentially `PredictionEventHandler` but with the additional responsibilities of a) tracking the future representing the predict task running in the worker, and b) handling the individual event objects returned by worker.
`SetupTask` is the equivalent but for a setup.
We expect that this code will change significantly in the near future to allow the runner to keep track of multiple predictions at once.
This also changes the behaviour of cog in the event of a fatal prediction exception: if `await_explicit_shutdown` is set, then rather than triggering instant shutdown, we will poison the …

Simplify `PredictionRunner`

---

python/cog/server/runner.py
python/cog/server/worker.py
python/tests/server/test_http_input.py

PR #1865 introduced a regression: URLs for Path inputs were downloaded inside the request handler for `POST/PUT /predictions`.
This creates at least two problems:
1. It blocks the uvicorn thread, stopping us from serving healthchecks.
2. It makes the prediction create request take too long, even when `Prefer: respond-async` is specified.
Both of these issues cause unexpected failures in production.
This commit moves responsibility for fetching these files into Worker, and specifically into its background thread. This is probably not a long-term fix, as we want to make Worker (and ChildWorker) async eventually.
This also adds a test which fails on main and is fixed by this change.

Download Path inputs in background

---

python/cog/server/runner.py
python/tests/server/test_runner.py

We create the task before we call `Worker.predict`, and sometimes, in case of errors, we never actually start the prediction. We should only send the webhook when we actually start.

Only send the "start" webhook when we start tracking a prediction

---

.gitignore
pkg/cli/build.go
pkg/cli/debug.go
pkg/cli/predict.go
pkg/cli/push.go
pkg/cli/run.go
pkg/cli/train.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go
pkg/image/build.go
test-integration/test_integration/fixtures/torch-baseimage-project/cog.yaml
test-integration/test_integration/fixtures/torch-baseimage-project/openapi.json
test-integration/test_integration/fixtures/torch-baseimage-project/predict.py
test-integration/test_integration/test_build.py

* Add base-image to gitignore
* Use a boolean pointer for cog base image flag for a tri-state variable
* Handle not explicitly setting the cog base image and a failure to resolve the base image as a warning
* Add integration test for torch 1.13.0
* Solves problem 3 in: https://github.com/replicate/cog/issues/1862

Fallback to regular if cog base image can't be determined and flag is not explicitly set

---

.github/workflows/pypi-package.yaml

Unfortunately the `release` event associated with the release created by `goreleaser` in the CI workflow does not trigger workflow runs. This is because the release is created using the `$GITHUB_TOKEN`, which doesn't trigger workflows to eliminate the possibility of recursive workflow triggers. See:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
This changes the publishing workflow (which is separate so that PyPI trusted publishing can reference specifically this workflow, and not allow publishing from any CI workflow run) to trigger on tag push, just like the main CI workflow.
The drawback here is that this is not conditional on the tests running and passing. For now, this is probably ok, …

Publish on tag push rather than release

---

pyproject.toml
python/tests/server/test_worker.py

We don't want to rack up a huge GitHub actions bill if we introduce test hangs. No individual test should take longer than 10s, except possibly the Hypothesis state machine test for `Worker`.
This PR adds `pytest-timeout` and configures a global test timeout of 10s for the project.

Add `pytest-timeout` and configure a 10s test timeout

---

.coveragerc
.github/workflows/ci.yaml
.gitignore
Makefile
pyproject.toml
python/cog/json.py
python/cog/server/worker.py
python/tests/server/test_http_input.py
test-integration/Makefile
test-integration/README.md
tox.ini

Tox makes it much easier for us to ensure that we are testing exactly what we want -- our package, installed from a built wheel, with no hidden dependencies on external packages.
This commit rejigs the Python testing situation so that we run all our tests inside tox environments, including the integration tests.
This in turn allows us to drastically slim down the "dev" dependencies extra, as it only needs to provide the dependencies used to build cog, and tox itself. All the test dependencies move into the "tests" extra.
I've been meaning to do this for a while but it is immediately motivated by #1885, as using tox makes it a lot easier to switch to not using `uv` on Python 3.7.
Small other changes included here:
- consolidate coverage config into tox.ini
- make `python/tests` not a …

Use tox to run Python tests

---

pyproject.toml
python/cog/predictor.py
python/cog/server/runner.py
python/cog/types.py

We need to support running 3.7 models in Replicate's production environment for now.
This ensures that we run the tests against 3.7.

Add Python 3.7 back to supported versions

---

pkg/dockerfile/base.go
pkg/dockerfile/base_test.go

* We never want to useCogBaseImage when generating base images.
Currently if we execute `./base-images dockerfile --cuda 12.1.1 --torch 2.1.1 --python 3.11` we see the following:
```
#syntax=docker/dockerfile:1.4
FROM r8.im/cog-base:cuda12.1-python3.11-torch2.1
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked apt-get update -qq && apt-get install -qqy  && rm -rf /var/lib/apt/lists/*
```
This is due to the generator thinking cog base images is turned on. This is because I changed the configuration to default to true if the user didn't explicitly define whether they wanted to use cog base images. Here we fix it by explicitly saying we don't want to use cog base images, this then forces the generator to produce a full base image rather than a stub.

Set useCogBaseImage to false in base-image

---

pkg/config/cuda_base_images.json
pkg/config/torch_compatibility_matrix.json

* Adds torch 2.4.0 compatibility in the matrix
* Add CuDNN to CUDA 12.4.x compatibility
After this new version of torch is added we can build base images with it.

Add new base images for torch 2.4.0

---

pkg/config/compatibility.go
pkg/config/compatibility_test.go
pkg/dockerfile/base.go
pkg/dockerfile/base_test.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go
pkg/util/version/version.go
pkg/util/version/version_test.go

* Do not strip patch version from torch
* If the user specifies a torch version without a patch, resolve the highest patch version from our compatibility matrix
* Change the version struct to use a pointer for the patch version in order to handle cases where the pointer has not been supplied (and how that manifests when comparing versions)
* Standardise on StripModifier for the version rendering
* No longer generate a torch minor compatibility matrix, unnecessary now we explicitly define patch version compatibilities

Support torch patch base images

---

python/tests/server/conftest.py
python/tests/server/test_worker.py

A lot of the setup and teardown boilerplate for Worker tests was repeated between tests.
This commit eliminates that and ensures that each test is using the same process to set up and tear down the worker, by adding a `worker` fixture and allowing it to be parameterized indirectly.

Deduplicate worker tests

---

pkg/config/compatibility.go
pkg/config/config.go
pkg/config/config_test.go
pkg/dockerfile/base.go
pkg/dockerfile/base_test.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

* Exclude torchaudio from pip installs (like torchvision)
* Install torchvision and torchaudio in the base images

Add Torchvision and Torchaudio to base images

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

* Follow the pyenv guide for producing optimised python binaries for better performance.
https://github.com/pyenv/pyenv/blob/master/plugins/python-build/README.md#building-for-maximum-performance
If the user is not using a base image this adds some latency to the build, I am guessing this might be fine since not supported base images are rare

Generate optimized python binaries with pyenv

---

pkg/dockerfile/base.go

* We require zstd to do some decompression from the tarballs on the image.

Add zstd to base image packages

---

pkg/dockerfile/base.go

* Allow base images to use the find unix command
* This is required to use the python compileall command in conjunction with find

Add findutils to base image

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

* Use pyenv and realpath to tell us where pyenv stores the real python binary
* Link to this binary in root
* Once this is built into base images we can convert the CMD statements to use this python
* This prevents shims executing multiple bash processes before the main python process.

Add direct link to python in root

---

pkg/dockerfile/base.go
pkg/dockerfile/base_test.go

* Currently base images installs python3-opencv
* This installs apt python making us have 2 pythons in the base image
* Instead install opencv-dev libraries and pip install the opencv python package.

Install opencv without python in base images

---

test-integration/test_integration/test_build.py

* This string has escape sequences in it.
On a broader note I'm unsure why this is suddenly the case, it seems to have correlated with the release of new base images, but its unclear to me why it would add escape sequences as part of its stderr output.

Fix test build integration test

---

pkg/cli/baseimage.go

* Allow the user to specify specific python, cuda or torch versions in the base image binary.
* This allows an easy way to filter the matrix for CI jobs.

Allow filtering the generated matrix

---

tools/install.sh

The install script seems to suggest `/usr/local/bin` as the default install directory. However, pressing `RETURN` will actually set the install dir to an empty string. The error message is not helpful as it then reads `The directory  does not exist.` (note the additional space).
This fix makes the script behave as expected: pressing `RETURN` accepts the default suggestion.
(Also factors out the directory selection into a function.)

Clarify default install directory behaviour

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

* These do not play nicely with emulators when running across different architectures.
More context:
https://brad.net.nz/blog/2019/07/12/docker-cflags-marchnative-and-illegal-hardware-instruction/
https://stackoverflow.com/questions/54039176/mtune-and-march-when-compiling-in-a-docker-image

Remove -march native cflags

---

docs/deploy.md

Closes the code block so the rest of the docs are rendered properly in markdown.

fix code block in deploy.md

---

python/cog/server/http.py

Generating the OpenAPI schema was broken under the circumstances:
- train.py#train had an enum-type input
- cog was running with --x-mode=train
I've verified that this change fixes it.  The current code is obviously wrong in any case.

Fix openapi schema

---

Makefile

Our stuff doesn't work with 1.23 yet (#1950 is working on it); for now, pin to goreleaser 2.2.0 so we can still do releases.

Pin goreleaser to v2.2.0 to avoid pulling in go 1.23

---

pkg/cli/build.go
pkg/cli/push.go
pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go
pkg/image/build.go
test-integration/test_integration/test_build.py

* Add a —-precompile build flag that allows users to opt in to precompiling their python files so
they load faster.
* This uses the python `compileall` module to compile python files to bytecode
* It uses the invalidation mode of `timestamp` which we have told the python interpreter in its invocation to run

Add Precompile Build Flag

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

* Moves apt installs to just below the initial FROM line
* This prevents pip packages not installing due to depending on these apt packages
Fixes: https://github.com/replicate/cog/issues/1949

Install apt packages before pip packages

---

python/cog/predictor.py
test-integration/test_integration/fixtures/future-annotations-project/predict.py
test-integration/test_integration/test_predict.py

This reverts commit 05900a7e6d8270df8175b1f7788f0b566486855c.
This is needed to avoid breaking predictors that rely on __signature__ or partial.
I'm suggesting merging this ahead of #1895 to unblock certain language models that have been broken

Revert "Handle predictors with deferred annotations (#1772)"

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

* Allow cached directories, but on every pip install use a volume mount to make the cache
invisible to the running container

Add mount caches to pip installs

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

* This adds the cog install step to images using base images.
* This fulfils the contract of using the current version of cog within the image and not the
version of cog used by the base image.

Install cog when using base images

---

pkg/cli/login.go

If the token pasted for CLI login starts with `r8_`, reject it with an error message before we even start.
This also clears up some of the surrounding copy, which is pretty confusing and could easily have led to people thinking an API token was valid here.

Don't accept Replicate API tokens for CLI login

---

python/cog/errors.py
python/cog/server/errors.py
python/cog/server/helpers.py
python/cog/server/runner.py

to allow for separation of error tracking.
Connected to internal issue PLAT-265

Prefix server errors with `Cog:`

---

python/cog/server/runner.py

If the runner fails to handle an error this gets bubbled up to the worker, which logs a warning and then merrily carries on. Errors bubbling up in this way include things like failing to upload a file, which should fail the prediction. Currently if a model fails to upload one or more files for the prediction, the prediction will still be marked as succeeded, but it won't have any files in the output.

Fail prediction on unhandled error

---

python/cog/predictor.py
python/tests/server/fixtures/input_choices_iterable.py
python/tests/server/test_http_input.py
python/tests/server/test_predictor.py

In the case of the Str (which translates to a StrEnum for choices) the explicit list isinstance check is incorrect. There are many cases where it would be valid to send an `Iterable` such as with `dict.keys()` returning a `dict_keys`. As we do not want to explictly cast to `list` type this commit results in a check of iterable type instead of list.

Choices for Str not just list

---

.github/workflows/docs.yaml

The "deploy docs" workflow is broken because it's using the system python.  This is because actions/setup-python hasn't been told which version to install.

fix docs build

---

pkg/cli/push.go

Sometimes, the `cog push` command returns the following error:
```
unknown: {"errors":[{"code":"NAME_UNKNOWN","message":"The model https://replicate.com/{owner}/{name} does not exist"}]}
ⅹ exit status 1
```
Often, this is because the user ran either `cog login` or `cog push` as `sudo`, which causes Docker to use the wrong credentials.
This PR updates the `cog push` command to explain this error.

Explain `NAME_UNKNOWN` error on failed cog push

---

python/cog/server/clients.py
python/cog/types.py
python/tests/server/test_clients.py
python/tests/test_types.py

We would like `predict` functions to be able to return a remote URL rather than a local file on disk and have it behave like a file object. And when it is passed to the file uploader it will stream the file from the remote to the destination provided.
```py
def predict(self, **kwargs) -> File:
return URLFile("https://replicate.delivery/czjl/9MBNrffKcxoqY0iprW66NF8MZaNeH322a27yE0sjFGtKMXLnA/hello.webp")
```
This PR modifies the URLFile class to use `urllib.request.openurl` instead of `requests` as the HTTP client for reading the file data.
The `urllib.response.addinfourl` interface conforms to the one used by `urllib3.response.HTTPResponse` so I don't think we have any gaps here, longer term we probably want to figure out a more reliable shim. But as this …

[async] Support URLFile in the upload_file function

---

python/cog/files.py
python/cog/types.py
python/tests/test_json.py
python/tests/test_types.py

We would like `predict` functions to be able to return a remote URL rather than a local file on disk and have it behave like a file object. And when it is passed to the file uploader it will stream the file from the remote to the destination provided.
```py
def predict(self, **kwargs) -> File:
return URLFile("https://replicate.delivery/czjl/9MBNrffKcxoqY0iprW66NF8MZaNeH322a27yE0sjFGtKMXLnA/hello.webp")
```
This PR adds an additional check to the `upload_file()` handler to call `fh.seekable()` before attempting to seek. This allows instances of `io.IOBase` that do not support seek (like `URLFile`) to be uploaded.
We also add a `name` attribute to `URLFile`. This is used by the `upload_file` function to infer the file extension and mime type.

Support URLFile in the upload_file function

---

python/cog/__init__.py
python/cog/base_input.py
python/cog/base_predictor.py
python/cog/predictor.py

* Currently these two classes live in predictor
* Separate them out into their own classes to allow for easier reasoning about the predictor code.
This is a subset of https://github.com/replicate/cog/pull/1957/.

Separate BasePredictor and BaseInput from predictor

---

python/cog/types.py
python/tests/test_types.py

This works around an issue where the basename of the URL many not actually
contain a file extension and the uploader logic cannot infer the mime
type for the file.

Support custom filename to be provided to URLFile

---

python/cog/__init__.py
python/cog/mimetypes_ext.py
python/tests/test_mimetypes_ext.py

Fixes PLAT-341
This has only recently been introduced in Python 3.13.0 and is currently inconsistently implemented across different platforms. Confusingly webp is supported in local development on macOS but not when building the docker image of a cog model. This is either because it's not defined in the system mime.types file of the Linux image or because a dev dependency is manually adding it. I've not done the work to fully understand which.
This commit introduces a function called in the init script for the cog package that patches the global mimetypes registry to understand the .webp extension and image/webp mime type. This will be a no-op on systems that already understand the type.
This fixes a bug whereby files with the .webp extension are uploaded to the --upload-url with the …

Add support for image/webp to mimetypes package

---

.gitignore
Makefile
test-integration/test_integration/test_build.py
test-integration/test_integration/util.py
tox.ini

This is still far from perfect, but it attempts a much more thorough comparison of the version reported by cog's CLI binary and the version reported by the embedded Python wheel.

Fix version match test

---

.golangci.yaml
.tool-versions
Makefile
go.mod
pkg/cli/push.go
pkg/config/compatibility.go
pkg/predict/input.go
tools/compatgen/main.go

Upgrade the cog build toolchain to Go 1.23.

Upgrade to go 1.23

---

python/cog/types.py
python/tests/server/test_clients.py
python/tests/test_types.py

It turns out some providers require these headers to be present
otherwise they'll give an error response. This issue is not present
in the requests version of the codebase because the requests library
provides default headers on our behalf.

Provide User-Agent and Accept headers in URLFile requests

---

Makefile

* make test currently fails if COG_WHEEL is not previously defined. This is the case when performing `make test` on a freshly cloned instance.
* Define COG_WHEEL if it doesn’t exist by finding the wheel file in pkg/dockerfile/embed

Fix no COG_WHEEL in Make

---

mkdocs.yml

Add Deployment and Win11 documents to table of contents.
Currently these can only be found more or less by accident, following links from other documents.

Include all documentation in table of contents

---

pyproject.toml

to require version that provides `Buffer` type.
Connected to PLAT-405

Bump version constraint for `typing-constraints`

---

pkg/config/cuda_base_images.json
pkg/config/tf_compatibility_matrix.json
pkg/config/torch_compatibility_matrix.json
pyproject.toml
python/cog/base_input.py
python/cog/server/runner.py
python/cog/types.py
test-integration/test_integration/util.py
tools/compatgen/internal/torch.go

because python 3.7 has been EOL for ~1 year and we cannot continue to support it within Cog.
Closes PLAT-429

Drop support for Python 3.7

---

python/cog/server/runner.py

Exclude invalid output paths from infrastructure errors

---

python/cog/server/connection.py
python/cog/server/eventtypes.py
python/cog/server/helpers.py
python/cog/server/runner.py
python/cog/server/worker.py
python/tests/server/fixtures/hello_world_async.py
python/tests/server/fixtures/logging_async.py
python/tests/server/fixtures/sleep_async.py
python/tests/server/test_worker.py

Reverts #2022 to restore #2010 
plus:
- use async stream redirector in setup, which means writes from C will **not** be captured
- switch to sync stream redirector when not running in async mode
- adjusting accordingly for tests
Closes PLAT-373

Support async predictors (✨ again ✨)

---

pyproject.toml
python/cog/server/connection.py

that results in seemingly unrelated errors like:
```python
File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/spacy/schemas.py", line 250, in <module>
class TokenPattern(BaseModel):
File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
File "/root/.pyenv/versions/3.8.16/lib/python3.8/typing.py", line 774, in __subclasscheck__
return issubclass(cls, self.__origin__)
TypeError: …
```

Downgrade `typing-extensions` to fix conflict with `spacy` and `pydantic`

---

pkg/config/cuda_base_images.json

since the CuDNN version is no longer included in image tags and the `compatgen` tool doesn't know how to look up the CuDNN version from image metadata layers.

Manually patch CuDNN in cuda base images index

---

CONTRIBUTING.md

to hopefully provide a bit more guidance about what a given tag value should be, and also to explicitly include `--annotate` so lightweight tags hopefully aren't being generated.

Update section in CONTRIBUTING about release tags

---

python/cog/server/http.py
python/tests/server/test_http.py

primarily for the Cog version so that clients can include it in telemetry.
plus supporting `python -m cog.http.server --version` for improved runtime inspectability.

Add version and more URLs to index document

---

.github/workflows/ci.yaml

After #2028, we don't need these conditionals.

Tidy up build

---

pkg/predict/input.go

This PR updates the import for the `mime` package to use the local utility which handles the case where `mime.TypeByExtension` returns an empty string. This was likely a regression introduced in 1289b6fe8c2ec01b7d47c6ee970838e5d4be4da7 with auto-imports picking the wrong package to import.
Fixes #2032

Use correct mime package in input.go

---

python/cog/command/openapi_schema.py
python/cog/config.py
python/cog/mode.py
python/cog/predictor.py
python/cog/server/http.py
python/cog/server/worker.py
python/tests/server/conftest.py
python/tests/server/test_http_input.py
python/tests/server/test_predictor.py
python/tests/test_config.py
python/tests/test_predictor.py

* Makes config a first class citizen
* All config variables are accessed through the class properties and resolved at runtime
* Cog Modes are now an enum
* Input/Output Types are managed by the config class
This PR is a subset of https://github.com/replicate/cog/pull/1957/

Add Config class

---

README.md
pkg/cli/root.go
pkg/cli/serve.go
test-integration/test_integration/util.py

to run an HTTP server command very similar to what is used in Replicate production. By making this command more within reach, my hope is that not only is it easier and more clear to run Cog in its HTTP server mode, but also that more Cog users will build familiarity with and opinions about the HTTP server interface.
Connected to PLAT-259

Add serve command

---

python/tests/server/test_http_input.py

I was seeing this test fail in CI (example runs below).  It turns out this test has a race condition - the test asserts that the temp file has been deleted, but the temp file is deleted asynchronously on a
concurrent.futures.Future.add_done_callback() callback.  There is no way to ask a Future to wait until callbacks are finished running (without having the callback itself perform some sort of coordination, which feels like overkill for our needs here).
I fixed this with a quick bodge - we test if the file has been deleted, but if it's still there we wait 200ms and try again.  It's ugly but it works.
I tested this fix works by deliberately adding delays into the callback to verify that waiting before unlinking the file does indeed cause the test failure here.
Example failures:
- …

Fix flake on test_path_temporary_files_are_removed

---

pkg/image/build.go
pkg/image/pip_freeze.go
test-integration/test_integration/test_build.py

* Record the output of a pip freeze to the docker label so we can determine what packages the image
was frozen with.

Add pip freeze to docker label

---

python/cog/files.py
python/cog/types.py

If requests.get has no timeout it is possible to hang indefinitely on a ill behaved webserver. This timeout is explicitly a connect *and* read timeout, meaning if no bytes received.

Bug Fix: Set timeout on requests.get

---

python/cog/config.py
python/cog/server/helpers.py
python/cog/server/http.py
python/cog/server/worker.py
python/tests/server/conftest.py
python/tests/server/test_runner.py
python/tests/server/test_worker.py
python/tests/test_config.py

Currently for models that provide a non-async predict function we have two stream redirectors wrapping stdout/stderr.
We think this entering/exiting the stream redirector context multiple times may have been causing unusual bugs, particularly with models that use libraries like `tqdm` to render progress bars and other manipulation.
This PR changes this behaviour to use either the `StreamRedirector` or (newly renamed) `SimpleStreamRedirector` based on whether the predict is defined with an async function or not. We now use the same redirector for module loading, setup and prediction.
The interrogation of the predict function now happens higher up the stack in http.py when we read the input/output types using `config.get_predictor_types`. This now returns an additional value `is_async` …

Use a single stream redirector for both setup and predict

---

python/cog/__init__.py
python/cog/server/scope.py
python/tests/server/fixtures/emit_metric.py
python/tests/server/fixtures/emit_metric_async.py
python/tests/server/test_worker.py

This helps with the transition between the main cog branch and the experimental `async` branch. Models built for the `async` branch can be run on either without code changes.
New models should still be using the internal `current_scope().record_metric()` interface.

Add deprecated `emit_metric()` helper to cog interface

---

pkg/config/torch_compatibility_matrix.json

* Torchvision 0.20.1 doesn’t work on 2.5.0 cpu torch

Change torch vision to 0.20.0 for torch 2.5.0 cpu

---

pyproject.toml

httpx 0.28.0 has changed a few things that break things for us.  Pin to <0.28.0 so things keep working.

pin httpx to <0.28.0

---

pkg/cli/build.go
pkg/config/config.go
pkg/config/config_test.go
pyproject.toml
python/cog/__init__.py
python/cog/config.py
python/cog/server/helpers.py
python/cog/server/http.py
python/cog/server/runner.py
python/cog/server/worker.py
python/cog/types.py
python/tests/server/conftest.py
python/tests/server/test_runner.py
python/tests/server/test_worker.py
test-integration/test_integration/fixtures/async-sleep-project/cog.yaml
test-integration/test_integration/fixtures/async-sleep-project/predict.py
test-integration/test_integration/fixtures/async-string-project/cog.yaml
test-integration/test_integration/fixtures/async-string-project/predict.py
test-integration/test_integration/test_predict.py

This builds on the work in https://github.com/replicate/cog/pull/2057 and wires it up end-to-end.
We can now support async models with a max concurrency configured, and submit
multiple predictions concurrently to them.
We only support python 3.11 for async models; this is so that we can use
asyncio.TaskGroup to keep track of multiple predictions in flight and ensure
they all complete when shutting down.
The cog http server was already async, but at one point it called wait() on a
concurrent.futures.Future() which blocked the event loop and therefore prevented
concurrent prediction requests (when not using prefer-async, which is how the
tests run).  I have updated this code to wait on asyncio.wrap_future(fut)
instead which does not block the event loop.  As part of this I have updated the …

End-to-end support for concurrent async models

---

pkg/weights/weights.go
pkg/weights/weights_test.go

* Do not consider files within a .git directory when we are using separate-weights
Fixes https://github.com/replicate/cog/issues/2054

Ignore files within a .git directory

---

python/cog/base_predictor.py
python/cog/predictor.py
python/cog/server/worker.py
python/cog/types.py
python/tests/server/fixtures/async_setup_uses_same_loop_as_predict.py
python/tests/server/fixtures/setup_async.py
python/tests/server/fixtures/setup_async_with_sync_predict.py
python/tests/server/test_worker.py

This commit introduces the ability to define an async `setup` function on your predictor. For simplicity an async `setup()` function is only supported alongside an async `predict()` function. An error will be raised during setup if this is not the case.
Various pieces of the code have been extracted into smaller methods in order to achieve this. A new `_handle_setup_error` context manager has been created to handle setup errors and send appropriate `Done` event over the worker channel.
The `_setup()` method has been split into two phases, first we perform validation on the requirements for async/concurrency support. Then we attempt to run the `setup()` method either as a direct call for the non-async path or as part of the event loop in the async path.

Async setup

---

python/cog/server/worker.py
python/tests/server/test_worker.py

Currently a cancellation event sent to a worker with `concurrency` > 1 will always cancel the most recent task.
For the async `_aloop` we now use a weak map to track all in flight prediction tasks. On receipt of a `Cancel` event, we retrieve the task from the map and cancel it.
For the standard `_loop` method we continue to ignore the `Cancel` event. Relying on calling the `send_cancel_signal()` to terminate the worker method before sending the `Cancel` event. I'm not 100% clear on why the parent needs to do this but calling `send_cancel_signal` or raising `CancelationException` directly in the `_loop` method causes the tests to fail so I've left it as-is.

Concurrency cancellation

---

python/cog/server/worker.py

Currently, we download inputs (via URLPath's convert() method) in
_prepare_payload, in the main Worker event consumer loop.  This is bad, because
downloading inputs is a blocking operation and we cannot process other events
while downloads are in progress.
This is a substantial restructuring:
- the event consumer loop now only processes events from the child; prediction
requests and cancel requests from the http server are now processed directly.
- there are new concurrent.future.ThreadPoolExecutor instances for preparing
predictions and downloading inputs.
- as part of this, this commit also supports downloading inputs concurrently
rather than serially.  I have hardcoded a maximum of 8 concurrent downloads
based on the ThreadPoolExecutor size.  I picked this number arbitrarily.
- when …

Download inputs off the event consumer loop

---

docs/yaml.md
pkg/config/torch_compatibility_matrix.json
pkg/dockerfile/standard_generator_test.go
pyproject.toml
python/cog/mimetypes_ext.py
python/tests/server/test_helpers.py
python/tests/test_mimetypes_ext.py
tools/compatgen/internal/torch.go

Cog already supports Python 3.13 fine. This makes some minor changes so our test suite passes for it.

Fix Python 3.13 tests

---

Makefile
python/cog/server/runner.py
python/tests/server/test_worker.py
python/tests/test_config.py
python/tests/test_wait.py
test-integration/test_integration/fixtures/apt-packages/cog.yaml
test-integration/test_integration/fixtures/apt-packages/predict.py
test-integration/test_integration/test_build.py

* Ensure that apt-packages are installed in the main docker image file
* Previously they were installed in a separate stage and not copied over

Add a cog integration test for apt-packages

---

pyproject.toml
test-integration/test_integration/fixtures/pydantic2/cog.yaml
test-integration/test_integration/fixtures/pydantic2/predict.py
test-integration/test_integration/test_build.py

* Add an integration test to validate the problem
* Upgrade fastapi to >= 0.100 to support pydantic 2

Fix pydantic2 cog builds

---

.github/workflows/llm-docs.yml
docs/getting-started.md
docs/llms.txt
docs/python.md
mkdocs.yml

This PR adds an `llms.txt` file that language models can consume at `https://cog.run/llms.txt`
It also adds an Actions workflow that:
1. Runs daily (or manually via workflow dispatch)
1. Uses the [sitefetch](https://www.npmjs.com/package/sitefetch) npm package to compile the llms.txt file.
1. Commits and pushes any changes to the main branch.
I also added tips to a couple of high-traffic docs pages to make the file more discoverable to Cog model authors.

add llms.txt

---

.github/workflows/llm-docs.yml
docs/llms.txt

This PR simplifies the code that generates `https://cog.run/llms.txt`.
Instead of scraping the website and converting the HTML back to markdown, it just concatenates all the markdown docs in the repo together.

simplify llms.txt generation

---

pkg/dockerfile/fast_generator.go
pkg/dockerfile/fast_generator_test.go
pkg/dockerfile/version_check.go

Incorrect formats will likely fail `monobase.build` but it's nice to fail fast here.
We now:
* Pull the support matrix from monobase: https://github.com/replicate/monobase/blob/main/matrix.json
* Compute latest CuDNN version as default if not set
* Check Python+Torch+CUDA venv is in the matrix
* Include supported versions in error message

Check version formats in fast_generator

---

python/cog/types.py
python/tests/test_types.py

* Splits the extension on a ? query parameter
* Ensure that the filename in URLPath is truncated
As an addendum I don't actually know how this comes to be, in the sense that this was originally created by an input that is a `Path` type which gets converted to a `URLPath` and during that conversion the truncation of the filename happens. The truncation is based of parsing the URL and using its `path` attribute which should not include queries. However they somehow sneak past this check and show up in the tempfile `NamedTemporaryFile` method. In light of this I've opted to check the length on creation of the `URLPath` construction and provided some tests to verify that.

Fix file too long on tmp file create

---

pkg/docker/fast_push_test.go
pkg/docker/push_test.go
pkg/web/client.go
pkg/web/client_test.go

* Do not use the username from the authentication credentials, the user could always push to an org
that they have access to.
* Make sure the URL is a r8.im URL before breaking it up.

Enforce usage of r8.im image name

---

pkg/dockerfile/fast_generator.go
pkg/dockerfile/fast_generator_test.go

* Ensure we send an error if the user tries to use fast push with run commands, they are not
supported.

Validate config by checking the run commands

---

python/cog/server/worker.py
python/tests/server/fixtures/import_err.py
python/tests/server/test_worker.py

This commit fixes a bug where we failed to flush the StreamRedirector when catching an exception during the loading of the predictor module.
We now use the existing `_handle_setup_error` function to ensure that the streams are flushed. I've kept the naming of the context manager the same because this all happens as part of the model setup.
Two regression tests have been added to reproduce and verify that the issue has been fixed, both in normal and concurrent/async mode.

Capture standard output when loading the predictor

---

pkg/web/client.go

Since all previous runtime configs include the `sha256:` prefix expected by other components in the whole thing.
Connected to PLAT-848

Include `sha256:` prefix in generated runtime config files

---

pkg/dockerfile/fast_generator_test.go
pkg/requirements/requirements.go
pkg/requirements/requirements_test.go
test-integration/test_integration/fixtures/fast-build/cog.yaml
test-integration/test_integration/fixtures/fast-build/requirements.txt

So that we don't attempt to parse requirements specs and instead pass
them as is to monobase, i.e. `uv pip compile` for validation

Fail python_packages on --x-fast

---

pkg/config/requirements.go
pkg/config/requirements_test.go

Apparently this works:
`uv pip install 'imageio[ffmpeg]==2.37.0'`
And pulls in `imageio-ffmpeg==0.6.0`

Support Python requirements package[extra,...]==version

---

pyproject.toml
tox.ini

Linting got broken because of an autogenerated file by `setuptools-scm` now failing lint after a `setuptools-scm` update. But the question is, should we be linting this file in the first place?
Linting on any PR newer than 2025/02/21 is failing. Linting on this PR should not be failing.

Update ruff config so lint works again

---

pkg/dockerfile/fast_generator.go

We are symlinking the wrong path for the weights since we are not appending `sha256` to the weights path, but that is where we store them

Fix path for weights in symlink

---

pkg/docker/fast_push.go
pkg/docker/fast_push_test.go
pkg/docker/push_test.go

In [this](https://github.com/replicate/cog/pull/2182) PR we moved the weights from `tmp/weights.json` to `tmp/weights/weights.json` but forgot to update one location to keep track of that change.

Handle weights moved to subdir

---

pkg/docker/fast_push.go
pkg/docker/fast_push_test.go
pkg/docker/push_test.go
pkg/dockerfile/fast_generator.go
pkg/dockerfile/fast_generator_test.go
pkg/weights/fast_weights.go

Follow up to #2191
Make sure that separate temp dirs in `fast_push.go` are consistent with `fast_generator.go`.
Add a new tmp dir for tarballs extracted from images, so that they don't cause cache invalidation.

Fix fast tarball tmp dir

---

pkg/monobeam/client.go
tools/uploader/s3.go

The progress bar for fast push has a lot of issues where it eats logs and looks weird. Change a log to a prepended write and remove the bar after it completes so it is more pretty.
Push a model with fast push - the progress bar shouldn't look as ugly.

Make progress bar more pretty

---

docs/python.md
docs/yaml.md

This adds documentation for the new concurrency support in cog 0.14.0.
I moved the "streaming output" section to be under the "output" heading; it fits better here, and it means I can introduce async predictors before talking about AsyncIterator and AsyncConcatenateIterator.  As a result this is probably better viewed as a split diff instead of a unified diff.

Add documentation for concurrency support

---

pkg/util/env.go

This is rarely used without the default right now so it's not urgent, but this conditional is wrong. If the error _is_ nil, return the parsed value, otherwise log the error and continue with the default.

Fix conditional on util package

---

pkg/dockerignore/dockerignore.go
pkg/image/build.go
pkg/weights/fast_weights.go
pkg/weights/fast_weights_test.go

* Respect .dockerignore exclusions and only process weights that appear visible to docker
* Otherwise the `COPY —link` command can’t see the files.
* Centralise the dockerignore functions since they are now used by 2 different packages.

Skip weights that are ignored in dockerignore

---

python/cog/server/http.py

Fixes #2212.
Previously, we had `runner.is_busy()`, which for sync models returned True if a prediction was currently being processed and False otherwise.  But for concurrent models, we can be partially busy.
The cancel method had a fail-fast check to return if we is_busy() returned False.  But with concurrent models, is_busy() has been generalized to mean "is completely full; cannot accept more work".  This meant we could only cancel predictions if we were currently processing concurrency.max predictions.
As it turns out, this fail-fast check is unnecessary.  runner.cancel() checks that the targeted prediction exists and isn't done already.  So we can just drop this check.

Allow cancelation on async models

---

docs/python.md
docs/yaml.md

This a little followup to https://github.com/replicate/cog/pull/2200 with some minor changes to the concurrency docs.
Commits are significant.

Tweak new concurrency docs

---

pkg/cli/build.go
pkg/cli/predict.go
pkg/cli/push.go
pkg/cli/train.go
pkg/config/config.go

* This enables fast builds throughout the build without specifying —x-fast in every command

Add a config option to enable fast builds

---

pkg/docker/push.go
pkg/monobeam/client.go

On the server side, it is useful to know someone wants to upload stuff before they actually start uploading stuff. This PR lets the server know that the user wants to upload stuff.

Hit pre-upload route as part of monobeam uploads

---

pkg/monobeam/client.go
pkg/web/client.go

* Allow us to debug fast push better by including URLs and UUIDs when appropriate

Add more data to error strings

---

python/cog/predictor.py
python/tests/server/fixtures/input_path_or_none.py
python/tests/server/test_http_input.py
test-integration/test_integration/fixtures/new-union-project/cog.yaml
test-integration/test_integration/fixtures/new-union-project/predict.py
test-integration/test_integration/fixtures/pydantic1-none/cog.yaml
test-integration/test_integration/fixtures/pydantic1-none/predict.py
test-integration/test_integration/test_build.py
test-integration/test_integration/test_predict.py

* Support type hints like `str | None` in inputs
* Main issue is the detection of whether something is `Optional`, solved by extending the `Union` detection to `UnionType`

Support UnionTypes in Optional check

---

python/tests/server/test_http.py

* Static schema checks are now made redundant by Pydantic 2.11 adding in additional metadata
* Use the tests to check for targeted dictionary equality instead.

Remove checks for static schema

---

pkg/config/config.go
pkg/config/config_test.go
pkg/dockerfile/fast_generator.go
pkg/dockerfile/fast_generator_test.go
pkg/requirements/requirements.go
pkg/requirements/requirements_test.go

* When reading the requirements txt, handle line continuations and remove comments

Create scanner for removing comments and continuations

---

python/cog/json.py

so that more types than `cog.types.Path` will be treated as path-like uploadables.
Connected to PLAT-1107

Allow `pathlib.Path` and descendants as uploadables

---

pkg/cli/init-templates/cog.yaml
pkg/cli/init-templates/requirements.txt
pkg/cli/init.go

The `python_packages` key in cog.yaml is [deprecated](https://github.com/replicate/cog/blob/4ce6fb90b3812d46b753413e5dc4b3b689ba5785/docs/yaml.md#python_packages) and may eventually stop working entirely.
This PR updates the `cog init` command to use `python_requirements` instead, and adds a starter `requirements.txt` file to the mix with some helpful comments.

Update `cog init` command to use `python_requirements` and `requirements.txt`

---

pkg/config/config_test.go
pkg/config/data/config_schema_v1.0.json

* Allows fast to be defined as a build property in cog.yaml to prevent the constant use of —x-fast flags on the CLI.

Allow fast as a build property in cog.yaml

---

python/cog/ext/__init__.py

~to see if it's an off by one issue that's preventing extension packages from directly depending on `cog`.~
It _is_ an off-by-one level issue! By adding an "empty" `cog.ext` module, we can now add `cog` as a proper dependency of separately distributed packages that want to use `cog.ext` as a namespace package.

Add empty namespace package for `cog.ext`

---

pkg/dockerfile/fast_generator.go
pkg/dockerfile/fast_generator_test.go

* zsh system packages were overwriting the /bin dir
* Follow the symlink on ubuntu instead

Fix tar overwriting symlink directories

---

python/cog/predictor.py
python/tests/test_predictor.py
test-integration/test_integration/fixtures/optional-project/cog.yaml
test-integration/test_integration/fixtures/optional-project/predict.py
test-integration/test_integration/test_predict.py

* Check if the type is optional, if it is and the default is undefined set the default to `None`
* This allows OpenAPI to understand that the field is not required

Prevent Optional Input Types from being required

---

pkg/docker/build.go

Docker desktop w/ containerd enabled is creating [provenance attestations](https://docs.docker.com/build/metadata/attestations/slsa-provenance/) with each build. When this happens, each image is pushed with 2 additional manifests, one is the provenance manifest containing build facts, and the other an index pointing to the actual image and the provenance manifest. While useful in some contexts, cog is not one of them atm. The registry is ignoring them, but this PR disables creation entirely.

Disable provenance attestations

---

pkg/predict/input.go
test-integration/test_integration/fixtures/string-list-project/cog.yaml
test-integration/test_integration/fixtures/string-list-project/predict.py
test-integration/test_integration/test_predict.py

* When the user has an input of `s: list[str]` we want the following to be handled:
```
cog predict -i s=world
```

Handle cog predict lists

---

pkg/cli/init-templates/.dockerignore

Fixes #2275
There is a bug where an existing .python-version file will be copied
from an existing project into the Docker container and conflict with the
Python version set in the cog.yaml.
We now include the .python-version in the .dockerignore file so that
it will not be copied into the container at build time.

Add .python-version to .dockerignore

---

pkg/cli/build.go
pkg/cli/push.go
pkg/coglog/client.go
pkg/coglog/client_test.go
pkg/coglog/env.go
pkg/coglog/env_test.go
pkg/docker/push.go
pkg/docker/push_test.go
pkg/http/user_agent.go
pkg/image/build.go

* Send logs to the `coglog` service when a build or push occurs
* Allow this functionality to be disabled with `R8_COGLOG_DISABLE`

Log cog build/push functions

---

test-integration/test_integration/test_build.py
test-integration/test_integration/test_config.py
test-integration/test_integration/test_migrate.py
test-integration/test_integration/test_predict.py
test-integration/test_integration/test_run.py
test-integration/test_integration/test_train.py
test-integration/test_integration/util.py

This PR updates all the integration tests to use [the `cog_binary` fixture](https://github.com/replicate/cog/pull/2274/commits/ae288968b3bed5102996913592b24086d61dcdd2). This allows the test runner to specify a cog binary to test. When not provided it'll fallback to the existing behavior, which is a PATH lookup for `"cog"`.

Update all integration tests to use the `cog_binary` fixture

---

pkg/migrate/migrator_v1_v1fast.go
pkg/migrate/migrator_v1_v1fast_test.go
pkg/migrate/overwrite_yaml.go
pkg/migrate/overwrite_yaml_test.go

* Currently we strip all the comments
* Instead, merge the 2 YAMLs using direct yaml.Node which doesn’t remove the comments

Handle comments when migrating yaml

---

pkg/migrate/migrator_v1_v1fast.go
test-integration/test_integration/fixtures/migration-no-python-changes-project/cog.yaml
test-integration/test_integration/fixtures/migration-no-python-changes-project/predict.py
test-integration/test_integration/test_migrate.py

* If the code is equal nothing has changed

Do not show option to change code if code is equal

---

.github/workflows/ci.yaml
pkg/dockerfile/env.go
pkg/dockerfile/env_test.go
pkg/dockerfile/fast_generator.go
tox.ini

* Allow environment variables to define what version we use for coglet
* This can be used for forcing a coglet version
* Primarily we use this in the CI to prevent github rate limits

Add environment variable for defining coglet version

---

pkg/requirements/requirements.go
pkg/requirements/requirements_test.go

* Returning an empty line tells the scanner that we are finished.

Do not return an empty line

---

go.mod
go.sum
pkg/docker/docker_command.go
pkg/image/build.go

Multiplexing stderr to a buffer accidentally broke TTY detection in docker when ran as a subprocess. This PR restores it by creating a pty/tty for the subprocess when necessary.
Also fixes:
- `--progress` was not being passed to the second build step.
- stops using a deprecated flag on the docker cli that was causing a warning
Before 
```bash
$ go run ../../../../cmd/cog build -t cog-test
Building Docker image from environment in cog.yaml as cog-test...
#0 building with "desktop-linux" instance using docker driver
#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 560B done
#1 DONE 0.0s
#2 [auth] docker/dockerfile:pull token for registry-1.docker.io
#2 DONE 0.0s
...
```
After
```bash
❯ go run ../../../../cmd/cog build -t cog-test
Building Docker image from …
```

Fix build output

---

pkg/cli/init-templates/cog.yaml

Resolves https://linear.app/replicate/issue/RUNT-76/update-new-model-template-to-set-fast-true

enable `build.fast` in `cog init` template

---

python/cog/command/ast_openapi_schema.py
python/cog/schema.py
python/cog/server/eventtypes.py
python/cog/server/runner.py
python/cog/server/scope.py
python/cog/server/worker.py
python/tests/server/fixtures/with_context.py
python/tests/server/fixtures/with_context_async.py
python/tests/server/test_runner.py
python/tests/server/test_worker.py

This allows a prediction request to include additional per-prediction context alongside the `input`. This will then be made available to the predictor via `current_scope().context`. For now this is limited to `dict[str, str]` but we could expand it later.
The primary benefit is to allow prediction scoped configuration to be passed alongside user input without changing the input signature.
Usage:
```
POST /predictions
{
"input": { ... },
"context": {
"procedure_source_url": "file:///foo/bar/baz",
"replicate_api_token": "r8_foop",
},
}
```
Then in the predictor:
```
def predict():
context: dict[str, str] = cog.current_scope().context
assert context["foo"] == "bar"
```
> [!IMPORTANT]
> The drawback of the current implementation is that this additional configuration is not currently reflected …

Introduce the concept of "context" to PredictionRequest

---

pkg/docker/docker_command.go

* -t works across —timeout and —time

Change stop to -t

---

pkg/cli/push.go

* Models are now created if they are not present

Remove check for image before pushing

---

pkg/cli/baseimage.go
pkg/cli/build.go
pkg/cli/debug.go
pkg/cli/migrate.go
pkg/cli/predict.go
pkg/cli/push.go
pkg/cli/run.go
pkg/cli/serve.go
pkg/cli/train.go
pkg/docker/docker.go
pkg/docker/options.go

Extracted from #2327 to keep the diff small. Once the new client is merged in, setting a truthy value to `COG_DOCKER_SDK_CLIENT` will use it. Needed to run integration tests for both clients in parallel.

Toggle docker client using an env var

---

pkg/docker/docker_command.go

`docker container stop` prints the container id to stdout -- ignore it 
cc @fofr

Stop printing the container ID at the end of `cog predict`

---

python/cog/command/call_graph.py
python/tests/command/call_graph_test.py

* Determines the call graph from within a model
* Fails if the input is not a static string

Add call_graph tool

---

.github/workflows/ci.yaml
pkg/cli/predict.go
test-integration/test_integration/fixtures/training-setup-project/cog.yaml
test-integration/test_integration/fixtures/training-setup-project/predict.py
test-integration/test_integration/fixtures/training-setup-project/train.py
test-integration/test_integration/test_train.py

* Test that the `setup` function is run in a `train` predictor

Add integration test for setup run in trainer

---

.tool-versions
python/cog/predictor.py
python/tests/server/fixtures/input_kwargs.py
python/tests/server/test_http_input.py

This change allows a predictor input to be defined exclusively as `**kwargs`. This is an experimental change that allows a model to be used as a proxy where any inputs will be passed through directly without modification.
```py
import json
def predict(**kwargs) -> str:
return json.dumps(kwargs)
```
This change restricts the use of `**kwargs` to functions/methods that accept only that as an argument to avoid the complexity of having to support both dynamic and fixed inputs.
The OpenAPI schema for such a model will be:
```json
{
"properties": {},
"additionalProperties": true,
"type": "object",
"title": "Input"
}
```

Support kwargs predictors

---

.github/workflows/ci.yaml

I ran into an issue over in #2327 where branch protection rules will never pass when referring to matrix jobs.
The rule requires a check named `"Test Integration"` to be successful, but after making that GHA job a matrix, names are now `"Test Integration (matrix-param)"`, which obviously won't match.
This PR adds a new meta job named "Test Results" which depends on the integration matrix job, as well as the other tests that were probably not required because of the same issue.
@tempusfrangit once this is merged can you change the required check name to "Test Results"?

Fix for branch protection rules + dynamic matrix jobs

---

pkg/dockerfile/fast_generator.go
pkg/web/client.go
test-integration/test_integration/fixtures/fast-build/cog.yaml
test-integration/test_integration/test_build.py
test-integration/test_integration/test_predict.py

We've transitioned usage of `--x-fast` to `fast: true` in the `cog.yaml`. We should change all references within our code to reflect this.

Make all instances of --x-fast use fast:true instead

---

pkg/http/transport.go
pkg/http/transport_test.go

* Do not overwrite the content-type header if it is explicitly set by the user

Only overwrite header if it doesn’t exist

---

pkg/cli/predict.go
pkg/predict/predictor.go

Now when running `cog predict` with `--use-replicate-token` any `REPLICATE_API_TOKEN` in the current environment will be passed into the model via the `context` field on the prediction/training request.
```sh
REPLICATE_API_TOKEN=r8_xyz cog predict --use-replicate-token -i prompt="make me a sandwich"
```
This will then be available on the current scope and picked up by the Replicate Python client (as of v1.0.7).

Pass REPLICATE_API_TOKEN to model via context

---

pkg/config/torch_compatibility_matrix.json
test-integration/test_integration/fixtures/granite-project/requirements.txt
test-integration/test_integration/test_predict.py

* Adds torch 2.6.0 and torch 2.7.0 to the compatibility matrix
* This will temporarily break builds against these versions on main until we build the base images (which will come after this PR is merged)

Add recent torch compatibility matrix

---

pkg/cli/baseimage.go

* Allow generate-matrix to generate a matrix of builds with multiple parameters for
cuda/python/torch

Allow comma separated versions in generate-matrix

---

pkg/docker/docker_client_test.go
pkg/docker/errors.go

We have a test that makes sure the docker client correctly handles network errors on push. The test checks for one of several known errors, but every so often the suite lands on a GHA runner that correctly fails, but with a different error message. 
This adds a helper to match common errors and calls that from the test.

Fix flaky registry test

---

pkg/docker/dockertest/mock_command.go
pkg/docker/pipeline_push_test.go
pkg/docker/push_test.go
pkg/env/env.go
pkg/web/client.go
pkg/web/client_test.go

This follows the procedure for shipping an experimental "pipeline" model via the API used by other areas of the Replicate product.
We use the new cog.replicate.com/api/token/{account} endpoint to exchange the cog token for a short lived Replicate API token that is restricted only to read/write actions on model resources.
Usage:
cog push --x-pipeline r8.im/username/my-model

Refactor PostNewPipeline to use Replicate public API

---

pkg/api/client.go
pkg/api/client_test.go

* We weren’t correctly separating the image name from the tag

Handle tags at the end of images

---

python/cog/server/http.py

Cog currently uses deprecated `@app.on_event()` handlers which cause deprecation warnings in FastAPI.
- Migrated from `@app.on_event("startup")` and `@app.on_event("shutdown")` to FastAPI's lifespan handlers
- Updated imports to include `asynccontextmanager`
- No functional changes, just API modernization

Fix FastAPI deprecation warnings by migrating to lifespan handlers

---

pkg/cli/predict.go
pkg/path/path.go
pkg/path/path_test.go
pkg/web/client.go
test-integration/test_integration/fixtures/string-project/input.json
test-integration/test_integration/test_predict.py

This PR introduces `cog predict --json` that represents both input and output as JSON.
The intention behind this PR is to provide a better interface for machines to interface with `cog predict`. Such as running automated tests. In these cases trying to parse the existing unstable output is non-trivial. Having access to the full JSON prediction makes things much easier.
In order to do this correctly the PR also fixes a number of bugs with the `--output` behavior.
* We now support passing a directory as an output value e.g. `--output ./outputs`
* We now honor the `--output` flag for lists of files. Previously if a model returned a list of files they would all be `output.<idx>.<ext>` regardless of the --output flag.
* We now error with a non-zero exit code if the prediction is not …

Refactor `cog predict` to support `--json` flag

---

pkg/cli/run.go
test-integration/test_integration/test_run.py

* Cog run fast builds the image then runs the command on that image if in fast mode

Add support for fast build images in cog run

---

docs/cli.md
mkdocs.yml

This adds a section to the cog documentation for the CLI interface including the newly added `cog predict --json` command.

Document the cog CLI

---

pkg/requirements/requirements.go
pkg/requirements/requirements_test.go

* Do not consider lines with editable commands as part of the read requirements output

Filter editable commands out of read requirements

---

test-integration/test_integration/conftest.py
test-integration/test_integration/test_build.py
test-integration/test_integration/test_predict.py

We have a few integration tests that fail randomly due to a race, eg: 
```
FAILED test_integration/test_build.py::test_fast_build - IsADirectoryError: [Errno 21] Is a directory: '/home/runner/work/cog/cog/test-integration/test_integration/fixtures/fast-build/weights.h5'
```
The issue is that several integration tests alter the same fixture directory during a test. If the tests run concurrently, it's likely the weights.h5 file will be removed by the first before the second is done with it.
This PR adds a fixture helper that'll give each test a unique copy of a fixture that gets cleaned up automatically. I only updated the flakey tests, but this is probably good to add to the rest since things like `.cog` temp dirs often linger as well.

Fix flakey integration tests

---

pkg/docker/docker.go

Switches the default docker client to the new one introduced in #2327. It's been available for about a month by calling with `COG_DOCKER_SDK_CLIENT=1`. 
No show-stopping issues came up through internal testing or integration tests on CI, but if anything does arise users can revert to the previous behavior by running with `COG_DOCKER_SDK_CLIENT=0`, such as:
```
COG_DOCKER_SDK_CLIENT=0 cog build ...
```

Enable docker api client by default

---

pkg/cli/init.go
pkg/cli/init_test.go

This updates the `cog init` command to allow for skipping files that already exists either one by one or all at once
It also adds two cli flags `--skip-existing` and `--overwrite-existing` which will either:
1. skip all existing flags without prompting
2. overwrite all existing flags without prompting
I chose to not just skip existing by default as to be more consistent with the existing behavior, but I could also see the argument that we just want to always skip all existing files.. so would like to get feedback here
```
Setting up the current directory for use with Cog...
File cog.yaml already exists. What would you like to do? (default: skip, options: skip, skip-all, quit): skip
Skipped existing cog.yaml
✅ Created /Users/markphelps/workspace/replicate/pipelines-test/predict.py
File …
```

feat: add ability to skip files that already exist, overwrite or quit

---

pkg/config/torch_compatibility_matrix.json

* Wrong version of torchvision was included for torch `2.7.1`

Fix torch vision compatibility matrix

---

pkg/procedure/validate.go

* Currently the absolute path is assigned to the requirements file in the config
* This will then merge with the project directory making the file path invalid
* Instead, send back the relative path from the project directory

Send back relative path in download

---

pkg/docker/api_client.go

* When the user information cannot be loaded, ask the user to use cog login

Include cog login in error message

---

CONTRIBUTING.md

Was just cutting a new release and noticed this process has changed a bit. These instructions worked for me.
- Sign with GPG
- Get teammates to approve PyPI publish request

docs: document new requirements for cutting releases

---

test-integration/test_integration/fixtures/string-project/cog.yaml

* Only run the version check on non cog-runtime builds

Fix version check integration test

---

python/cog/command/call_graph.py

This API will be removed in Python 3.14 and is creating noisy deprecation warnings.

Swap out deprecated `ast.Str` for `ast.Constant`

---

pkg/cli/login.go
pkg/cli/root.go
pkg/docker/api_client.go
pkg/docker/credentials.go
pkg/docker/credentials_test.go
pkg/global/global.go

Implements support for other registries besides hardcoded `r8.im`
- **Add `COG_REGISTRY_HOST` environment variable** for persistent registry override
- **Add `--registry` global persistent flag** (hidden) for one-off overrides  
- **Implement credential fallback**: when alternate registry has no credentials, automatically reuse `r8.im` credentials
- **Update API client** to dynamically load registry authentication
- **Update login messages** to show actual registry host being authenticated
```
--registry flag (highest - one-off overrides)
↓
COG_REGISTRY_HOST env var (session/testing)
↓
Default "r8.im" (lowest - production)
```
Internal teams can now test alternate registries:
```bash
export COG_REGISTRY_HOST=x.r8.im
cog login
cog push x.r8.im/user/model
cog --registry x.r8.im login
``` …

feat: add registry migration support with credential fallback
