replicate/cog

pkg/cli/repo.go
pkg/cli/root.go
pkg/client/client.go
pkg/client/delete.go
pkg/client/download.go
pkg/client/get.go
pkg/client/list.go
pkg/client/ping.go
pkg/client/upload.go

Default Cog server host set in COG_SERVER env var

---

pkg/cli/test.go
pkg/docker/local_builder.go
pkg/model/model.go
pkg/server/build.go
pkg/server/web_hook.go
pkg/serving/local.go
pkg/serving/platform.go
pkg/serving/test.go

Record memory usage and run time in model object

---

pkg/cli/infer.go
pkg/serving/platform.go

Expand home dirs on infer input/output

---

go.mod
go.sum
pkg/server/build.go
pkg/server/server.go

Better server logging

---

pkg/docker/local_builder.go

Lowercase docker tag

---

.gitignore
pkg/docker/cog.py

Reliable queues using Redis streams

---

end-to-end-test/end_to_end_test/test_server.py
pkg/docker/cog.py
pkg/server/build.go
pkg/serving/test.go

Save test output if not defined in config examples

---

pkg/cli/show.go
pkg/docker/cog.py
pkg/docker/cog_test.py
pkg/model/model.go

Input options

---

pkg/serving/local.go

Remove container after run

---

go.mod
go.sum
pkg/serving/local.go

Strip multiplexing prefix from test container logs

---

pkg/serving/test.go

Make examples relative to project root rather than workdir

---

pkg/serving/local.go

Container stats report cumulative CPU secs from the container was started.

Fix CPU stats

---

pkg/cli/test.go
pkg/server/queue.go
pkg/serving/test.go

* Running cpu and gpu build in parallel, there was a race condition when saving example output
* Throttling was broken, fixed with semaphore

Fix concurrency issues

---

pkg/server/queue.go

Rejig async logic to fix deadlock bug

---

end-to-end-test/end_to_end_test/test_server.py
go.mod
go.sum
pkg/cli/benchmark.go
pkg/cli/build.go
pkg/cli/infer.go
pkg/cli/push.go
pkg/cli/repo.go
pkg/cli/root.go
pkg/cli/server.go
pkg/cli/show.go
pkg/client/build.go
pkg/client/get.go
pkg/database/build_logger.go
pkg/database/database.go
pkg/database/local.go
pkg/logger/logger.go
pkg/model/config.go
pkg/model/model.go
pkg/server/build.go
pkg/server/get.go
pkg/server/queue.go
pkg/server/server.go
pkg/server/web_hook.go
pkg/serving/local.go
pkg/serving/test.go

Background builds

---

pkg/cli/test.go
pkg/server/queue.go
pkg/serving/mock.go
pkg/serving/test.go
pkg/serving/test_test.go

Also fixes bug where example outputs were relative to workdir instead
of root dir (like example inputs are)

Unit tests for model testing

---

pkg/docker/mock.go
pkg/server/queue.go
pkg/server/queue_test.go
pkg/server/server.go

Queue test

---

pkg/cli/debug.go
pkg/cli/test.go
pkg/docker/generate.go
pkg/docker/generate_test.go
pkg/server/queue.go

...instead of base64-encoding contents

Install cog.py library file a copied file

---

pkg/server/queue.go

Fix concurrent map read issue in queue

---

pkg/cli/debug.go
pkg/cli/root.go
pkg/cli/test.go
pkg/docker/generate.go
pkg/docker/generate_test.go
pkg/model/config.go

Extracting a few preparatory bits of work from my work on local mode so as not to make it a nightmare to merge. Feel free to merge at any point, and I will continue to add to this.

Local prep work

---

end-to-end-test/end_to_end_test/test_server.py

Fix end to end tests

---

pkg/cli/run.go

Local mode fixes

---

README.md
docs/getting-started-own-model.md
docs/getting-started.md
docs/python.md
docs/yaml.md

Update docs and add docs for setting up own model

---

pkg/cli/build.go
pkg/cli/predict.go
pkg/cli/push.go
pkg/cli/run.go
pkg/client/build.go
pkg/logger/logger.go

Use a logwriter to print build output to fix #109.

Fix `cog build log` on failure

---

pkg/image/type_signature.go
python/cog/input.py
python/cog/predictor.py
python/cog/server/ai_platform.py
python/cog_test.py
test-integration/test_integration/test_build.py

Make inputs a list so they are ordered

---

pkg/cli/build.go
pkg/cli/predict.go
pkg/cli/push.go
pkg/cli/run.go
pkg/docker/build.go
pkg/image/build.go

Add build --progress flag similar to docker and docker-compose

---

pkg/docker/login.go

Fix cog login when creds is not set in docker's config.json

---

python/cog/server/redis_queue.py

Capture exception tracebacks in redis queue worker

---

CONTRIBUTING.md

document the release process

---

docs/python.md

Document not downloading weights in setup()

---

CONTRIBUTING.md

Resolves https://github.com/replicate/cog/issues/244

clarify installation steps for Mac M1 users

---

.vscode/extensions.json
Makefile
python/cog/server/http.py
python/cog/server/redis_queue.py
python/cog_test.py
test-integration/test_integration/fixtures/failing-project/cog.yaml
test-integration/test_integration/fixtures/failing-project/predict.py
test-integration/test_integration/fixtures/yielding-project/cog.yaml
test-integration/test_integration/fixtures/yielding-project/predict.py
test-integration/test_integration/test_redis_queue.py
tools.go

Yet Another Pull Request! This is a cleaned up and squashed version of #248

Yield progressive output squashed

---

README.md

Like https://github.com/replicate/cog/pull/243, but for the README this time.

update install commands in README

---

docs/getting-started.md

Makes this make marginally more sense as a way to try out Replicate. I think JSON output is still broken though. :(

Use r8.im in docs

---

docs/yaml.md

This PR makes a few minor updates to the `cog.yaml` reference documentation.

update cog.yaml reference doc

---

README.md

minor tweak to function names in example

---

pkg/cli/predict.go
pkg/docker/image_exists.go
pkg/docker/image_inspect.go
pkg/docker/pull.go
pkg/image/config.go

Fixes https://github.com/replicate/cog/issues/280

Make remote models use GPUs in cog predict, if model requires GPU

---

pkg/docker/run.go
pkg/image/type_signature.go
test-integration/test_integration/test_build.py

Re-run type signature step without GPU if it fails with something that
looks like a missing device driver error

Relax GPU requirements for build

---

docs/yaml.md

A tiny followup to https://github.com/replicate/cog/pull/317#issuecomment-956577635

use r8.im as the only `image` example

---

python/cog/command/type_signature.py
python/cog/suppress_output.py
python/cog_test.py
test-integration/test_integration/conftest.py

Fixes https://github.com/replicate/cog/issues/295

Suppress output before parsing type signature

---

.github/workflows/ci.yaml

Handy for testing local branches etc.

Run CI on all pushes

---

.vscode/settings.json

All the testing integration works now, including handy little "run this test" buttons on tests:

Configure VSCode for py.test

---

README.md
docs/python.md
pkg/cli/init-templates/cog.yaml

* Tiny - fix some typos in docs
* Tiny - fix a typo found by spellchecker.

Tiny - fix some typos in docs

---

pkg/config/config.go
python/cog/predictor.py
test-integration/test_integration/test_predict.py

Support predict modules in subdirectories

---

test-integration/test_integration/conftest.py
test-integration/test_integration/fixtures/file-project/cog.yaml
test-integration/test_integration/fixtures/file-project/predict.py
test-integration/test_integration/fixtures/logging-project/cog.yaml
test-integration/test_integration/fixtures/logging-project/predict.py
test-integration/test_integration/test_build.py
test-integration/test_integration/test_redis_queue.py
test-integration/test_integration/util.py

Makes it easier to edit and reason with.

Move integration test project to fixtures

---

pkg/cli/root.go
pkg/docker/run.go
pkg/global/global.go
test-integration/test_integration/fixtures/no-predictor-project/cog.yaml
test-integration/test_integration/test_build.py

Clean up build integration tests

---

pkg/predict/predictor.go

The new Cog internals return a 422 instead of a 400 when the input is invalid. Rather than dumping that out as a cryptic "returned a 422" message, pull out the individual validation issues from the response and present them to the user.
Adding the hint about how to provide inputs on the command line will hopefully help first time users who are running a bare `cog predict`.

Better error message when providing invalid inputs

---

test-integration/test_integration/test_redis_queue.py

This is one of the tasks on our todo list in #407. It works basically fine already, so I've added a test to assert that. No code change necessary.

Add a test for error messages from invalid input

---

docs/python.md

document how to yield progressive output

---

docs/getting-started-own-model.md
docs/python.md
python/cog/predictor.py
python/tests/server/test_http.py
python/tests/server/test_http_input.py

This will probably work with Replicate, but at least the Cog side
definitely works so we can fix that later.

Support int choices

---

README.md

This is not true. It will be soon. But right now it is confusing.

Remove references to nascent AMQP API

---

python/cog/server/http.py
python/tests/server/test_http.py

Yielding predictors were deleting inputs before the prediction had
been run, resulting in `cog predict` being broken for progressive
output models that take files as input.
With this change, the cleanup doesn't happen until after the
prediction has completed.
Related to https://github.com/replicate/cog/pull/472

Fix yielding predictor cleanup bug in HTTP server

---

pkg/cli/run.go

Resolves #357 
- Currently we shell out to the docker CLI, but ideally we'd call the Docker API directly.
- Allow `cog run` to pass flags arbitrarily instead of -p specifically? (No)
- Use something like `NextFreePort` to support `cog run notebook` without specifying a port?
🍐 @evilstreak

add `-p` to `cog run` to forward ports

---

CONTRIBUTING.md

Define some nouns

---

README.md
docs/deploy.md
docs/getting-started-own-model.md
docs/getting-started.md
docs/http.md

Add documentation to explain how to deploy models

---

pkg/dockerfile/generator.go
pkg/dockerfile/generator_test.go

It doesn't actually do anything, but a useful bit of metadata about the
container to explain what port is exposed.

Add EXPOSE to Dockerfile

---

python/tests/test_json.py

These were half written and commented out for some reason.

Enable file and numpy encode_json() tests

---

docs/python.md

Resolves https://github.com/replicate/cog/issues/539

docs: `cog.Input()` is optional

---

README.md
docs/getting-started.md

Fix getting started guide

---

docs/getting-started.md

This PR removes the `--gpus all` flag in the `docker run` example in the Getting Started guide.
It also makes some changes to the formatting to make it easier to use.
First, the `cog.yaml` example doesn't include `gpu: true`
and second, that causes the command to fail on systems without GPUs
That plus the voluminous TensorFlow warnings convinced me I had something wrong in my Cog setup
-- that I needed `nvidia-docker` or hadn't set an env variable correctly, but it was just the flag.
You could put a specific note about the warnings from TF and direct folks to the `#gpus` section of the BYOmodel start guide.
I also updated the formatting, using some ideas from
[this style guide](https://arcticicestudio.github.io/styleguide-markdown/rules/code.html)
for code in Markdown.
The code snippets …

Drops --gpus flag, updates formatting

---

.vscode/settings.json
Makefile
mypy.ini
python/cog/files.py
python/cog/json.py
python/cog/predictor.py
python/cog/response.py
python/cog/server/http.py
python/cog/server/log_capture.py
python/cog/server/redis_queue.py
python/cog/server/runner.py
python/cog/suppress_output.py
python/cog/types.py
requirements-dev.txt

Cog is all about Python types, so why aren't we using it on Cog's codebase?
I ran mypy against Cog for fun and then it complained a lot and then realized this was going to be less fun than I anticipated. So, I am merely flipping the switch here and leaving the rest for us to chip away at over time.
Lots of fun here for those so inclined: 🎹🎹🎹
```
python/cog/server/log_capture.py:9: error: Function is missing a type annotation
python/cog/server/log_capture.py:85: error: Function is missing a type annotation
python/cog/server/log_capture.py:98: error: Function is missing a return type annotation
python/cog/server/log_capture.py:98: note: Use "-> None" if function does not return a value
python/cog/types.py:16: error: Function is missing a return type annotation
python/cog/types.py:16: error: …
```

Add mypy and typing

---

README.md
pkg/cli/init-templates/predict.py
pkg/cli/predict.go
test-integration/test_integration/fixtures/int-project/predict.py
test-integration/test_integration/fixtures/string-project/predict.py
test-integration/test_integration/fixtures/subdirectory-project/my-subdir/predict.py
test-integration/test_integration/test_predict.py
test-integration/test_integration/test_redis_queue.py

Having a magic `input` input was weird and collided with Python's
built-in `input()`.
Closes #381

Make default input first input

---

docs/yaml.md

Add an example for `cuda` in `cog.yaml` docs

---

docs/redis.md

...so people reading Cog's Redis API docs have a better chance of finding it.
Signed-off-by: Zeke Sikelianos <zeke@sikelianos.com>

link to cog-redis-example repo

---

python/cog/json.py
python/cog/server/http.py
python/cog/server/redis_queue.py
python/cog/server/runner.py
python/setup.py
python/tests/server/test_http_output.py
python/tests/test_json.py
test-integration/test_integration/fixtures/yielding-list-of-complex-output-project/cog.yaml
test-integration/test_integration/fixtures/yielding-list-of-complex-output-project/predict.py
test-integration/test_integration/test_redis_queue.py

Starting by refactoring the Redis queue worker so it uses the same encoding as HTTP to hopefully remove a whole class of problems.
The last commit is the real change. Other commits are refactoring preludes.
Based on https://github.com/replicate/cog/pull/665

Fix Redis worker yielding list of complex outputs

---

pkg/update/update.go

Fix update check showing immediately after upgrading

---

pkg/config/config.go
pkg/config/config_test.go

Suggest upgrading Cog if CUDA version can't be found

---

docs/redis.md
python/cog/server/redis_queue.py
requirements-dev.txt
test-integration/test_integration/test_redis_queue.py

~~Some test shenanigans to work out still!~~
~~Opening to get feedback on the interface, because it feels a bit Marmite.~~
This is ready to go! Details in the commit message.

Send queue worker responses to webhooks

---

test-integration/test_integration/test_redis_queue.py

There's what looks like a timing issue with this test, where occasionally the error from the prediction runner will get processed before the log capture has managed to send back logs, and the response is sent back without the stacktrace being logged.
Having the stacktrace is nice, so longer term we should fix this (hence the TODO). For now, having a flaky test on main is something best avoided.

Disable flaky stacktrace logging test

---

pkg/cli/login.go

Allows users to `cog login` on CI and other non-interactive environments.
Usage:
```
echo $REPLICATE_TOKEN | cog login --token-stdin
```

Non-interactive login with --token-stdin

---

python/cog/server/redis_queue.py
test-integration/test_integration/test_redis_queue.py

For the terminal response, sending the webhook is pretty important. Retry up to a dozen times over the course of 5 minutes, with exponential backoff. This will get through temporary issues very quickly (5 retries within ~3 seconds) and through longer lived issues eventually, with progressively less pressure on the downstream service.
For non-terminal responses, we just try them once. Another response will be along soon enough, and as we're sending full snapshots the loss of an intermediate response isn't serious.
Fixes #742

Retry webhook for terminal responses

---

pkg/config/config_test.go

Just a more complete tests. Also surfaced a couple of little test bugs.
Cherry picked from #714

Use ValidateAndCompleteConfig in config tests

---

python/cog/server/runner.py

We're planning to rewrite this subprocess communication Real Soon Now, but there's a bug with cancellation timing we need to fix.
If the runner gets sent a cancel signal (SIGUSR1) whilst it's outside of the _run_prediction try block, the exception isn't caught and it's then possible for the next prediction to end up with incorrect input/output.
Rejigging where the cancel signal is registered, and where it's caught, should make the runner behave as expected.

Address timing issue with cancel signal

---

python/cog/server/redis_queue.py

Rejig the functions to end up with a `run_prediction()` function that takes the message and yields responses. My intent here is to wrap up the event stream from `Worker` with something that yields the responses we want to send back to the webhooks. These responses should also be the same thing we want to return to HTTP requests, allowing us to reuse this wrapping.
There shouldn't be any behaviour change in this PR.
It feels like it should probably live in a separate class (and be unit tested!), though I'm not sure what that'd be called.
Signed-off-by: Dominic Baggott <dominic.baggott@gmail.com>

Refactor redis_queue to extract response building

---

python/cog/server/redis_queue.py

We're occasionally seeing models get into a zombie state in Replicate, where the model will keep accepting jobs but it fails every single one. When it's failing them very quickly, and survives as the final worker after the model is downscaled, we end up serving only failures for the affected model.
This change allows a maximum consecutive number of failures to be set. If the worker fails more than that many predictions in a row, it'll exit, forcing a new (hopefully healthy) worker to be started to take its place.
---
Opening this as a draft because it's based on top of #799, which will need reviewing first.

Add option to exit redis worker after too many failures

---

.github/workflows/ci.yaml
CONTRIBUTING.md
go.mod
pkg/cli/init.go
pkg/config/load.go
pkg/config/load_test.go
pkg/dockerfile/generator_test.go
pkg/predict/input.go
pkg/update/state.go

Upgrade to Go 1.19

---

.github/workflows/ci.yaml
pkg/docker/run.go
pkg/predict/predictor.go
pkg/util/shell/net.go
requirements-dev.txt
test-integration/Makefile

Use faster GitHub runners

---

.github/workflows/ci.yaml
Makefile

I think this is the bottleneck in CI now.

Run Python tests in parallel

---

CONTRIBUTING.md

Update instructions for installing `cog` for development

---

.github/workflows/ci.yaml

This reverts commit c4e692072cb3913d501888711f5f00dd1975efee.

Revert "Bump to 64 cores"

---

python/pyproject.toml
python/tests/server/test_http.py
requirements-dev.txt

Some miscellaneous issues to get my dev environment (mostly) working again.

Dependency fixes

---

python/cog/director/director.py

We were only shutting down the model when hitting an exceptional case an aborting previously. We no longer need to do the shutdown in `_abort` because we're doing it in the `finally` block in `start()`.

Shut down model container on graceful termination

---

python/cog/server/http.py

We saw an issue in production where the model container took longer than 5s to terminate after a call to `/shutdown`. We think this is because the server thread was busy doing something (like uploading a file), so took a while to process the change to `should_exit`.
This change gives the server 1 second to exit, at which point it sends a SIGKILL if it's still running. This is perhaps a little overkill, but the number of threads that are involved in this makes any gentler approach a pain to implement.

SIGKILL when http server receives shutdown call

---

python/cog/director/director.py
python/cog/director/prediction_tracker.py
python/cog/server/http.py
python/cog/server/runner.py

A few extra fixes – details in the commits!

Add async api fixes

---

python/cog/director/director.py
python/cog/server/runner.py

- Extends CANCEL_WAIT to 30s for now
- Adds some more detailed logging in director
- Adds log context and basic lifecycle events in the model container

Logging changes for split cog

---

python/cog/server/webhook.py

Optionally add authorization header to all webhook HTTP calls

---

python/cog/director/__main__.py
python/cog/director/director.py
python/cog/director/redis.py

We rotate on every loop of the director.
~~If this makes sense, the next steps will be to update the config to actually support configuring more than one Redis.~~

Support multiple Redis endpoints, rotating between them

---

python/cog/director/redis.py

We've given director the ability to cycle through multiple Redis queues to make it possible to migrate to another Redis instance. For that to work it needs to not blow up when the queue is missing!

Ignore XREADGROUP error on missing queue

---

python/cog/server/runner.py
python/tests/server/test_http_input.py

runner: gracefully fail if failing to get url path

---

pkg/predict/predictor.go
python/cog/server/http.py
python/cog/server/runner.py
python/tests/server/conftest.py
python/tests/server/test_runner.py

Currently, `Runner.setup()` blocks. When we call it in the FastAPI app `startup` hook, we block the initialisation of the HTTP server itself.
That in turn means that any attempts to connect to the HTTP interface while setup is running are refused, so we cannot successfully shut down a model container while setup is running. This leaves model pods in a broken state for up to 30m (the K8S termination grace period) until they are killed.
This changes `Runner.setup()` to a non-blocking method that returns an AsyncResult. We can then poll this object when the healthcheck endpoint is called to find out whether setup is complete.
Note that it is not a requirement to call the healthcheck endpoint. While setup is running, prediction endpoints will return a 409 Conflict indicating that the …

Run setup on a background thread

---

pkg/cli/build.go
pkg/cli/push.go
pkg/docker/build.go
pkg/image/build.go

See https://github.com/replicate/cog/pull/1013#issuecomment-1523964080

Add `--no-cache` flag to `cog build` and `cog push` commands

---

docs/private-package-registry.md
pkg/cli/build.go
pkg/cli/push.go
pkg/docker/build.go
pkg/image/build.go

Add `--secret` flag to `cog build` and `cog push` commands

---

python/tests/server/test_http_output.py

Fix typo in test_http_output.py

---

python/cog/server/http.py

From https://github.com/replicate/cog/issues/1099#issuecomment-1598643259:
> @remorses: Currently there is no logs if the port is already used, printing a message like `port 5000 already in use` would already be a great improvement
This PR updates `cog.server.http` to check whether the configured port is already in use, and if so, exits with error message and status code 1.
As I mentioned in https://github.com/replicate/cog/issues/1099#issuecomment-1598683605, this shouldn't happen when running with Docker. However, if there were a conflict, this change would make it easier to detect.

Check whether port is already in use before starting HTTP server

---

pkg/image/build.go

Resolves #1093
#1008 added OCI annotations for the Git commit and version of the source repository when building a Cog model image. To determine the Git tag, Cog checks for a `.git` directory, and then runs `git describe --tags --dirty`. If this command fails, then an error is logged.
Currently, this error is logged as a warning. If the subsequent `docker buildx build` command fails, this log severity gives the false impression that the build failed because it was unable to determine the Git tag.
This PR changes the log level to info and changes the language from "Failed" to "Unable to" to provide a better sense of severity.

Change logging level to info when unable to determine Git commit or tag

---

docs/wsl2/wsl2.md

Resolves https://github.com/replicate/cog/issues/1024
This PR updates the [WSL2 docs](https://github.com/replicate/cog/blob/07cec363be4a68cd401b90edd91e57dc9949bac7/docs/wsl2/wsl2.md) according to the feedback @boxabirds provided in https://github.com/replicate/cog/issues/1024.
I don't have access to a Windows environment, so I haven't tested this myself.

Fix instructions for Windows 11

---

.vscode/extensions.json
.vscode/settings.json
pyproject.toml
python/cog/server/http.py
python/cog/server/probes.py
python/tests/server/fixtures/catch_in_predict.py
python/tests/server/test_http_input.py
test-integration/test_integration/fixtures/many-inputs-project/predict.py

This PR updates settings in Visual Studio Code to use [Black](https://github.com/psf/black) for formatting and to run [Ruff](https://beta.ruff.rs/docs/) to automatically fix any violations on save. It also updates the list of recommended extensions to include those used in the default project settings.

Update VSCode recommended extensions and settings

---

pkg/cli/init-templates/.dockerignore
pkg/cli/init.go
pkg/cli/init_test.go

Resolves https://github.com/replicate/cog/issues/209

Add `.dockerignore` file to `cog init` template

---

pkg/cli/predict.go
test-integration/test_integration/test_predict.py

Don't use first input as implicit input name in `cog predict`

---

pkg/config/image_name.go
pkg/config/image_name_test.go

Conditionally prepend `cog-` to default image name

---

README.md

added installing buildx to doc

---

python/cog/command/ast_openapi_schema.py
python/cog/predictor.py
python/cog/server/worker.py
python/tests/server/fixtures/async_hello.py
python/tests/server/fixtures/async_yield.py
python/tests/server/test_http.py
python/tests/server/test_worker.py

This reverts commit 95fc689f35f2c5100af67c889135921807db9004.

Revert "support async predict functions  (#1350)"

---

python/tests/server/test_worker.py

- added "slow" hypothesis profile in python worker test to make it passing on slow systems

fix(python_test): added "slow" hypothesis profile in python worker test

---

python/cog/server/http.py
python/cog/server/runner.py

Returning a `PredictionResponse` from setup was (I think) a bit of a hack to make the typechecker happy. Unfortunately it's pretty confusing, as `PredictionResponse` has a whole bunch of fields on it that mean nothing in the context of a setup result.
This commit reduces the confusion by introducing a dedicated `SetupResult` type and using that where appropriate.

Don't return a PredictionResponse from PredictionRunner.setup

---

python/cog/server/http.py
python/tests/server/fixtures/slow_setup.py
python/tests/server/test_http.py

#1433 introduced a race condition if healthcheck happens before setup is done

check if setup_result is None

---

pyproject.toml

fix: update the version typing_extensions to use latest version 

---

.goreleaser.yaml

refs https://github.com/goreleaser/goreleaser/issues/4513

build: fix goreleaser configuration

---

test-integration/test_integration/util.py

- need to use force as image is used by container (stopped)

fix: test fixture does not remove docker image

---

docs/python.md

Resolves https://github.com/replicate/cog/issues/1458

fix output variable name in path docs example

---

Makefile
python/cog/command/ast_openapi_schema.py
python/cog/command/openapi_schema.py
python/cog/schema.py
python/cog/server/http.py
python/cog/server/webhook.py
python/cog/server/worker.py
python/cog/types.py

#1496 and others introduced formatting errors. let's add ruff format --check to CI. I'm also open to using black instead (since we have it in pyproject) or removing black altogether

format and add formatting to ci

---

Makefile

Signed-off-by: technillogue <technillogue@gmail.com>

allow environ to override go and python versions

---

CONTRIBUTING.md
go.mod

Required for https://github.com/replicate/cog/pull/1536

Upgrade to Go 1.21

---

.vscode/settings.json

Set VSCode default formatter to `charliermarsh.ruff`

---

python/cog/command/openapi_schema.py
python/cog/schema.py

Signed-off-by: technillogue <technillogue@gmail.com>

a new version of ruff has appeared

---

python/cog/command/openapi_schema.py
test-integration/test_integration/fixtures/complex_output_project/cog.yaml
test-integration/test_integration/fixtures/complex_output_project/predict.py
test-integration/test_integration/test_build.py

Issue: https://github.com/replicate/cog/issues/1275

fix: invalid components: schema "Output": extra sibling fields: [title]

---

.github/workflows/build-bases.yaml
pkg/cli/baseimage.go
pkg/cli/build.go
pkg/config/config.go
pkg/docker/build.go
pkg/dockerfile/base.go

Remove buildkit version validation and implement GH Action for building bases
* Push action does not actually push to registry yet.

GH Action Support

---

docs/environment.md

Resolves https://github.com/replicate/cog/issues/1701

Update environment variables documentation

---

python/cog/predictor.py
python/cog/server/http.py
python/cog/types.py

Added a new TypedDict representing config.yaml contents and replaced config's types around the codebase.
@allcontributors please add @JacekDuszenko for code

Change config's type to TypedDict instead of Dict.

---

pkg/dockerfile/generator.go

Use timestamps for tmp build directories

---

docs/deploy.md

Document `--host` option

---

README.md

Update README with working combination of Python and Torch

---

.github/workflows/release.yaml

Check that the release tag is a version tag (v[0-9].[0-9]+.[0-9]+) and that the workflow is triggered by a new tag push.

Check release tag

---

python/cog/predictor.py

This doesn't appear to be used anywhere

Remove `run_prediction`

---

python/cog/server/helpers.py
python/cog/server/worker.py
python/tests/server/test_helpers.py

This commit simplifies the use of StreamRedirector:
- make the wrapping and unwrapping of streams happen automatically through a context manager
- default to wrapping STDOUT and STDERR if streams are not explicitly provided
This paves the way to using a different AsyncStreamRedirector when this implementation of StreamRedirector is not appropriate.
_~There are probably some things in here that won't work in Python 3.7/3.8... I'm going to wait for the tests to tell me about that.~_

Make StreamRedirector a context manager

---

pkg/dockerfile/base.go

* We need to check the python and torch minimum versions before we add that config to the matrix

Fix generating matrix with all CPU torches

---

pkg/dockerfile/generator_test.go

* Add a test to prevent -march cflags from being a part of the generation

Add test against -march

---

python/cog/server/worker.py

This naive implementation of the observer pattern both leaks memory and causes a very slow performance degradation over time as the `_subscribers` dictionary gets larger and larger, mostly full of `None` values.
This replaces the implementation with one that ensures that repeated subscribe/unsubscribe calls don't affect performance or memory consumption.

Fix memory leak

---

pkg/dockerfile/generator_test.go

* In flight collision between 2 PRs merged at different times.

Fix generator test

---

python/cog/server/worker.py

Unwrapping and re-wrapping stdout and stderr after setup and before the main loop seems to cause weird errors with some models.  Specifically, models that work by launching a subprocess (such as fofr/cog-comfyui) get into a broken state when we do this.
It's possible that there's a way to do the unwrapping that doesn't break these models but I'm unsure how we do that.
I've tested that this fixes the problems with fofr/cog-comfyui we were seeing with 0.9.21..0.9.23.

Don't unwrap and re-wrap streams

---

python/cog/types.py
python/tests/test_types.py

The commit 3805e2e introduced the `filename` keyword argument to the `URLFile` constructor. However we do not correctly propagate that value when the instance is pickled resulting in the `URLFile` that is passed to the upload handler missing that attribute.
This PR updates the code to stash the `name` when pickling and extract it again when unpickling. The `__getattr__` function then supports returning the underlying `name` value rather than proxying to the underlying request object.
I also ran into a small bug whereby the `__del__` method was triggering a network request because of some private attributes being accessed during teardown would trigger the `__wrapper__` code. I've overridden the super class to disable this. Though I'm unclear if this is just the test suite doing this …

[async] Propagate `URLFile.name` attribute across serialization

---

python/cog/command/ast_openapi_schema.py
python/cog/env_property.py
python/cog/predictor.py
python/cog/schema.py
python/cog/server/helpers.py
python/cog/server/telemetry.py
python/cog/server/useragent.py
python/cog/types.py
python/tests/server/test_http_input.py
python/tests/server/test_worker.py
test-integration/test_integration/test_predict.py
test-integration/test_integration/util.py

A few bits and pieces that can be simplified now we require python >= 3.8.

More python 3.7 tidying

---

pkg/config/torch_compatibility_matrix.json

* Add torch 2.5.1 to the compatibility matrix

Support torch 2.5.1

---

pkg/cli/run.go
tools/install.sh

fix some comments, including fix the function name in comment and some typos

chore: fix some comments

---

test-integration/test_integration/fixtures/ffmpeg-package/cog.yaml
test-integration/test_integration/fixtures/ffmpeg-package/predict.py
test-integration/test_integration/test_build.py

* Add an integration test to check for `ffmpeg` in the base image.

Add test for ffmpeg in base images

---

test-integration/test_integration/fixtures/ffmpeg-package/cog.yaml

* Python 3.12 doesn’t work for ffmpeg

Change ffmpeg int test to 3.12

---

pkg/docker/fast_push.go

* Handle status `201` when creating an upload request
* Add `Cog/[Version]` to the `User-Agent` header
* Use the `"auto"` region in the S3 configuration

Fast Push Fixes

---

pkg/cli/predict.go

On replicate.com, a model with return type `Path` can return a URL, and it is handled as though the model returned a local file path.
Locally, `cog predict` will fail with
```
ⅹ Failed to write output: Failed to decode dataurl: missing data prefix
```
This change makes `cog predict` download and save the output URL.
The `useExtensionIfUnknownContentType` is mostly needed because .webp is incorrectly returned by replicate.delivery as application/octet-stream.

Handle URL `Path` in `cog predict`

---

pkg/monobeam/client.go
pkg/monobeam/client_test.go

* Monobeam client was recreating a standard HTTP client rather than using the one injected.

Fix monobeam client not authenticating properly

---

pkg/docker/fast_push_test.go
pkg/docker/push_test.go
pkg/web/client.go
pkg/web/env.go

Update the API endpoint we hit for creating new versions as the name of the endpoint has changed
See #2135's test plan

Update API endpoint in accordance with new name

---

pkg/dockerfile/fast_generator.go

See [this PR](https://github.com/replicate/monobase/pull/82) in monobase

Update CDN URL

---

pkg/config/config.go
pkg/config/config_test.go
pkg/dockerfile/fast_generator.go
pkg/dockerfile/fast_generator_test.go
test-integration/test_integration/fixtures/fast-build/predict.py

https://github.com/replicate/cog-runtime/pull/49
Removing it from `cog.yaml`

Move fast push test to cog-runtime

---

pkg/dockerfile/build_tempdir.go
pkg/dockerfile/build_tempdir_test.go
pkg/dockerfile/fast_generator.go
pkg/dockerfile/fast_generator_test.go

* So that changes in one layer does not invalidate everything else

Separate tmp mounts for fast layers

---

README.md

* Make it clear that this accepts an image as an input path and returns a path to the transformed
image.

Add a simple explanation for the standard predictor

---

pkg/docker/docker_command.go

* We need to specify the platform when pulling

Support pulling monobase in macOS

---

test-integration/test_integration/fixtures/fast-build/cog.yaml

Remove tests from fast-build cog.yaml

---

docs/yaml.md
pkg/config/config.go

* These fields have been deprecated for a while, make it clear to the user that they will be removed in future versions.
* Add the necessary documentation.

Warn the user when they use deprecated fields

---

pkg/config/requirements.go
pkg/config/requirements_test.go

This reverts commit bc4b95e070b271e06d796d335986791908271fd0.

Revert "Support Python requirements package[extra,...]==version (#2160)"

---

python/cog/predictor.py
python/cog/server/http.py
test-integration/test_integration/fixtures/pydantic2-output/cog.yaml
test-integration/test_integration/fixtures/pydantic2-output/predict.py
test-integration/test_integration/fixtures/pydantic2-output/train.py
test-integration/test_integration/test_train.py

* Add support for `Optional` arguments into a `predict` or `train` method

Support Optional in Input

---

pkg/monobeam/client.go
pkg/monobeam/client_test.go

* Call correct URL path
* Add test for response correctness

Fix pre-upload call

---

test-integration/test_integration/fixtures/install-requires-packaging/cog.yaml
test-integration/test_integration/fixtures/install-requires-packaging/predict.py
test-integration/test_integration/fixtures/install-requires-packaging/requirements.txt
test-integration/test_integration/test_build.py

* Add integration test for a package that requires packaging in fast push

Fix install requires packaging

---

pkg/cli/predict.go
test-integration/test_integration/test_predict.py

* Build the image on `cog predict` if we are running a fast boot image

Build the image on predict in fast boots

---

pkg/docker/fast_push_test.go
pkg/docker/push_test.go
pkg/web/client.go
pkg/web/client_test.go

Add new version log

---

pkg/predict/input.go
test-integration/test_integration/fixtures/complex-types-list-project/cog.yaml
test-integration/test_integration/fixtures/complex-types-list-project/predict.py
test-integration/test_integration/fixtures/complex-types-list-project/requirements.txt
test-integration/test_integration/test_predict.py

* Allow cog predict to handle JSON lists

Add support for lists of dicts in cog predict

---

pkg/image/build.go

* If the build is not a fast build, send the user a message about using fast boots

Add callout to move users towards fast-boots

---

pkg/migrate/migrator_v1_v1fast_test.go
pkg/migrate/overwrite_yaml.go
pkg/migrate/overwrite_yaml_test.go
test-integration/test_integration/test_predict.py

* Can't blindly reassign contents, need to consider when to add/remove on mapping nodes

Fix keeping comments in yaml

---

pkg/image/build.go

This reverts commit f5bb1debedc65ab5a71a982b503a731646dd2c67.

Revert "Add callout to move users towards fast-boots (#2322)"

---

pkg/config/torch_compatibility_matrix.json
pkg/dockerfile/fast_generator.go

This reverts commit 92cf6a7424dfe828c24bb414a6154648c34f4b6b.
This is no longer necessary

Revert "Add torch 2.5.0 CUDA 12.4.1 to matrix (#2350)"

---

test-integration/test_integration/fixtures/torch-270-cuda-126/cog.yaml
test-integration/test_integration/fixtures/torch-270-cuda-126/predict.py
test-integration/test_integration/test_build.py
test-integration/test_integration/test_predict.py

* Create an integration test to make sure this works

Test torch 2.7.0 cuda 12.6 works as a base image

---

pkg/config/cuda_base_images.json

Revert "Remove CUDA 12.6 ubuntu 24.04"

---

pkg/api/client.go
pkg/api/client_test.go

* Draft sources can now be pulled using draft:user/digest
* Extracts tarball logic into lower function, only Significant change is the URL processing

Add support for pulling draft sources

---

pkg/config/config.go
pkg/config/config_test.go
pkg/dockerfile/standard_generator.go
pkg/dockerfile/standard_generator_test.go
pkg/requirements/requirements.go
pkg/requirements/requirements_test.go

* If we are installing coglet, skip installing cog

Fix coglet stomping on cog installation

---

pkg/docker/api_client.go
pkg/docker/command/context_inspect.go

* Use docker context inspect to find endpoints
* Assign these endpoints to the environment variable

Handle overriding docker host if required

---

pkg/docker/host.go

In #2444 I accidentally printed a "normal" error as a warning instead of a debug message. This changes it to a debug message and adds some more to give more context around how cog finds the docker host.

Fix debug message, more debug logging

---

pkg/config/config.go
pkg/config/config_test.go
pkg/config/data/config_schema_v1.0.json
pkg/dockerfile/monobase_matrix.go
pkg/dockerfile/standard_generator.go

Depends on new cogless-cog-base-images https://github.com/replicate/cog/pull/2440

Add cog_runtime flag

---

pkg/dockerfile/standard_generator.go

To be merged before 0.16.0 release.

Add warning for cog_runtime flag

---

python/cog/command/call_graph.py

* Deduplicate usages of replicate.use

Deduplicate includes

---

pkg/dockerfile/standard_generator.go
pkg/dockerfile/standard_generator_test.go

* OpenCV now requires these build packages to install

Install opencv related build packages

---

pkg/dockerfile/standard_generator.go
pkg/dockerfile/standard_generator_test.go

* Attempt to make `opencv-python` install on python 3.13

Allow wheel >= 1 to be installed

---

pkg/predict/input.go
test-integration/test_integration/fixtures/cog-runtime-float/cog.yaml
test-integration/test_integration/fixtures/cog-runtime-float/predict.py
test-integration/test_integration/fixtures/cog-runtime-int/cog.yaml
test-integration/test_integration/fixtures/cog-runtime-int/predict.py
test-integration/test_integration/test_predict.py

* Check if cog-runtime and cog combined can receive a float input from the CLI

Add integration test for float with cog-runtime

---

CONTRIBUTING.md

update docs about the release process
